Repository Automattic/pocket-casts-ios, pull requests merged in 2023-10, with the labels that each got.

#1146 Enable the Patron feature flag
  CHANGELOG.md
  podcasts/FeatureFlag.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
Labels: Patron

#1147 Adds a remote feature flag for Patron
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/IapHelper.swift
  podcasts/Settings.swift
Labels: Patron

#1148 Moves the Patron cloud storage value to remote config
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Settings.swift
Labels: Patron

#1151 Fix TracksLogging crash
  podcasts/Analytics/Adapters/Tracks/TracksAdapter.swift
  podcasts/Analytics/Analytics.swift
  podcasts/AppDelegate+Analytics.swift
  podcasts/AppDelegate.swift
  podcasts/FeatureFlag.swift
Labels: analytics

#1145 EOY 2023: Intro Story
  podcasts/End of Year/Stories/IntroStory.swift
  podcasts/EndOfYear.xcassets/20.imageset/20@2x.png
  podcasts/EndOfYear.xcassets/20.imageset/20@3x.png
  podcasts/EndOfYear.xcassets/20.imageset/Contents.json
  podcasts/EndOfYear.xcassets/2023-title.imageset/Contents.json
  podcasts/EndOfYear.xcassets/2023-title.imageset/eoy_2023_title_@2x.png
  podcasts/EndOfYear.xcassets/2023-title.imageset/eoy_2023_title_@3x.png
  podcasts/EndOfYear.xcassets/23.imageset/23@2x.png
  podcasts/EndOfYear.xcassets/23.imageset/23@3x.png
  podcasts/EndOfYear.xcassets/23.imageset/Contents.json
  podcasts/Onboarding/Patron/PatronAppIconUnlock.swift
  podcasts/SwiftUI/ProportionalValue.swift
Labels: End of Year

#1150 EOY 2023: listened number story
  podcasts.xcodeproj/project.pbxproj
  podcasts/DMSans.ttf
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/Stories/ListenedNumbersStory.swift
  podcasts/End of Year/Stories/Views/CommonStoryViews.swift
  podcasts/End of Year/Stories/Views/PodcastCover.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  podcasts/podcasts-Info.plist
Labels: End of Year

#1155 EOY 2023: top podcast story
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/Stories/TopOnePodcastStory.swift
  podcasts/End of Year/Stories/Views/PodcastCover.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: End of Year

#1159 Bookmarks: Add a way to specify a feature is in early access
  podcasts/PaidFeature.swift
Labels: Bookmarks

#1160 Bookmarks: Adds early access what's new logic
  PocketCastsTests/Tests/Whats New/WhatsNewTests.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/WhatsNew.swift
Labels: Bookmarks

#1172 Bookmarks: What's New adds the design
  PocketCastsTests/Tests/Utilities/PaidFeatureTests.swift
  PocketCastsTests/Tests/Whats New/BookmarkAnnouncementViewModelTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Bookmarks/Bookmarks+Analytics.swift
  podcasts/Common SwiftUI/BookmarksLockedStateView.swift
  podcasts/IapHelper.swift
  podcasts/MainTabBarController.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
  podcasts/Profile - SwiftUI/Common Views/SubscriptionBadge.swift
  podcasts/ProfileViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/BookmarksAnnouncement.swift
  podcasts/Whats New/WhatsNew.swift
  podcasts/Whats New/WhatsNewView.swift
  podcasts/WhatsNew.xcassets/whatsnew-bookmarks.imageset/Contents.json
  podcasts/WhatsNew.xcassets/whatsnew-bookmarks.imageset/whatsnew-bookmarks@2x.png
  podcasts/WhatsNew.xcassets/whatsnew-bookmarks.imageset/whatsnew-bookmarks@3x.png
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#1173 Bookmarks: Update the upgrade message text
  podcasts/Common SwiftUI/BookmarksLockedStateView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#1157 EOY 2023: top five podcasts story
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/Stories/TopFivePodcastsStory.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Playback 2023

#1188 Disable new show notes and RSS artwork
  CHANGELOG.md
  podcasts/FeatureFlag.swift
Labels: Artwork

#1179 Remove unneeded env vars from Fastfile
  fastlane/Fastfile
Labels: tooling
