Repository Automattic/pocket-casts-ios, pull requests merged in 2023-04, with the labels that each got.

#806 Fix some issues with handling share links
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelelgate+SiriShortcuts.swift
  podcasts/CancelInfoViewController.swift
  podcasts/ChaptersViewController+Table.swift
  podcasts/EpisodeDetailViewController+ShowNotes.swift
  podcasts/ExpandedCollectionViewController.swift
  podcasts/ExpandedEpisodeListViewController.swift
  podcasts/MainTabBarController.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/SFSafariViewController+Creation.swift
  podcasts/ShowNotesPlayerItemViewController.swift
Labels: Bug

#805 Search Improvements: design tweaks
  podcasts.xcodeproj/project.pbxproj
  podcasts/CommonImages.xcassets/search.imageset/Contents.json
  podcasts/CommonImages.xcassets/search.imageset/search.pdf
  podcasts/New Search/Views/History/SearchHistoryCell.swift
  podcasts/New Search/Views/Results/PodcastCarouselView.swift
  podcasts/New Search/Views/Results/SearchResultCell.swift
  podcasts/New Search/Views/Results/ThemeableListHeader.swift
  podcasts/PCSearchBarController.xib
  podcasts/PodcastImage.swift
Labels: Search Improvements

#782 Ratings: Pulls ratings in from the API and displays them if they're available
  Modules/Server/Sources/PocketCastsServer/Public/Helpers/JSONDecodableURLTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/Helpers/URL+Throwing.swift
  Modules/Server/Sources/PocketCastsServer/Public/Ratings/RetrievePodcastRatingTask.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/Int+RoundingAbbreviations.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/FeatureFlag.swift
  podcasts/PCHostingController.swift
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastViewController.swift
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/StarRatingView.swift
  podcasts/SwiftUI/View+UIView.swift
Labels: UI Related

#811 Updates the podcast results scrollview on the new search to use the new HorizontalCarousel
  Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/Notification.Name+Publisher.swift
  podcasts/New Search/Views/Results/PodcastCarouselView.swift
  podcasts/SwiftUI/DismissKeyboardOnScroll.swift
  podcasts/SwiftUI/HorizontalCarousel.swift
Labels: Search Improvements

#810 Make author and title optional to avoid decoding issues
  Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
  podcasts/New Search/Views/Results/PodcastCarouselView.swift
  podcasts/New Search/Views/Results/SearchResultCell.swift
  podcasts/PodcastImage.swift
Labels: Search Improvements

#823 SSO: enable it and fix Sonos
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ExchangeSonosTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+SocialAuth.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler.swift
  podcasts/AuthenticationHelper.swift
  podcasts/FeatureFlag.swift
  podcasts/SonosLinkController.swift
Labels: SSO

#822 Patron: add subscription prices
  Pocket Casts Configuration.storekit
  podcasts/Constants.swift
  podcasts/IapHelper.swift
  podcasts/Onboarding.xcassets/Plus/icon-patron-button-selected.imageset/Contents.json
  podcasts/Onboarding.xcassets/Plus/icon-patron-button-selected.imageset/icon-patron-button-selected.pdf
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusButtonStyles.swift
  podcasts/Onboarding/Plus/PlusLandingView.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/PlusPurchaseModal.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Patron

#828 Use CI Toolkit SPM caching action
  .buildkite/cache_builder.yml
  .buildkite/commands/build.sh
  .buildkite/commands/release-build.sh
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  fastlane/Fastfile
Labels: tooling

#833 Patron: update upgrade screen
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/Plus/PlusButtonStyles.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Patron

#840 Patron: update logged-out flow
  podcasts/Constants.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/PlusLandingView.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/PlusPurchaseModal.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/SettingsViewController.swift
  podcasts/SwiftUI/HorizontalCarousel.swift
Labels: Patron
