Repository Automattic/pocket-casts-ios, pull requests merged in 2023-06, with the labels that each got.

#893 Specify public as the logging privacy to allow logs to show up in Xcode 15
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileLog.swift
Labels: iOS 17

#896 Bookmarks: Add a new tab to the player
  podcasts.xcodeproj/project.pbxproj
  podcasts/Bookmarks/Player/BookmarksPlayerTab.swift
  podcasts/PlayerContainerViewController+Update.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PlayerTabsView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#897 Bookmarks: Update the data structure
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/BookmarkDataManager.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/BookmarkDataManagerTests.swift
  podcasts/BookmarkManager.swift
Labels: Bookmarks

#882 Support: improve Watch logs
  CHANGELOG.md
  podcasts/PCMessageSupportViewModel.swift
  podcasts/ReadOnlyTextView.swift
  podcasts/Strings+Generated.swift
  podcasts/SupportConfig.swift
  podcasts/WatchManager+Send.swift
  podcasts/WatchManager.swift
  podcasts/Zendesk/FileLog+FileUpload.swift
  podcasts/Zendesk/MessageSupportView.swift
  podcasts/Zendesk/MessageSupportViewModel.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement

#899 Fix KingFisher from infinitely requesting the profile image when it returns 404
  podcasts/Profile - SwiftUI/Common Views/ProfileImage.swift
Labels: Bug

#909 Fix SmartLess not appearing in search results
  podcasts/New Search/Views/Results/PodcastCarouselView.swift
Labels: Bug

#916 Bookmarks: Adds the Add Bookmark player shelf action
  podcasts.xcodeproj/project.pbxproj
  podcasts/Bookmarks.xcassets/Contents.json
  podcasts/Bookmarks.xcassets/bookmarks-shelf-icon.imageset/Contents.json
  podcasts/Bookmarks.xcassets/bookmarks-shelf-icon.imageset/bookmarks-shelf-player.pdf
  podcasts/Bookmarks.xcassets/bookmarks-shelf-overflow-icon.imageset/Contents.json
  podcasts/Bookmarks.xcassets/bookmarks-shelf-overflow-icon.imageset/bookmarks-shelf.pdf
  podcasts/Enumerations.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/Settings.swift
  podcasts/ShelfActionsViewController+Table.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#914 Episodes Autoplay: extract SQL queries to its own class
  podcasts.xcodeproj/project.pbxproj
  podcasts/DownloadsViewController.swift
  podcasts/EpisodeTableHelper.swift
  podcasts/EpisodesDataManager.swift
  podcasts/ListeningHistoryViewController.swift
  podcasts/PlaylistRefreshOperation.swift
  podcasts/PodcastEpisodesRefreshOperation.swift
  podcasts/StarredViewController.swift
  podcasts/UploadedViewController.swift
Labels: Episodes Autoplay

#917 Episodes Autoplay: add a new option in Settings
  podcasts/Constants.swift
  podcasts/FeatureFlag.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Episodes Autoplay

#923 Episodes Autoplay: persist from where the episode started playing
  PocketCastsTests/Tests/Playback/AutoplayHelperTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AutoplayHelper.swift
  podcasts/DownloadsViewController+Table.swift
  podcasts/EpisodeCell.swift
  podcasts/EpisodeDetailViewController+Actions.swift
  podcasts/EpisodeDetailViewController.swift
  podcasts/PlaybackActionHelper.swift
  podcasts/PlaylistViewController+TableData.swift
  podcasts/PodcastViewController+TableData.swift
  podcasts/StarredViewController+Table.swift
  podcasts/UploadedViewController+Table.swift
  podcasts/UserEpisodeDetailViewController+Table.swift
  podcasts/UserEpisodeDetailViewController.swift
Labels: Episodes Autoplay

#932 Episodes Autoplay: play the next episode
  podcasts/AutoplayHelper.swift
  podcasts/EpisodesDataManager.swift
  podcasts/PlaybackManager.swift
  podcasts/PodcastViewController+TableData.swift
  podcasts/Settings.swift
Labels: Episodes Autoplay

#939 Episodes Autoplay: enable it only for new users
  podcasts/AppDelegate+Defaults.swift
  podcasts/Settings.swift
Labels: Episodes Autoplay

#940 Episodes Autoplay: add CarPlay support
  podcasts/CarPlaySceneDelegate+Convert.swift
  podcasts/CarPlaySceneDelegate+Interaction.swift
  podcasts/CarPlaySceneDelegate+Tabs.swift
Labels: Episodes Autoplay

#942 Episodes Autoplay: add Watch (Phone source) support
  Pocket Casts Watch App Extension/DownloadListView.swift
  Pocket Casts Watch App Extension/EpisodeDetailsViewModel.swift
  Pocket Casts Watch App Extension/EpisodeListView.swift
  Pocket Casts Watch App Extension/EpisodeView.swift
  Pocket Casts Watch App Extension/FilesListView.swift
  Pocket Casts Watch App Extension/FilterEpisodeListView.swift
  Pocket Casts Watch App Extension/NowPlayingContainerView.swift
  Pocket Casts Watch App Extension/NowPlayingViewModel.swift
  Pocket Casts Watch App Extension/PhoneSourceViewModel.swift
  Pocket Casts Watch App Extension/PlaySourceViewModel.swift
  Pocket Casts Watch App Extension/PodcastEpisodeListView.swift
  Pocket Casts Watch App Extension/SessionManager+Send.swift
  Pocket Casts Watch App Extension/UpNextView.swift
  Pocket Casts Watch App Extension/WatchSourceViewModel.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AutoplayHelper.swift
  podcasts/WatchConstants.swift
  podcasts/WatchManager.swift
Labels: Episodes Autoplay
