Repository Automattic/pocket-casts-ios, pull requests merged in 2023-02, with the labels that each got.

#688 Single Sign On
  .configure
  .configure-files/GoogleSignIn.plist.enc
  .configure-files/GoogleSignIn.txt.enc
  .configure-files/google_cloud_keys.json.enc
  .configure-files/pocket_casts_credentials.json.enc
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Private/TokenHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+Account.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+SocialAuth.swift
  Modules/Server/Sources/PocketCastsServer/Public/Models/AuthenticationResponse.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
  Pocket Casts Watch App Extension/WatchSyncManager.swift
  PocketCastsTests/Tests/BackgroundSignOutListenerTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/AccountViewController.swift
  podcasts/Analytics/AnalyticsDescribable+Modules.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate.swift
  podcasts/AuthenticationHelper.swift
  podcasts/BackgroundSignOutListener.swift
  podcasts/Credentials/ApiCredentials.tpl
  podcasts/Login/AppleSocialLogin.swift
  podcasts/Login/GoogleSocialLogin.swift
  podcasts/Login/SocialLogin.swift
  podcasts/Login/SocialLoginFactory.swift
  podcasts/MainTabBarController.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
  podcasts/NewEmailViewController.swift
  podcasts/Onboarding/Login/LoginLandingView.swift
  podcasts/Onboarding/Login/SyncLoadingAlert.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/ProfileIntroViewController.swift
  podcasts/ProfileIntroViewController.xib
  podcasts/ShiftyLoadingAlert.swift
  podcasts/SonosLinkController.swift
  podcasts/SonosLinkController.xib
  podcasts/Strings+Generated.swift
  podcasts/SyncSigninViewController.swift
  podcasts/ThemeableRoundedButton.swift
  podcasts/UIButton+EasyActions.swift
  podcasts/WatchConstants.swift
  podcasts/WatchManager.swift
  podcasts/en.lproj/Localizable.strings
  podcasts/podcasts-Info.plist
  scripts/build-phases/post-build-update-plist.sh
Labels: SSO

#689 i18n: Add Catalan
  fastlane/Fastfile
  podcasts.xcodeproj/project.pbxproj
  podcasts/ca.lproj/InfoPlist.strings
  podcasts/ca.lproj/Intents.strings
  podcasts/ca.lproj/Localizable.strings
Labels: i18n

#685 Starred: display starred on Profile for logged out users
  CHANGELOG.md
  podcasts/ProfileViewController.swift
  podcasts/StarredViewController.swift
Labels: enhancement

#695 Update the Buildkite CI image to Xcode 14.2
  .buildkite/cache_builder.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  README.md
Labels: tooling

#703 Add higher CI priority to release builds
  .buildkite/release-builds.yml
Labels: tooling

#694 Onboarding: do not push user to Plus view if they didn't signed in
  podcasts/Onboarding/LoginCoordinator.swift
Labels: Onboarding

#710 Add initial Search Improvements structure
  podcasts.xcodeproj/project.pbxproj
  podcasts/DiscoverViewController+Search.swift
  podcasts/DiscoverViewController.swift
  podcasts/FeatureFlag.swift
  podcasts/New Search/SearchResultsViewController.swift
  podcasts/PodcastListSearchResultsController.swift
  podcasts/PodcastListViewController+Search.swift
  podcasts/PodcastListViewController.swift
Labels: Search Improvements

#729 Remove iOS 14 support
  Modules/DataModel/Package.swift
  Modules/Server/Package.swift
  Modules/Utils/Package.swift
  Podfile
  Podfile.lock
  WidgetExtension/Up Next/CompactWhenNecessaryEpisodeView.swift
  WidgetExtension/Up Next/EpisodeView.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AboutView.swift
  podcasts/End of Year/Stories/Views/CommonStoryViews.swift
  podcasts/MainTabBarController.swift
  podcasts/NameFolderView.swift
  podcasts/PodcastViewController.swift
  podcasts/Styles.swift
  podcasts/SwiftUI/HighlightedText.swift
Labels: enhancement

#732 Search Improvements: add "Search History" view
  podcasts.xcodeproj/project.pbxproj
  podcasts/New Search/SearchHistoryView.swift
  podcasts/New Search/SearchResultsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/Styles.swift
  podcasts/en.lproj/Localizable.strings
Labels: Search Improvements

#727 Auto scroll Discover Featured collection view by adhering to new AutoScroll protocol
  podcasts/FeatureFlag.swift
  podcasts/FeaturedSummaryViewController.swift
  podcasts/ThemeableCollectionView.swift
Labels: good first issue, UI Related, Discover

#737 Import OPML from URL
  .configure
  CHANGELOG.md
  Gemfile.lock
  podcasts/Constants.swift
  podcasts/Onboarding.xcassets/Import/opml_from_url.imageset/Contents.json
  podcasts/Onboarding.xcassets/Import/opml_from_url.imageset/opml_from_url.svg
  podcasts/Onboarding/Import/ImportDetailsView.swift
  podcasts/Onboarding/Import/ImportLandingView.swift
  podcasts/Onboarding/Import/ImportViewModel.swift
  podcasts/OpmlImporter.swift
  podcasts/PodcastManager.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement, Import
