Repository Automattic/pocket-casts-ios, pull requests merged in 2023-09, with the labels that each got.

#1098 Updates cloud storage to use the remote value
  podcasts/Constants.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusLandingView.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/PlusFeaturesView.swift
  podcasts/Settings.swift
Labels: Plus, UI Related

#1101 Display an alert if the user is purchasing in the beta
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/PurchaseReceiptTask.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/IapHelper.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Strings+Generated.swift
  podcasts/SubscriptionTier+L10n.swift
  podcasts/en.lproj/Localizable.strings
Labels: Plus, Patron

#1104 Enables the Patron feature flag
  CHANGELOG.md
  podcasts/FeatureFlag.swift
Labels: Patron

#1091 Subscribe route: fix logic that append "http://"
  CHANGELOG.md
  podcasts/AppDelegate+UrlHandling.swift
Labels: Bug

#1113 Disables the patron feature flag
  CHANGELOG.md
  podcasts/FeatureFlag.swift
Labels: Patron

#1119 Fix the player tabs not rendering correctly for some languages
  CHANGELOG.md
  podcasts/PlayerTabsView.swift
Labels: UI Related

#1120 Update the player tab colors when the episode changes
  CHANGELOG.md
  podcasts/PlayerContainerViewController+Update.swift
Labels: UI Related

#1123 Fixes Play / Pause not working on the Now Playing widget with user-added files
  CHANGELOG.md
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
  podcasts/AppPlayEpisodeIntentExtension.swift
Labels: Bug

#1126 Utility: Adds mapFirst method on Sequence
  Modules/Utils/Sources/PocketCastsUtils/Extensions/Sequence+Extensions.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/SequenceExtensionsTest.swift
Labels: refactoring

#1129 Fix watchOS app development profile
  podcasts.xcodeproj/project.pbxproj
Labels: tooling
