Repository Automattic/pocket-casts-ios, pull requests merged in 2023-12, with the labels that each got.

#1137 PCiOS: Update Fastfile with version model
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: tooling

#1238 Playback: small fixes for next year
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Playback 2023

#1253 Change WatchOS minimum deployment target to 8
  podcasts.xcodeproj/project.pbxproj
Labels: watchOS

#1254 7.53 Release: Merge changes from 7.53.0.4 into `trunk`
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
Labels: Releases

#1256 CI: PR #1195
  CHANGELOG.md
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/NowPlayingPlayerItemViewController+Update.swift
  podcasts/PlaybackManager.swift
  podcasts/ServerSyncManager.swift
  podcasts/ShelfLoadState.swift
Labels: enhancement

#1262 Playback 2023: re-generate the top 5 list link if user is sharing
  podcasts/Constants.swift
Labels: Playback 2023

#1261 Tooling: ensure "Releases" is added as a Label for each release-related PR
  fastlane/Fastfile
Labels: tooling

#1255 Bookmarks: Fix the bookmark player tab appearing in the wrong location
  podcasts/PlayerContainerViewController+Update.swift
Labels: Bookmarks

#1263 7.53 Release: Merge changes from 7.53.0.5 into `trunk`
  config/Version.xcconfig
  fastlane/Fastfile
  podcasts/Constants.swift
Labels: Releases

#1264 7.53 Release: Merge changes from 7.53.0.6 into `trunk`
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/MainServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  config/Version.xcconfig
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/PlayerContainerViewController+Update.swift
  podcasts/PodcastViewController+NetworkLoad.swift
  podcasts/Settings.swift
Labels: Releases

#1267 Player transition: small tweaks
  podcasts/MiniPlayerToFullPlayerAnimator.swift
  podcasts/PlayerContainerViewController+Gestures.swift
Labels: enhancement

#1268 7.53 Release: Merge changes from 7.53.0.7 into `trunk`
  config/Version.xcconfig
  podcasts/MiniPlayerToFullPlayerAnimator.swift
  podcasts/PlayerContainerViewController+Gestures.swift
Labels: Releases

#1270 Removes the discoverFeaturedAutoScroll feature flag
  podcasts/FeatureFlag.swift
  podcasts/ThemeableCollectionView.swift
Labels: tech debt

#1271 Remove the newSearch feature flag
  podcasts.xcodeproj/project.pbxproj
  podcasts/DiscoverPodcastSearchResultsController.swift
  podcasts/DiscoverPodcastSearchResultsController.xib
  podcasts/DiscoverViewController+Search.swift
  podcasts/DiscoverViewController.swift
  podcasts/FeatureFlag.swift
  podcasts/New Search/Views/Results/PodcastCarouselView.swift
  podcasts/New Search/Views/Results/RoundedSubscribeButtonView.swift
  podcasts/New Search/Views/Results/SearchResultCell.swift
  podcasts/PodcastListSearchResultsController.swift
  podcasts/PodcastListSearchResultsController.xib
  podcasts/PodcastListViewController+Search.swift
  podcasts/PodcastListViewController.swift
Labels: tech debt

#1265 Add theme support to the Up Next
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/AppearanceViewController.swift
  podcasts/Constants.swift
  podcasts/MiniPlayerViewController.swift
  podcasts/NothingUpNextCell.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/PlayerCell.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/ThemeableSwipeCell.swift
  podcasts/UpNextNowPlayingCell.swift
  podcasts/UpNextViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: Up Next, Themes

#1257 Adds a way to export the database and preferences from the Help & Feedback page
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/DatabaseExport.swift
  podcasts/OnlineSupportController.swift
  podcasts/StatusPageView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement

#1273 Cleanup: onboardingUpdates feature flag
  podcasts/FeatureFlag.swift
  podcasts/MainTabBarController.swift
  podcasts/PlusDetailsViewController.swift
  podcasts/ProfileViewController.swift
Labels: tech debt

#1274 Cleanup: Removes UpgradeRequiredViewController
  podcasts.xcodeproj/project.pbxproj
  podcasts/UpgradeRequiredViewController.swift
  podcasts/UpgradeRequiredViewController.xib
Labels: tech debt

#1275 Cleanup: Removes ProfileIntroViewController
  podcasts.xcodeproj/project.pbxproj
  podcasts/Constants.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/ProfileIntroViewController.swift
  podcasts/ProfileIntroViewController.xib
  podcasts/PromotionViewController.swift
  podcasts/SJUIUtils.swift
Labels: tech debt

#1278 Cleanup: Remove SelectPaymentFreqViewController
  podcasts.xcodeproj/project.pbxproj
  podcasts/SelectPaymentFreqViewController.swift
  podcasts/SelectPaymentFreqViewController.xib
Labels: tech debt

#1279 Cleanup: Remove ConfirmPaymentViewController
  podcasts.xcodeproj/project.pbxproj
  podcasts/ConfirmPaymentViewController.swift
  podcasts/ConfirmPaymentViewController.xib
  podcasts/NewEmailViewController.swift
Labels: tech debt

#1280 Cleanup: Removes NewSubscription
  podcasts.xcodeproj/project.pbxproj
  podcasts/NewEmailViewController.swift
  podcasts/NewSubscription.swift
  podcasts/Onboarding/LoginCoordinator.swift
Labels: tech debt

#1281 Cleanup: Removes the signInWithApple feature flag
  podcasts/FeatureFlag.swift
  podcasts/Onboarding/Login/LoginLandingView.swift
Labels: tech debt

#1282 Cleanup: Remove autoplay feature flag
  podcasts/AppDelegate+Defaults.swift
  podcasts/FeatureFlag.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/Settings.swift
Labels: tech debt

#1283 Cleanup: Removes the showRatings feature flag
  podcasts/FeatureFlag.swift
  podcasts/PodcastHeadingTableCell.swift
Labels: tech debt

#1285 Logs: use `actor` to avoid data race conditions
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileLog.swift
  Modules/Utils/Sources/PocketCastsUtils/Logging/LogEntry.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/General/SerialDispatchMock.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/Logging/LogBufferTests.swift
Labels: Bug, crash

#1287 Cache the EndOfYear.isEligible value
  podcasts/End of Year/EndOfYear.swift
  podcasts/ProfileViewController.swift
Labels: Playback 2023

#1289 Fix a crash when exporting the database on an iPad
  podcasts/DatabaseExport.swift
  podcasts/OnlineSupportController.swift
Labels: Bug

#1288 Player transition: fix a freeze when dismissing
  podcasts/MainTabBarController.swift
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/MiniPlayerViewController.swift
Labels: Bug

#1292 Player transition: disable
  podcasts/FeatureFlag.swift
Labels: Bug

#1294 Player: disable transition on TestFlight
  podcasts/FeatureFlag.swift
Labels: Bug

#1290 7.54 Release: Merge changes from 7.54.0.1 into `trunk`
  config/Version.xcconfig
  podcasts/DatabaseExport.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/MainTabBarController.swift
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/MiniPlayerViewController.swift
  podcasts/OnlineSupportController.swift
  podcasts/ProfileViewController.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1296 7.54 Release: Merge changes from 7.54.0.2 into `trunk`
  config/Version.xcconfig
  podcasts/FeatureFlag.swift
Labels: Releases

#1298 Player Transition: Fix the player not dismissing correctly when in the background
  podcasts/FeatureFlag.swift
  podcasts/MiniPlayerToFullPlayerAnimator.swift
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/MiniPlayerViewController.swift
Labels: Bug

#1301 Player transition: add remote feature flag
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/Settings.swift
Labels: Player

#1303 7.54 Release: Merge changes from 7.54.0.3 into `trunk`
  config/Version.xcconfig
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/FeatureFlag.swift
  podcasts/MiniPlayerToFullPlayerAnimator.swift
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/MiniPlayerViewController.swift
  podcasts/Settings.swift
  podcasts/ca.lproj/Localizable.strings
Labels: Releases

#1307 Player: do not allow landscape on the player
  podcasts/PlayerContainerViewController.swift
Labels: Player

#1308 7.54 Release: Merge changes from 7.54.0.4 into `trunk`
  config/Version.xcconfig
  podcasts/PlayerContainerViewController.swift
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
Labels: Releases

#1311 [Tooling] Remove legacy pipeline code after migration to Apple Silicon infra on CI
  .buildkite/cache_builder.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: tooling
