Repository Automattic/pocket-casts-ios, pull requests merged in 2023-11, with the labels that each got.

#1199 Update Release Toolkit to `9.2.0` and Cocoapods to `1.14.2`
  Gemfile.lock
Labels: tooling

#1163 Playback 2023: show total listening time
  podcasts/End of Year/Stories/ListeningTimeStory.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Playback 2023

#1164 Playback 2023: show longest episode listened to
  PocketCastsTests/Tests/End of Year/EndOfYearStoriesBuilderTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/Stories/ListenedCategoriesStory.swift
  podcasts/End of Year/Stories/LongestEpisodeStory.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Playback 2023

#1169 Playback 2023: entry point
  podcasts/Constants.swift
  podcasts/DeveloperMenu.swift
  podcasts/End of Year/Views/EndOfYearCard.swift
  podcasts/End of Year/Views/EndOfYearModal.swift
  podcasts/EndOfYear.xcassets/23_small.imageset/23.svg
  podcasts/EndOfYear.xcassets/23_small.imageset/Contents.json
  podcasts/EndOfYear.xcassets/modal_cover.imageset/Contents.json
  podcasts/EndOfYear.xcassets/modal_cover.imageset/modal_cover.svg
  podcasts/MainTabBarController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Playback 2023

#1174 Playback 2023: year over year listening time story
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  PocketCastsTests/Mocks/EndOfYearManagerMock.swift
  PocketCastsTests/Tests/End of Year/EndOfYearStoriesBuilderTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/Stories/YearOverYearStory.swift
  podcasts/Profile - SwiftUI/Common Views/SubscriptionBadge.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Playback 2023

#1178 Playback 2023: add a mechanism to skip "Plus stories" in sequence
  PocketCastsTests/Tests/End of Year/StoriesModelTests.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
Labels: Playback 2023

#1189 Playback 2023: Plus flow
  podcasts.xcodeproj/project.pbxproj
  podcasts/Constants.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/Stories/CompletionRateStory.swift
  podcasts/End of Year/Stories/EpilogueStory.swift
  podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
  podcasts/End of Year/Stories/YearOverYearStory.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/MainTabBarController.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Playback 2023

#1191 Playback 2023: add logic to sync 2022 and 2023 listening history
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
  PocketCastsTests/Tests/End of Year/EndOfYearStoriesBuilderTests.swift
  PocketCastsTests/Tests/End of Year/StoriesModelTests.swift
  podcasts/Constants.swift
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/EndOfYear.xcassets/2023-title.imageset/2023-title.svg
  podcasts/EndOfYear.xcassets/2023-title.imageset/Contents.json
  podcasts/EndOfYear.xcassets/2023-title.imageset/eoy_2023_title_@2x.png
  podcasts/EndOfYear.xcassets/2023-title.imageset/eoy_2023_title_@3x.png
  podcasts/Settings.swift
Labels: Playback 2023

#1192 Playback 2023: refinements and improvements
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
  podcasts/End of Year/Stories/CompletionRateStory.swift
  podcasts/End of Year/Stories/EpilogueStory.swift
  podcasts/End of Year/Stories/IntroStory.swift
  podcasts/End of Year/Stories/ListenedNumbersStory.swift
  podcasts/End of Year/Stories/ListeningTimeStory.swift
  podcasts/End of Year/Stories/TopCategoriesStory/TopListenedCategoriesStory.swift
  podcasts/End of Year/Stories/TopFivePodcastsStory.swift
  podcasts/End of Year/Stories/TopOnePodcastStory.swift
  podcasts/End of Year/Stories/Views/CommonStoryViews.swift
  podcasts/End of Year/Stories/Views/StoryLogoView.swift
  podcasts/End of Year/StoryShareableText.swift
  podcasts/EndOfYear.xcassets/0.imageset/0.svg
  podcasts/EndOfYear.xcassets/0.imageset/Contents.json
  podcasts/EndOfYear.xcassets/2.imageset/2.svg
  podcasts/EndOfYear.xcassets/2.imageset/Contents.json
  podcasts/EndOfYear.xcassets/20.imageset/20@2x.png
  podcasts/EndOfYear.xcassets/20.imageset/20@3x.png
  podcasts/EndOfYear.xcassets/20.imageset/Contents.json
  podcasts/EndOfYear.xcassets/22.imageset/22.svg
  podcasts/EndOfYear.xcassets/22.imageset/Contents.json
  podcasts/EndOfYear.xcassets/23.imageset/23@2x.png
  podcasts/EndOfYear.xcassets/23.imageset/23@3x.png
  podcasts/EndOfYear.xcassets/23.imageset/Contents.json
  podcasts/EndOfYear.xcassets/3.imageset/3.svg
  podcasts/EndOfYear.xcassets/3.imageset/Contents.json
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Playback 2023

#1193 Playback 2023: prompt user to share when a screenshot is taken
  podcasts/End of Year/Stories/EpilogueStory.swift
  podcasts/End of Year/Stories/IntroStory.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Playback 2023

#1196 Playback 2023: Tracks
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/End of Year/Stories/CompletionRateStory.swift
  podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
  podcasts/End of Year/StoriesModel.swift
Labels: Playback 2023

#1200 Bookmarks: Enables the What's New
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/ProfileViewController.swift
  podcasts/ShelfActionsViewController.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/BookmarksAnnouncement.swift
Labels: Bookmarks

#1201 Bookmarks: Adds the bookmarks remote feature flag
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/Settings.swift
Labels: Bookmarks

#1202 Enables the bookmarks feature flag
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  podcasts/FeatureFlag.swift
Labels: Bookmarks

#1204 Bookmarks + Playback: Add handling for when both the bookmarks what's new and the playback prompt will show
  podcasts/End of Year/EndOfYear.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/MainTabBarController.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/ProfileViewController.swift
  podcasts/ShelfActionsViewController.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/BookmarksAnnouncement.swift
Labels: Bookmarks, Playback 2023

#1203 Playback 2023: add animations to some stories
  PocketCastsTests/Tests/End of Year/StoriesModelTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/Animations/PlayPauseAnimatableModifier.swift
  podcasts/End of Year/Stories/ListenedNumbersStory.swift
  podcasts/End of Year/Stories/LongestEpisodeStory.swift
  podcasts/End of Year/Stories/TopFivePodcastsStory.swift
  podcasts/End of Year/Stories/TopOnePodcastStory.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/Views/StoriesView.swift
Labels: Playback 2023

#1206 Playback 2023: enable it
  CHANGELOG.md
  podcasts/FeatureFlag.swift
Labels: Playback 2023

#1208 Patron: change product IDs
  Pocket Casts Configuration.storekit
  podcasts/Constants.swift
Labels: Patron

#1211 Hotfix: change product ids
  Pocket Casts Configuration.storekit
  podcasts/Constants.swift
Labels: Patron

#1213 Playback 2023: fix completion rate SQL query
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
Labels: Playback 2023

#1118 Dangermattic Setup
  .buildkite/commands/danger-pr-check.sh
  .buildkite/commands/danger.sh
  .buildkite/pipeline.yml
  .rubocop.yml
  .rubocop_todo.yml
  Dangerfile
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  scripts/themes/generate_themes.rb
Labels: tooling

#1215 Playback 2023: fix hanging loading the episodes
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
  podcasts/End of Year/Stories/EpilogueStory.swift
Labels: Playback 2023

#1218 Playback 2023: design tweaks
  podcasts/End of Year/Animations/PlayPauseAnimatableModifier.swift
  podcasts/End of Year/Stories/CompletionRateStory.swift
  podcasts/End of Year/Stories/EpilogueStory.swift
  podcasts/End of Year/Stories/IntroStory.swift
  podcasts/End of Year/Stories/ListenedNumbersStory.swift
  podcasts/End of Year/Stories/ListeningTimeStory.swift
  podcasts/End of Year/Stories/LongestEpisodeStory.swift
  podcasts/End of Year/Stories/TopCategoriesStory/TopListenedCategoriesStory.swift
  podcasts/End of Year/Stories/TopFivePodcastsStory.swift
  podcasts/End of Year/Stories/TopOnePodcastStory.swift
  podcasts/End of Year/Stories/Views/CommonStoryViews.swift
  podcasts/End of Year/Stories/YearOverYearStory.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/EndOfYear.xcassets/2023-title.imageset/2023-title.svg
Labels: Playback 2023

#1220 Playback 2023: animates Year over Year
  podcasts/End of Year/Animations/PlayPauseAnimatableModifier.swift
  podcasts/End of Year/Stories/YearOverYearStory.swift
  podcasts/End of Year/Views/EndOfYearCard.swift
Labels: Playback 2023

#1223 Playback 2023: tweak parallax on the intro story
  Modules/Utils/Sources/PocketCastsUtils/Extensions/ComparableExtension.swift
  podcasts/End of Year/Stories/IntroStory.swift
  podcasts/SwiftUI/Motion.swift
Labels: Playback 2023

#1225 Bookmarks: Some design improvements
  podcasts/Bookmarks/Episode/EpisodeDetailTabView.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTab.swift
  podcasts/EpisodeBookmarksTabsView.swift
  podcasts/SwiftUI/ActionBarOverlayView.swift
Labels: Bookmarks

#1228 Bookmarks: fix colors when opening from Up Next
  podcasts/Bookmarks/BookmarksTheme.swift
  podcasts/Bookmarks/Episode/BookmarkEpisodeListController.swift
  podcasts/EpisodeDetailViewController.swift
Labels: Bookmarks

#1230 Playback 2023: tweak parallax on the intro story
  Modules/Utils/Sources/PocketCastsUtils/Extensions/ComparableExtension.swift
  podcasts/End of Year/Stories/IntroStory.swift
  podcasts/SwiftUI/Motion.swift
Labels: Playback 2023

#1233 Bookmarks: Ensure the whats new handler is called from the profile tab
  podcasts/ProfileViewController.swift
Labels: Bug, Bookmarks

#1232 End of Year: fix thread-safety access in iOS 17
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
Labels: Playback 2023

#1088 Player: improve transition
  Modules/Utils/Sources/PocketCastsUtils/Extensions/Sequence+Extensions.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/SequenceExtensionsTest.swift
  PocketCastsTests/Tests/BackgroundSignOutListenerTests.swift
  podcasts/AppDelegate.swift
  podcasts/BackgroundSignOutListener.swift
  podcasts/FeatureFlag.swift
  podcasts/MainTabBarController.swift
  podcasts/MiniPlayerViewController+Gestures.swift
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/MiniPlayerViewController.swift
  podcasts/PlayerContainerViewController+Gestures.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PlayerItemViewController.swift
  podcasts/SceneHelper.swift
  podcasts/UIViewController+Presenting.swift
  podcasts/VideoViewController.swift
Labels: UI Related

#1090 Player: custom transition
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts/MiniPlayerToFullPlayerAnimator.swift
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/MiniPlayerViewController+TransitionDelegate.swift
  podcasts/PlayerContainerViewController+Gestures.swift
  podcasts/PlayerContainerViewController.swift
Labels: UI Related

#1236 Moved `Help & Support` to Profile screen
  podcasts/CommonImages.xcassets/profile-help.imageset/Contents.json
  podcasts/CommonImages.xcassets/profile-help.imageset/help.svg
  podcasts/ProfileViewController.swift
  podcasts/Settings.xcassets/settings_help.imageset/help@2x.png
  podcasts/Settings.xcassets/settings_help.imageset/help@3x.png
  podcasts/SettingsViewController.swift
Labels: enhancement

#1243 7.53 Release: Merge changes from 7.53.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/Resources/release_notes.txt
Labels: Releases

#1244 Presentation: fix Playback 2023, About, Sonos and List
  podcasts/AboutView.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
  podcasts/UIViewController+Presenting.swift
Labels: Playback 2023

#1239 Folders issue: prevent the watch app from syncing folder changes
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
Labels: folders

#1245 7.53 Release: Merge changes from 7.53.0.1 into `trunk`
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
  config/Version.xcconfig
  podcasts/AboutView.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
  podcasts/UIViewController+Presenting.swift
Labels: Releases
