Repository Automattic/pocket-casts-ios, pull requests merged in 2023-07, with the labels that each got.

#912 Adjust ExtraDark theme's background color for Choose Podcasts/Create …
  CHANGELOG.md
  podcasts/CreateFolderView.swift
  podcasts/PodcastChooserViewController.xib
  podcasts/PodcastPickerView.swift
Labels: folders, UI Related

#946 Episodes Autoplay: Tracks
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/PlaybackManager.swift
Labels: Episodes Autoplay

#918 Add a playback_failed event
  PocketCastsTests/Tests/Analytics/AnalyticsCoordinatorTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsDescribable+Modules.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
  podcasts/Analytics/Helpers/AnalyticsPlaybackHelper.swift
  podcasts/DefaultPlayer.swift
  podcasts/EffectsPlayer.swift
  podcasts/PlaybackManager.swift
  podcasts/PlaybackProtocol.swift
Labels: playback, analytics

#935 Bookmarks: Add the Headphone Controls item to the settings list
  Modules/Utils/Sources/PocketCastsUtils/Extensions/Array+Extensions.swift
  podcasts/Settings.xcassets/settings_headphone_controls.imageset/Contents.json
  podcasts/Settings.xcassets/settings_headphone_controls.imageset/settings_headphone_controls.pdf
  podcasts/SettingsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#937 Bookmarks: Adds PCTableViewController
  podcasts.xcodeproj/project.pbxproj
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountPromptTableCell.swift
  podcasts/PCTableViewController.swift
  podcasts/Settings.xcassets/settings_headphone_controls_skip_back.imageset/Contents.json
  podcasts/Settings.xcassets/settings_headphone_controls_skip_back.imageset/settings_headphone_controls_skip_back.pdf
  podcasts/Settings.xcassets/settings_headphone_controls_skip_forward.imageset/Contents.json
  podcasts/Settings.xcassets/settings_headphone_controls_skip_forward.imageset/settings_headphone_controls_skip_forward.pdf
  podcasts/Strings+Generated.swift
  podcasts/ThemeableCell.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#938 Bookmarks: Add settings view
  Modules/Utils/Sources/PocketCastsUtils/Extensions/JSONCodable.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/BookmarkManager.swift
  podcasts/Constants.swift
  podcasts/HeadphoneSettingsViewController.swift
  podcasts/OptionAction.swift
  podcasts/OptionsPicker.swift
  podcasts/SettingsViewController.swift
Labels: Bookmarks

#936 Bookmarks: Adds the Settings properties
  Modules/Utils/Sources/PocketCastsUtils/Extensions/JSONCodable.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/BookmarkManager.swift
  podcasts/Constants.swift
  podcasts/HeadphoneSettingsViewController.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountPromptTableCell.swift
  podcasts/OptionAction.swift
  podcasts/OptionsPicker.swift
  podcasts/PCTableViewController.swift
  podcasts/Settings.swift
  podcasts/Settings.xcassets/settings_headphone_controls_skip_back.imageset/Contents.json
  podcasts/Settings.xcassets/settings_headphone_controls_skip_back.imageset/settings_headphone_controls_skip_back.pdf
  podcasts/Settings.xcassets/settings_headphone_controls_skip_forward.imageset/Contents.json
  podcasts/Settings.xcassets/settings_headphone_controls_skip_forward.imageset/settings_headphone_controls_skip_forward.pdf
  podcasts/SettingsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/ThemeableCell.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#957 Enable Autoplay
  CHANGELOG.md
  podcasts/FeatureFlag.swift
Labels: Episodes Autoplay

#966 Episode Swipe: add share action
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts/DownloadsViewController+Swipe.swift
  podcasts/ListeningHistoryViewController+Swipe.swift
  podcasts/PlaylistViewController+Swipe.swift
  podcasts/PodcastViewController+Swipe.swift
  podcasts/SharingHelper+swipeButton.swift
  podcasts/StarredViewController+Swipe.swift
  podcasts/SwipeActionsHelper.swift
  podcasts/UploadedViewController+Swipe.swift
Labels: enhancement

#970 Autoplay: change What's New copy
  fastlane/Frozen.strings
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Episodes Autoplay

#967 Adds new reusable SwiftUI Views/Extensions
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/Bookmark.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/BookmarkDataManager.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/BookmarkManager.swift
  podcasts/Bookmarks.xcassets/bookmarks-icon-play.imageset/Contents.json
  podcasts/Bookmarks.xcassets/bookmarks-icon-play.imageset/bookmarks-icon-play.pdf
  podcasts/Bookmarks/List/BookmarkListViewModel.swift
  podcasts/Bookmarks/List/BookmarkRow.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTab.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift
  podcasts/PlaybackManager.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PlayerTabsView.swift
  podcasts/Strings+Generated.swift
  podcasts/Strings+L10n.swift
  podcasts/SwiftUI/NonBlockingLongPressView.swift
  podcasts/SwiftUI/ScrollViewWithContentOffset.swift
  podcasts/SwiftUI/View+Buttonize.swift
  podcasts/Theme+Color.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#973 Adds the generic ListViewModel and MutliSelectListViewModel view model parent classes
  PocketCastsTests/Tests/Common SwiftUI/List View Model/ListViewModelTests.swift
  PocketCastsTests/Tests/Common SwiftUI/List View Model/MutliSelectListViewModel.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Common SwiftUI/List View/ListViewModel.swift
  podcasts/Common SwiftUI/List View/MultiSelectListViewModel.swift
Labels: Bookmarks

#974 Adds the MultiSelectRow and ActionBarOverlayView views
  podcasts.xcodeproj/project.pbxproj
  podcasts/Common SwiftUI/List View/MultiSelectRow.swift
  podcasts/SwiftUI/ActionBarOverlayView.swift
  podcasts/UIFont+FontStyle.swift
Labels: Bookmarks

#976 Bookmarks: Adds deleting of bookmarks from the list
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/BookmarkDataManager.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/BookmarkDataManagerTests.swift
  podcasts/BookmarkManager.swift
  podcasts/Bookmarks/List/BookmarkListViewModel.swift
Labels: Bookmarks

#975 Bookmarks: Adds the multi select mode and action bar
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/Bookmark.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/BookmarkDataManager.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/BookmarkDataManagerTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/BookmarkManager.swift
  podcasts/Bookmarks/List/BookmarkListViewModel.swift
  podcasts/Bookmarks/List/BookmarkRow.swift
  podcasts/Bookmarks/Player/ActionBarStyles.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTab.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#985 Share Extension: temporarily disable it
  podcasts.xcodeproj/project.pbxproj
Labels: Bug

#978 Bookmarks: Add title field
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/FMDatabaseQueue+Async.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/Bookmark.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/BookmarkDataManager.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/BookmarkDataManagerTests.swift
  podcasts/BookmarkManager.swift
  podcasts/Bookmarks/List/BookmarkRow.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#979 Bookmarks: Update the BookmarkManager
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/Bookmark.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/BookmarkDataManager.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/BookmarkDataManagerTests.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/Equatable+When.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/UI/Color+contrast.swift
  podcasts/BookmarkManager.swift
  podcasts/Bookmarks/List/BookmarkListViewModel.swift
  podcasts/Constants.swift
Labels: Bookmarks

#980 Bookmarks: Adds the add title view
  podcasts.xcodeproj/project.pbxproj
  podcasts/Bookmarks/Editing/BookmarkEditTitleView.swift
  podcasts/Bookmarks/Editing/BookmarkEditTitleViewController.swift
  podcasts/Bookmarks/Editing/BookmarkEditViewModel.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift
  podcasts/Strings+Generated.swift
  podcasts/Styles.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#981 Bookmarks: Adds editing of titles for existing bookmarks
  podcasts/Bookmarks/List/BookmarkListViewModel.swift
  podcasts/Bookmarks/List/BookmarkRow.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift
Labels: Bookmarks

#982 Bookmarks: Fix a bug that prevented the Add Bookmark item from appearing
  podcasts/Settings.swift
Labels: Bookmarks

#983 Bookmarks: Add sorting to the list
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/BookmarkDataManager.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/BookmarkDataManagerTests.swift
  podcasts/BookmarkManager.swift
  podcasts/Bookmarks/List/BookmarkListViewModel.swift
  podcasts/Bookmarks/List/BookmarkRow.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTab.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift
  podcasts/Constants.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#984 Bookmarks: Adds a way to customize the colors of the bookmark list
  podcasts.xcodeproj/project.pbxproj
  podcasts/Bookmarks/BookmarksTheme.swift
  podcasts/Bookmarks/List/BookmarkRow.swift
  podcasts/Bookmarks/Player/ActionBarStyles.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTab.swift
  podcasts/Common SwiftUI/List View/MultiSelectRow.swift
  podcasts/SwiftUI/ActionBarOverlayView.swift
Labels: Bookmarks

#992 Bookmarks: Show the toast message when a new bookmark is added
  podcasts/Bookmarks/Editing/BookmarkEditTitleViewController.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift
  podcasts/PlaybackManager.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PlayerItemViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#993 Bookmarks: Adds Empty State
  podcasts.xcodeproj/project.pbxproj
  podcasts/Bookmarks/Player/BookmarksPlayerTab.swift
  podcasts/Common SwiftUI/BookmarksEmptyStateView.swift
  podcasts/MainTabBarController.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
  podcasts/Strings+Generated.swift
  podcasts/SwiftUI/EmptyStateView.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bookmarks

#999 Bookmarks: Add a way to access the bookmarks from the podcast details
  podcasts.xcodeproj/project.pbxproj
  podcasts/Bookmarks/Podcast/BookmarksPodcastListView.swift
  podcasts/EpisodeBookmarksTabsView.swift
  podcasts/PCHostingController.swift
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastHeadingTableCell.xib
  podcasts/PodcastViewController+TableData.swift
  podcasts/PodcastViewController.swift
Labels: Bookmarks

#1001 Bookmarks: Adds a reusable SwiftUI SearchField view
  podcasts.xcodeproj/project.pbxproj
  podcasts/SwiftUI/SearchField.swift
Labels: Bookmarks

#1002 Bookmarks: Add SearchableListViewModel
  PocketCastsTests/Tests/Common SwiftUI/List View Model/SearchableListViewModelTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Common SwiftUI/List View/SearchableListViewModel.swift
Labels: Bookmarks
