Repository Automattic/pocket-casts-ios, pull requests merged in 2023-05, with the labels that each got.

#848 Adds an easier way to get themed colors from SwiftUI
  podcasts.xcodeproj/project.pbxproj
  podcasts/Theme+AppColors.swift
  podcasts/Theme+Color.swift
  podcasts/UIFont+FontStyle.swift
Labels: Patron

#849 Profile Updates: Makes some views reusable, and makes some changes to reuse logic
  Modules/Server/Sources/PocketCastsServer/Public/ServerEnums.swift
  Modules/Server/Sources/PocketCastsServer/Public/StatsManager.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/Double+formatTime.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsDescribable+Modules.swift
  podcasts/End of Year/Stories/EpilogueStory.swift
  podcasts/End of Year/Views/CircularProgressView.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/SwiftUI/ContentSizeGeometryReader.swift
  podcasts/SwiftUI/HolographicEffect.swift
  podcasts/SwiftUI/PageIndicatorView.swift
  podcasts/en.lproj/Localizable.strings
Labels: Patron

#852 Patron: Updates the account upsell prompt
  podcasts.xcodeproj/project.pbxproj
  podcasts/AccountActionCell.swift
  podcasts/AccountViewController+TableView.swift
  podcasts/AccountViewController.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountPromptTableCell.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/Theme+Plus.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/SwiftUI/HorizontalCarousel.swift
  podcasts/en.lproj/Localizable.strings
Labels: Patron

#853 Remove starred as a default filter
  CHANGELOG.md
  podcasts/PlaylistManager.swift
Labels: filters

#851 Patron: Updates the account details header
  podcasts.xcodeproj/project.pbxproj
  podcasts/AccountActionCell.swift
  podcasts/AccountViewController+TableView.swift
  podcasts/AccountViewController.swift
  podcasts/AccountViewController.xib
  podcasts/DeveloperMenu.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountPromptTableCell.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/Theme+Plus.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Profile - SwiftUI/Account/AccountHeaderView.swift
  podcasts/Profile - SwiftUI/Account/AccountHeaderViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/SwiftUI/HorizontalCarousel.swift
  podcasts/en.lproj/Localizable.strings
Labels: Plus, Patron

#850 Patron: Adds the updated profile header
  podcasts.xcodeproj/project.pbxproj
  podcasts/DeveloperMenu.swift
  podcasts/End of Year/Views/CircularProgressView.swift
  podcasts/Onboarding/Plus/Theme+Plus.swift
  podcasts/Profile - SwiftUI/Common Views/ProfileImage.swift
  podcasts/Profile - SwiftUI/Common Views/ProfileInfoLabels.swift
  podcasts/Profile - SwiftUI/Common Views/SubscriptionBadge.swift
  podcasts/Profile - SwiftUI/Common Views/SubscriptionProfileImage.swift
  podcasts/Profile - SwiftUI/Profile/ProfileHeaderView.swift
  podcasts/Profile - SwiftUI/View Models/ProfileDataViewModel.swift
  podcasts/Profile - SwiftUI/View Models/ProfileHeaderViewModel.swift
  podcasts/ProfileViewController.swift
  podcasts/ProfileViewController.xib
Labels: Patron

#842 Update Profile's header
  Modules/Server/Sources/PocketCastsServer/Public/ServerEnums.swift
  Modules/Server/Sources/PocketCastsServer/Public/StatsManager.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/Double+formatTime.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsDescribable+Modules.swift
  podcasts/AnimatedImageButton.swift
  podcasts/DeveloperMenu.swift
  podcasts/End of Year/Stories/EpilogueStory.swift
  podcasts/End of Year/Views/CircularProgressView.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/Onboarding/Plus/Theme+Plus.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Profile - SwiftUI/Common Views/ProfileImage.swift
  podcasts/Profile - SwiftUI/Common Views/ProfileInfoLabels.swift
  podcasts/Profile - SwiftUI/Common Views/SubscriptionBadge.swift
  podcasts/Profile - SwiftUI/Common Views/SubscriptionProfileImage.swift
  podcasts/Profile - SwiftUI/Profile/ProfileHeaderView.swift
  podcasts/Profile - SwiftUI/View Models/ProfileDataViewModel.swift
  podcasts/Profile - SwiftUI/View Models/ProfileHeaderViewModel.swift
  podcasts/ProfileProgressCircleView.swift
  podcasts/ProfileViewController.swift
  podcasts/ProfileViewController.xib
  podcasts/Strings+Generated.swift
  podcasts/SwiftUI/ContentSizeGeometryReader.swift
  podcasts/SwiftUI/HolographicEffect.swift
  podcasts/SwiftUI/PageIndicatorView.swift
  podcasts/Theme+AppColors.swift
  podcasts/Theme+Color.swift
  podcasts/UIFont+FontStyle.swift
  podcasts/en.lproj/Localizable.strings
Labels: Patron

#846 Fix playback speed label collapsed in German language
  podcasts/EffectsViewController.xib
  podcasts/TimeStepperCell.xib
Labels: UI Related

#861 Patron: Improve the Account prompt states
  Pocket Casts Configuration.storekit
  podcasts.xcodeproj/project.pbxproj
  podcasts/AccountViewController.swift
  podcasts/DeveloperMenu.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Profile - SwiftUI/Account/AccountHeaderView.swift
  podcasts/Profile - SwiftUI/Common Views/ProfileInfoLabels.swift
  podcasts/Profile - SwiftUI/Profile/ProfileHeaderView.swift
  podcasts/Profile - SwiftUI/View Models/ProfileDataViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/UserInfo.swift
  podcasts/en.lproj/Localizable.strings
Labels: Patron

#865 Patron: Add Initial Server Support
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/SubscriptionStatusTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerEnums.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  Modules/Server/Sources/PocketCastsServer/Public/SubscriptionHelper.swift
  Modules/Server/Tests/PocketCastsServerTests/SubscriptionTierTests.swift
  Pocket Casts Configuration.storekit
  podcasts/AccountViewController.swift
  podcasts/Analytics/Adapters/Tracks/TracksAdapter.swift
  podcasts/Analytics/Adapters/Tracks/TracksSubscriptionData.swift
  podcasts/Analytics/AnalyticsDescribable+Modules.swift
  podcasts/Constants.swift
  podcasts/DeveloperMenu.swift
  podcasts/IconSelectorCell.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Profile - SwiftUI/Account/AccountHeaderView.swift
  podcasts/Profile - SwiftUI/Common Views/SubscriptionBadge.swift
  podcasts/Profile - SwiftUI/Common Views/SubscriptionProfileImage.swift
  podcasts/Profile - SwiftUI/Profile/ProfileHeaderView.swift
  podcasts/UserInfo.swift
Labels: Patron

#876 Fix: Tracks Seeking Crash
  Modules/Utils/Sources/PocketCastsUtils/Extensions/Double+Extensions.swift
  PocketCastsTests/Tests/Analytics/AnalyticsPlaybackHelperTests.swift
  podcasts/Analytics/Helpers/AnalyticsPlaybackHelper.swift
Labels: Bug, crash

#877 Tracks: Only track the application installed / updated events if protected data is available
  podcasts/Analytics/AppLifecyleAnalytics.swift
Labels: analytics

#878 Fix: iOS 15 Warnings
  Modules/Utils/Sources/PocketCastsUtils/Extensions/UI/UIFontExtension.swift
  WidgetExtension/Up Next/UpNextProvider.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AboutView.swift
  podcasts/ActionIconButton.swift
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/DefaultPlayer.swift
  podcasts/DisclosureCell.xib
  podcasts/EpisodeListTableViewCell.xib
  podcasts/Login/AppleSocialLogin.swift
  podcasts/New Search/Views/Results/PodcastCarouselView.swift
  podcasts/PCViewController.swift
  podcasts/SceneHelper.swift
  podcasts/SingleEpisodeViewController.xib
  podcasts/ThemedSwitchToggleStyle.swift
Labels: iOS 15

#883 Revert: hidden chapters
  Pocket Casts Watch App Extension/WatchSourceViewModel.swift
  PocketCastsTests/Tests/Playback/Chapters/ChaptersTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/CarPlaySceneDelegate+Interaction.swift
  podcasts/ChapterInfo.swift
  podcasts/ChapterManager.swift
  podcasts/Chapters.swift
  podcasts/ChaptersViewController+Table.swift
  podcasts/ChaptersViewController.swift
  podcasts/NowPlayingHelper.swift
  podcasts/NowPlayingPlayerItemViewController+Update.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/PlaybackManager.swift
  podcasts/PlayerChapterCell.swift
  podcasts/PodcastChapterParser.swift
  podcasts/WatchManager.swift
Labels: Bug
