Repository Automattic/pocket-casts-ios, pull requests merged in 2024-09, with the labels that each got.

#2108 [Paywall Experiment] Reviews variant
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-slumber.imageset/Contents.json
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-slumber.imageset/moon-icon.svg
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-slumber.imageset/sleep-icon.svg
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-themes.imageset/icon-themes.svg
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/Features/PlusPaywallFeatureCard.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/Features/PlusPaywallFeaturesCarousell.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/PlusPaywallContainer.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/AppStoreInfo.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/PlusPaywallReviewCard.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/PlusPaywallReviews.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/PlusPaywallReviewsPlusFeatures.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/PlusPaywallReviewsStars.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/PlusPaywallReviewsViewModel.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/appStoreInfo.json
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Paywall Experiments

#2111 Improved create issue screen
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yml 
Labels: documentation

#2115 Fix enhancement file
  .github/ISSUE_TEMPLATE/enhancement.yml
Labels: [Type] Bug

#2114 Reimagine Sharing: What's New
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts Staging.xcscheme
  podcasts/Strings+Generated.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/ClipsWhatsNewView.swift
  podcasts/WhatsNew.xcassets/whatsnew_clip_preview.imageset/Contents.json
  podcasts/WhatsNew.xcassets/whatsnew_clip_preview.imageset/whatsnew_clip_preview.pdf
  podcasts/WhatsNew.xcassets/whatsnew_clips_instagram.imageset/Contents.json
  podcasts/WhatsNew.xcassets/whatsnew_clips_instagram.imageset/whatsnew_instagram.svg
  podcasts/WhatsNew.xcassets/whatsnew_clips_telegram.imageset/Contents.json
  podcasts/WhatsNew.xcassets/whatsnew_clips_telegram.imageset/whatsnew_telegram.svg
  podcasts/WhatsNew.xcassets/whatsnew_clips_tumblr.imageset/Contents.json
  podcasts/WhatsNew.xcassets/whatsnew_clips_tumblr.imageset/whatsnew_tumblr.svg
  podcasts/WhatsNew.xcassets/whatsnew_clips_whatsapp.imageset/Contents.json
  podcasts/WhatsNew.xcassets/whatsnew_clips_whatsapp.imageset/whatsnew_whatsapp.svg
  podcasts/en.lproj/Localizable.strings
Labels: Reimagine Sharing

#2091 Referrals: Entry point hint
  podcasts.xcodeproj/project.pbxproj
  podcasts/Constants.swift
  podcasts/ProfileViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/TipView.swift
  podcasts/en.lproj/Localizable.strings
Labels: Referrals

#2118 Update GoogleCast
  CHANGELOG.md
  Podfile.lock
Labels: [Type] Bug

#2112 Reimagine Sharing: Export Tweaks
  podcasts/End of Year/Views/View+Snapshot.swift
  podcasts/Sharing/AnimatedShareImageView.swift
  podcasts/Sharing/Clip/VideoExporter.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingFooterView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/View+CVPixelBuffer.swift
Labels: Reimagine Sharing

#2116 7.72 Release: Merge changes from 7.72.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2119 Reimagine Sharing: Export Tweaks for 7.72
  podcasts/End of Year/Views/View+Snapshot.swift
  podcasts/Sharing/AnimatedShareImageView.swift
  podcasts/Sharing/Clip/VideoExporter.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingFooterView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/View+CVPixelBuffer.swift
Labels: Reimagine Sharing

#2113 Reimagine Sharing: Enable feature flag
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Reimagine Sharing

#2125 Implement an adjustment variable to setup number of rows while animating
  CHANGELOG.md
  podcasts/ShelfActionsViewController+Table.swift
  podcasts/ShelfActionsViewController.swift
Labels: [Type] Bug, Player

#2134 Transcripts: Improve transcript shelf button color and action when no transcripts is available.
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/ShelfActionsViewController+Table.swift
  podcasts/Strings+Generated.swift
  podcasts/TranscriptShelfButton.swift
  podcasts/en.lproj/Localizable.strings
Labels: UI Related, [Project] Transcripts

#2127 Fix #2126: Add reimagine sharing support to Multi Selection
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
  podcasts/EpisodeDetailViewController.swift
  podcasts/MultiSelectHelper.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/SharingHelper+swipeButton.swift
  podcasts/SharingHelper.swift
Labels: Reimagine Sharing

#2135 Fix #2132: Fix iPad Crash when presenting popover from share button
  podcasts.xcodeproj/project.pbxproj
  podcasts/Sharing/ShareButton.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/SharingFooterView.swift
Labels: [Project] Reimagine Sharing

#2133 Revert change stats
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
Labels: [Type] Bug

#2136 7.72 Release: Merge changes from 7.72.0.2 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
  podcasts/EpisodeDetailViewController.swift
  podcasts/MultiSelectHelper.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/SharingHelper+swipeButton.swift
  podcasts/SharingHelper.swift
  podcasts/ShelfActionsViewController+Table.swift
  podcasts/ShelfActionsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/TranscriptShelfButton.swift
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#2137 7.72 Release: Merge changes from 7.72.0.3 into `trunk`
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts/Sharing/ShareButton.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/SharingFooterView.swift
Labels: Releases

#2147 Switch 7.72 release build to Xcode 16 Beta 6
  .buildkite/shared-pipeline-vars
Labels: [Type] Tooling

#2142 Fix normal color on menu shelf actions
  podcasts/ShelfActionsViewController+Table.swift
Labels: [Type] Bug

#2145 Skip bug: check if player is ready to play
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/DefaultPlayer.swift
  podcasts/EffectsPlayer.swift
  podcasts/GoogleCastManager.swift
  podcasts/GoogleCastPlayer.swift
  podcasts/PlaybackManager.swift
  podcasts/PlaybackProtocol.swift
Labels: [Type] Bug

#2120 Referrals: Send pass UI
  podcasts.xcodeproj/project.pbxproj
  podcasts/ProfileViewController.swift
  podcasts/Referrals/ReferralCardView.swift
  podcasts/Referrals/ReferralSendPassVC.swift
  podcasts/Referrals/ReferralSendPassView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Referrals

#2146 Fix #2139: Add export caching + improved file names
  podcasts.xcodeproj/project.pbxproj
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/String+SanitizedFileName.swift
Labels: [Project] Reimagine Sharing

#2143 Referrals: Add animated background gradient view to card.
  podcasts.xcodeproj/project.pbxproj
  podcasts/Referrals/ReferralCardAnimatedGradientView.swift
  podcasts/Referrals/ReferralCardView.swift
Labels: [Project] Referrals

#2140 Reimagine Sharing: Tweaks to exported asset sizing + colors
  podcasts/Sharing/AnimatedShareImageView.swift
  podcasts/Sharing/Clip/VideoExporter.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/View+CVPixelBuffer.swift
Labels: [Project] Reimagine Sharing

#2148 7.72 Release: Merge changes from 7.72.0.4 into `trunk`
  .buildkite/shared-pipeline-vars
  config/Version.xcconfig
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2152 Fix type in Kids Profile banner
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Bug

#2153 Referrals: User has no passes
  podcasts/ProfileViewController.swift
  podcasts/Referrals/ReferralSendPassVC.swift
  podcasts/Referrals/ReferralSendPassView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Referrals

#2157 Reimagine Sharing: iOS 15 support
  podcasts/Sharing/Clip/VideoExporter.swift
  podcasts/Sharing/ShareButton.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/SharingView.swift
  podcasts/View+CVPixelBuffer.swift
Labels: [Area] iOS 15, [Project] Reimagine Sharing

#2156 Reimagine Sharing: Fix trim handle lag on long episodes
  Modules/Utils/Sources/PocketCastsUtils/Formatting/TimeFormatter.swift
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/Clip/ScrollableScrollView.swift
Labels: [Project] Reimagine Sharing, Performance

#2159 Revert Xcode version to 15.4
  .buildkite/shared-pipeline-vars
Labels: [Type] Tooling

#2160 7.72 Release: Merge changes from 7.72.0.6 into `trunk`
  Modules/Utils/Sources/PocketCastsUtils/Formatting/TimeFormatter.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/Clip/ScrollableScrollView.swift
  podcasts/Sharing/Clip/VideoExporter.swift
  podcasts/Sharing/ShareButton.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/SharingView.swift
  podcasts/View+CVPixelBuffer.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2162 Referrals: Switch to 2 months and make display of offer duration more flexible
  podcasts.xcodeproj/project.pbxproj
  podcasts/ProfileViewController.swift
  podcasts/Referrals/Banner/ReferralsClaimBannerTableCell.swift
  podcasts/Referrals/Banner/ReferralsClaimBannerView.swift
  podcasts/Referrals/ReferralCardAnimatedGradientView.swift
  podcasts/Referrals/ReferralCardView.swift
  podcasts/Referrals/ReferralSendPassVC.swift
  podcasts/Referrals/ReferralSendPassView.swift
  podcasts/Referrals/ReferralsClaimPass.swift
  podcasts/Referrals/ReferralsOfferInfo.swift
  podcasts/Strings+Generated.swift
  podcasts/TipView.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Referrals

#2168 Transcripts: Fix sending of transcript show event when transcript are not visible
  podcasts/PlayerContainerViewController.swift
  podcasts/TranscriptViewController.swift
Labels: [Type] Bug, [Project] Transcripts

#2163 Reimagine Sharing: Accessibility
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/Clip/TrimSelectionView.swift
  podcasts/Sharing/SharingFooterView.swift
  podcasts/Sharing/SharingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Reimagine Sharing

#2169 7.72 Release: Merge changes from 7.72.0.8 into `trunk`
  config/Version.xcconfig
  podcasts/PlayerContainerViewController.swift
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/Clip/TrimSelectionView.swift
  podcasts/Sharing/SharingFooterView.swift
  podcasts/Sharing/SharingView.swift
  podcasts/Strings+Generated.swift
  podcasts/TranscriptViewController.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2170 7.73 Release: Merge changes from 7.73.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2167 Fix #2165: Exclude link from AirDrop export
  podcasts.xcodeproj/project.pbxproj
  podcasts/Sharing/ActivityItemSourceItem.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/SharingModal.swift
Labels: [Type] Bug, [Project] Reimagine Sharing

#2171 Update Changelog
  CHANGELOG.md
Labels: Changelog

#2172 Fix: Episode sort setting on WatchOS
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Pocket Casts Watch App/PodcastEpisodeListViewModel.swift
Labels: [Type] Bug, [Area] watchOS

#2164 Referrals :Update to unlimited passes
  podcasts/ProfileViewController.swift
  podcasts/Referrals/ReferralSendPassView.swift
  podcasts/Strings+Generated.swift
  podcasts/TipView.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Referrals

#2166 Referrals: send pass share
  podcasts/ProfileViewController.swift
  podcasts/Referrals/ReferralSendPassVC.swift
  podcasts/Referrals/ReferralSendPassView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Referrals

#2177 Update Xcode CI image from `xcode-15.4` to `xcode-16.0`
  .buildkite/shared-pipeline-vars
Labels: Xcode Update

#2183 [Tooling] Use final Xcode 16.0 image version
  .buildkite/shared-pipeline-vars
Labels: [Type] Tooling

#2175 Show all sorting options for episode
  CHANGELOG.md
  podcasts/EpisodeListSearchController.swift
Labels: [Type] Feature

#2190 [Tooling] Use final Xcode 16.0 image version (#2183)
  .buildkite/shared-pipeline-vars
Labels: [Type] Tooling, continuous integration

#2192 Transcripts/decode html entities
  CHANGELOG.md
  PocketCastsTests/Tests/Player/Transcripts/ComposeFilterTests.swift
  podcasts/TranscriptFilter.swift
Labels: [Type] Bug, [Project] Transcripts

#2178 Referrals: deep link for claiming guest pass
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate+SiriShortcuts.swift
  podcasts/Constants.swift
  podcasts/MainTabBarController.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
  podcasts/ProfileViewController.swift
  podcasts/Referrals/Banner/ReferralsClaimBannerView.swift
  podcasts/Referrals/ReferralsClaimPass.swift
  podcasts/Referrals/ReferralsCoordinator.swift
  podcasts/Referrals/ReferralsMessageView.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  podcasts/podcastsDebug.entitlements
Labels: [Project] Referrals

#2186 Update the now playing info when player is not seeking
  CHANGELOG.md
  podcasts/PlaybackManager.swift
Labels: [Type] Bug, playback

#2195 [Listening History] Display Search bar
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/ListeningHistoryViewController.swift
  podcasts/PCSearchBarController.swift
Labels: [Project] Listening History Search

#2197 Fix: #2141: Skip Back issue when skipping from watch
  CHANGELOG.md
  podcasts/PlaybackManager.swift
  podcasts/WatchManager.swift
Labels: [Type] Bug

#2193 Transcripts fix support for alternative format types
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/TranscriptFormat.swift
  podcasts/TranscriptModel.swift
Labels: [Project] Transcripts

#2194 Update proto api calls
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/files.pb.swift
Labels: Releases

#2202 7.73 Release: Merge changes from 7.73.0.3 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/PlaybackManager.swift
  podcasts/TranscriptFormat.swift
  podcasts/TranscriptModel.swift
  podcasts/WatchManager.swift
  podcasts/ja.lproj/Localizable.strings
Labels: Releases

#2201 [Listening History] Add local search
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/String+Escape.swift
  podcasts/EpisodeTableHelper.swift
  podcasts/EpisodesDataManager.swift
  podcasts/ListeningHistoryViewController.swift
  podcasts/ListeningHistoryViewController.xib
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Listening History Search

#2208 [Listening History] Add analytics
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/ListeningHistoryViewController.swift
Labels: [Project] Listening History Search

#2209 7.73 Release: Merge changes from 7.73.0.4 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts/DiscoverCollectionHeader.xib
  podcasts/ExpandedCollectionViewController+CollectionView.swift
  podcasts/LargeListCell.xib
  podcasts/UIView+Nib.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
Labels: Releases

#2205 Referrals: Integrate api call for get redeem code
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ReferralGetCodeTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+Referrals.swift
  podcasts/ProfileViewController.swift
  podcasts/Referrals/ReferralCardAnimatedGradientView.swift
  podcasts/Referrals/ReferralCardView.swift
  podcasts/Referrals/ReferralSendPassVC.swift
  podcasts/Referrals/ReferralSendPassView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Referrals

#2220 Transcripts: Track the transcript type and if javascript is detected in it.
  podcasts/TranscriptModel.swift
  podcasts/TranscriptViewController.swift
Labels: [Project] Transcripts

#2222 7.73 Release: Merge changes from 7.73.0.5 into `trunk`
  config/Version.xcconfig
  podcasts/TranscriptModel.swift
  podcasts/TranscriptViewController.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2221 [Tooling] Update fastlane
  Gemfile.lock
Labels: [Type] Tooling

#2224 Remove Xcode 15.4 check
  fastlane/Fastfile
Labels: continuous integration

#2225 7.73 Release: Merge changes from 7.73.0.6 into `trunk`
  Gemfile.lock
  config/Version.xcconfig
  fastlane/Fastfile
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
Labels: Releases

#2218 Add search functionality to DiscoverCollectionViewController
  podcasts.xcodeproj/project.pbxproj
  podcasts/DiscoverCollectionViewController+Search.swift
  podcasts/DiscoverCollectionViewController.swift
Labels: [Project] Discover Collection View

#2215 [Tooling] Refactor code freeze lane and Fastfile cleanup
  fastlane/Fastfile
Labels: [Type] Tooling

#2216 [Tooling] Reorder lanes in `Fastfile`
  fastlane/Fastfile
Labels: [Type] Tooling

#2217 [Tooling] Migrate all lanes to keyword-params syntax
  fastlane/Fastfile
Labels: [Type] Tooling

#2226 Discover Collection View: Add collection view and view controller cells
  podcasts.xcodeproj/project.pbxproj
  podcasts/Array+DiscoverItem.swift
  podcasts/DiscoverCellType.swift
  podcasts/DiscoverCollectionViewController+DiscoverDelegate.swift
  podcasts/DiscoverCollectionViewController+Search.swift
  podcasts/DiscoverCollectionViewController.swift
  podcasts/FeaturedSummaryViewController.swift
  podcasts/FeaturedSummaryViewController.xib
  podcasts/LargeListCell.xib
  podcasts/LargeListSummaryViewController.xib
  podcasts/SingleEpisodeViewController.xib
  podcasts/UIViewControllerContentConfiguration.swift
Labels: [Project] Discover Collection View

#2227 Merge release/7.74 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases
