Repository Automattic/pocket-casts-ios, pull requests merged in 2024-08, with the labels that each got.

#1954 Reimagine Sharing: Confine playhead to Trim range
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/Clip/PlayheadView.swift
  podcasts/Sharing/Clip/TrimHandle.swift
  podcasts/Sharing/Clip/TrimSelectionView.swift
Labels: Reimagine Sharing

#1974 Transcripts: prevent search from appearing when selecting text
  podcasts/TranscriptsViewController.swift
Labels: Transcripts

#1977 Fix: handling `/get/?args`
  CHANGELOG.md
  podcasts/AppDelelgate+SiriShortcuts.swift
Labels: Bug

#1975 [Kids Profile] Add UserDefaults logic to hide banner
  podcasts/Constants.swift
  podcasts/Kids Profile/KidsProfileBannerViewModel.swift
  podcasts/ProfileViewController.swift
  podcasts/Settings.swift
Labels: Kids profile

#1978 7.69 Release: Merge changes from 7.69.0.4 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/AppDelelgate+SiriShortcuts.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1979 7.69 Release: Merge changes from 7.69.0.5 into `trunk`
  config/Version.xcconfig
Labels: Releases

#1973 Transcripts small UI fixes
  podcasts/TranscriptsViewController.swift
Labels: Transcripts

#1984 7.70 Release: Merge changes from 7.70.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1982 Transcripts: search logic
  Modules/Utils/Sources/PocketCastsUtils/Extensions/UI/UITextView+scrollToRange.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/UI/UIView+distanceToBottom.swift
  Modules/Utils/Sources/PocketCastsUtils/General/KPMSearch.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/General/KMPSearchTests.swift
  podcasts/Strings+Generated.swift
  podcasts/TranscriptSearchAccessoryView.swift
  podcasts/TranscriptsViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: Transcripts

#1985 Skip Back: try to fix audio moving forward, not backwards
  CHANGELOG.md
  podcasts/EffectsPlayer.swift
Labels: Bug, playback

#1991 [Kids Profile] Send Feedback API implementation
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ApiBaseTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/SupportFeedbackTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+SupportFeedbackRequest.swift
  podcasts/Kids Profile/KidsProfileBannerView.swift
  podcasts/Kids Profile/KidsProfileSheetViewModel.swift
  podcasts/Kids Profile/KidsProfileSubmitScreen.swift
Labels: Kids profile

#1993 7.70 Release: Merge changes from 7.70.0.1 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/EffectsPlayer.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1992 [Give Ratings] Add What's New
  podcasts.xcodeproj/project.pbxproj
  podcasts/Strings+Generated.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/GiveRatingsWhatsNewHeader.swift
  podcasts/WhatsNew.xcassets/whatsnew_star.imageset/Contents.json
  podcasts/WhatsNew.xcassets/whatsnew_star.imageset/star 40x40.svg
  podcasts/en.lproj/Localizable.strings
Labels: Give Rating

#1995 Update Extra Playback Actions copy
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: settings

#1996 7.70 Release: Merge changes from 7.70.0.2 into `trunk`
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts.xcodeproj/project.pbxproj
  podcasts/Strings+Generated.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/GiveRatingsWhatsNewHeader.swift
  podcasts/WhatsNew.xcassets/whatsnew_star.imageset/Contents.json
  podcasts/WhatsNew.xcassets/whatsnew_star.imageset/star 40x40.svg
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#1994 Transcripts: Tracks
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/TranscriptViewController.swift
Labels: analytics, Transcripts

#2002 [Kids Profile] Add generic error for feedback toast
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+SupportFeedbackRequest.swift
  podcasts/Kids Profile/KidsProfileSheetViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Kids profile

#1947 Reimagine Sharing: Clip playback
  podcasts.xcodeproj/project.pbxproj
  podcasts/CMTimeScale+Common.swift
  podcasts/Sharing/Clip/ClipPlaybackManager.swift
  podcasts/Sharing/Clip/MediaTrimBar.swift
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/Clip/PlayButton.swift
  podcasts/Sharing/Clip/PlayheadView.swift
  podcasts/Sharing/Clip/TrimHandle.swift
  podcasts/Sharing/Clip/TrimSelectionView.swift
  podcasts/Sharing/SharingView.swift
Labels: Reimagine Sharing

#2003 [Tooling] Update Ruby Dependencies
  Gemfile.lock
Labels: tooling

#2005 Transcripts: display "0" when there are no results
  podcasts/TranscriptViewController.swift
Labels: Transcripts

#1989 Disable SPM caching in CI
  .buildkite/commands/build.sh
  .buildkite/commands/prototype-build.sh
  .buildkite/commands/prototype-upload.sh
  .buildkite/commands/release-build.sh
  .buildkite/commands/shared_setup.sh
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  podcasts.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: tooling

#2004 Transcripts: update shelf icon
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/CommonImages.xcassets/transcript.imageset/Contents.json
  podcasts/CommonImages.xcassets/transcript.imageset/transcript.svg
  podcasts/Enumerations.swift
  podcasts/Settings.swift
  podcasts/ShelfActionsViewController+Table.swift
  podcasts/ShelfActionsViewController.swift
  podcasts/TranscriptShelfButton.swift
Labels: Transcripts

#2009 Transcripts: Optimise formatting of attributed string
  podcasts/TranscriptViewController.swift
Labels: Transcripts

#2000 Transcripts fix crash on empty search
  podcasts/TranscriptSearchAccessoryView.swift
  podcasts/TranscriptViewController.swift
Labels: Transcripts

#2008 Transcripts: remove empty lines
  PocketCastsTests/Tests/Player/Transcripts/sample.vtt
  podcasts/TranscriptFormat.swift
  podcasts/TranscriptModel.swift
Labels: Transcripts

#2011 [Give Rating] Copy update
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Give Rating

#2007 Transcripts - Error and loading states
  podcasts.xcodeproj/project.pbxproj
  podcasts/CommonImages.xcassets/yield_scaled.imageset/Contents.json
  podcasts/CommonImages.xcassets/yield_scaled.imageset/yield.svg
  podcasts/Strings+Generated.swift
  podcasts/TranscriptErrorView.swift
  podcasts/TranscriptManager.swift
  podcasts/TranscriptViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: Transcripts

#2013 When searchTerm is emptied out cancel any pending search
  podcasts/Debounce.swift
  podcasts/TranscriptViewController.swift
Labels: Bug, Transcripts

#2015 Reimagine Sharing: Add clip time labels
  podcasts/Sharing/SharingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Reimagine Sharing

#2020 Update Paywall Landing view title copy
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Localization

#2021 7.70 Release: Merge changes from 7.70.0.3 into `trunk`
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2017 Update bookmarks icon in settings
  podcasts/Bookmarks.xcassets/bookmarks-profile.imageset/Contents.json
  podcasts/Bookmarks.xcassets/bookmarks-profile.imageset/bookmark.svg
  podcasts/ProfileViewController.swift
Labels: Bookmarks

#2014 Transcripts: block scroll when dismissing keyboard
  podcasts/TranscriptViewController.swift
Labels: Bug, Transcripts

#2016 Add logging to PlaybackManager
  podcasts/PlaybackManager.swift
Labels: Logging

#2012 Transcripts: speaker info
  PocketCastsTests/Tests/Player/Transcripts/TranscriptModelFilterTests.swift
  podcasts/TranscriptFormat.swift
  podcasts/TranscriptModel.swift
  podcasts/TranscriptViewController.swift
Labels: Transcripts

#2022 Transcripts: Fallback to other transcript format if main one fails
  PocketCastsTests/Tests/Playback/Chapters/ChapterManagerTests.swift
  PocketCastsTests/Tests/Player/Transcripts/TranscriptManagerTests.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinating.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinator.swift
  podcasts/ShowNotesUpdater.swift
  podcasts/TranscriptManager.swift
  podcasts/TranscriptsDataRetriever.swift
Labels: Transcripts, [Type] Feature - Medium

#2026 Reimagine Sharing: Add sharing to Instagram Stories
  .configure
  .configure-files/pocket_casts_credentials.json.enc
  podcasts/Credentials/ApiCredentials.tpl
  podcasts/Sharing.xcassets/instagram.imageset/Contents.json
  podcasts/Sharing.xcassets/instagram.imageset/instagram.pdf
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/podcasts-Info.plist
Labels: Reimagine Sharing

#1969 Implement ExPlat
  PocketCastsTests/Tests/ABTest/ABTestProviderTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/ABTest/ABTest.swift
  podcasts/ABTest/ABTestProvider.swift
  podcasts/ABTest/ABTestProviding.swift
  podcasts/Analytics/Adapters/Tracks/TracksAdapter.swift
Labels: Paywall Experiments, A/B Test

#2034 [Give Rating] Make the rating view tappable
  podcasts/Ratings/StarRatingView.swift
Labels: Give Rating

#2018 Reimagine Sharing: Export video
  podcasts.xcodeproj/project.pbxproj
  podcasts/Optional+ThrowOnNil.swift
  podcasts/Sharing/AnimatedShareImageView.swift
  podcasts/Sharing/Clip/VideoExporter.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/UnsafeTransfer.swift
  podcasts/UnsafeWait.swift
  podcasts/View+CVPixelBuffer.swift
Labels: Reimagine Sharing

#2036 7.70 Release: Merge changes from 7.70.0.4 into `trunk`
  config/Version.xcconfig
  podcasts/Ratings/StarRatingView.swift
  podcasts/ca.lproj/InfoPlist.strings
  podcasts/ca.lproj/Intents.strings
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2042 Fix missing angle argument on ShareImageView
  podcasts/Sharing/ShareDestination.swift
Labels: Bug

#2040 Transcripts: handle diacritics when searching
  Modules/Utils/Sources/PocketCastsUtils/General/KPMSearch.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/General/KMPSearchTests.swift
  podcasts/TranscriptViewController.swift
Labels: Transcripts

#2038 Cancel button
  CHANGELOG.md
  podcasts/OnlineSupportController.swift
Labels: Bug

#2046 7.70 Release: Merge changes from 7.70.0.5 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/OnlineSupportController.swift
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
Labels: Releases

#2050 [Tooling] Apply required CI checks too when setting branch protection settings on release branch
  fastlane/Fastfile
Labels: tooling

#2045 Reimagine Sharing: Static waveform lines + Preview scaling
  podcasts/Sharing/AudioWaveformView.swift
  podcasts/Sharing/SharingView.swift
Labels: Reimagine Sharing

#2037 Fix auto play when skipping last
  CHANGELOG.md
  podcasts/PlaybackManager.swift
Labels: Bug

#2041 Skip Back: do not allow skipping forward when skipping back
  CHANGELOG.md
  podcasts/PlaybackManager.swift
Labels: Bug

#2048 [Give Ratings] Reload ratings ignoring cache
  Modules/Server/Sources/PocketCastsServer/Public/Ratings/PodcastRatingTask.swift
  podcasts/PodcastViewController.swift
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/RatePodcastView.swift
  podcasts/Ratings/RatePodcastViewModel.swift
  podcasts/Ratings/StarRatingView.swift
Labels: Feature, Give Rating

#2044 Reimagine Sharing: Export audio clips
  .configure
  podcasts.xcodeproj/project.pbxproj
  podcasts/CommonImages.xcassets/music.imageset/Contents.json
  podcasts/CommonImages.xcassets/music.imageset/music.pdf
  podcasts/Sharing/Clip/AudioClipExporter.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
Labels: Reimagine Sharing

#2043 Widgets: track install/uninstall
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/AppLifecyleAnalytics.swift
  podcasts/Analytics/WidgetAnalytics.swift
Labels: Analytics, Widgets

#2052 [Tooling] Revert branch protection change (#2050)
  fastlane/Fastfile
Labels: tooling

#2051 7.70 Release: Merge changes from 7.70.0.6 into `trunk`
  Modules/Server/Sources/PocketCastsServer/Public/Ratings/PodcastRatingTask.swift
  config/Version.xcconfig
  podcasts/PodcastViewController.swift
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/RatePodcastView.swift
  podcasts/Ratings/RatePodcastViewModel.swift
  podcasts/Ratings/StarRatingView.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2053 Reimagine Sharing: Improve Task cancellation in VideoExporter
  podcasts/Sharing/Clip/VideoExporter.swift
Labels: Reimagine Sharing

#2055 7.70 Release: Merge changes from 7.70.0.7 into `trunk`
  config/Version.xcconfig
Labels: Releases

#2058 Reimagine Sharing: Tweak share screen
  podcasts/Sharing/AudioWaveformView.swift
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Reimagine Sharing

#2057 Reimagine Sharing: Add video sharing to Instagram Stories
  podcasts.xcodeproj/project.pbxproj
  podcasts/CGSize+FittingSize.swift
  podcasts/Sharing/AVAsset+Crop.swift
  podcasts/Sharing/AnimatedShareImageView.swift
  podcasts/Sharing/Clip/VideoExporter.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingFooterView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Reimagine Sharing

#2062 [Paywall Experiments] Create new Paywall container
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/PlusPaywallContainer.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/PlusPaywallFeaturesCarousell.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/PlusPaywallSubscriptions.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Feature, Paywall Experiments

#2064 Transcript: fix content jumping after tapping "Done"
  podcasts/TranscriptViewController.swift
Labels: Bug, Transcripts

#2065 [Tooling][CI] Modernize Buildkite pipelines syntax to use shared values
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  .buildkite/shared-pipeline-vars
  README.md
Labels: tooling

#2070 [Bug Fix] Fix cancel subscription URL
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
Labels: Bug

#2071 Xcode 16: add flag to allow building the app to Xcode 16 and Xcode 15
  Pocket Casts Watch App/NowPlayingControls.swift
Labels: Xcode Update

#2075 CI run for #2072
  CHANGELOG.md
  podcasts/PodcastListViewController.swift
Labels: Bug, Enhancement

#2067 Xcode 16: fix SIGABRT crash
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinator.swift
  podcasts/PodcastIndexChapterDataRetriever.swift
Labels: Bug, crash

#2054 watchOS 11: make play/pause button a primary action
  Pocket Casts Watch App/NowPlayingControls.swift
Labels: watchOS, watchOS 11

#2074 Ensure that the profile header view always returns a minimum size that is visible
  CHANGELOG.md
  podcasts/Profile - SwiftUI/Profile/ProfileHeaderView.swift
Labels: Bug

#2079 Update: Google Cast
  Podfile
  Podfile.lock
Labels: Dependencies

#2080 [Paywall Experiments] Features Carousel variant
  podcasts.xcodeproj/project.pbxproj
  podcasts/Onboarding/Plus/PlusPurchaseModal.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/PlusPaywallContainer.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/PlusPaywallFeatureCard.swift
  podcasts/Onboarding/Plus/UpgradeExperiment/PlusPaywallFeaturesCarousell.swift
  podcasts/Strings+Generated.swift
  podcasts/Subscription.xcassets/Paywall Experiment/Contents.json
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_bookmarks.imageset/Bookmarks.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_bookmarks.imageset/Bookmarks@2x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_bookmarks.imageset/Bookmarks@3x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_bookmarks.imageset/Contents.json
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_desktop.imageset/Contents.json
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_desktop.imageset/Desktop.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_desktop.imageset/Desktop@2x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_desktop.imageset/Desktop@3x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_extra_themes.imageset/Contents.json
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_extra_themes.imageset/Themes.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_extra_themes.imageset/Themes@2x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_extra_themes.imageset/Themes@3x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_folders.imageset/Contents.json
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_folders.imageset/Folders-new.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_folders.imageset/Folders-new@2x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_folders.imageset/Folders-new@3x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_slumber_studio.imageset/Contents.json
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_slumber_studio.imageset/Slumber.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_slumber_studio.imageset/Slumber@2x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_slumber_studio.imageset/Slumber@3x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_storage.imageset/Contents.json
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_storage.imageset/Storage.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_storage.imageset/Storage@2x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_storage.imageset/Storage@3x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_wear_os.imageset/Contents.json
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_wear_os.imageset/Watch.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_wear_os.imageset/Watch@2x.png
  podcasts/Subscription.xcassets/Paywall Experiment/plus_feature_card_wear_os.imageset/Watch@3x.png
  podcasts/en.lproj/Localizable.strings
Labels: Feature, Paywall Experiments

#2082 Referrals: Entry point
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/ProfileViewController.swift
  podcasts/Referrals.xcassets/Contents.json
  podcasts/Referrals.xcassets/gift.imageset/Contents.json
  podcasts/Referrals.xcassets/gift.imageset/gift.svg
Labels: Referrals

#2088 Reimagine Sharing: Trim Handle offsets
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/Clip/PlayheadView.swift
  podcasts/Sharing/Clip/ScrollableScrollView.swift
  podcasts/Sharing/Clip/TrimHandle.swift
  podcasts/Sharing/Clip/TrimSelectionView.swift
  podcasts/Sharing/SharingView.swift
Labels: Reimagine Sharing

#2093 Transcripts: Reset scroll position when changing transcript episode
  podcasts/TranscriptViewController.swift
Labels: Bug, Transcripts

#1876 Add new Medium "Now Playing" widget
  CHANGELOG.md
  WidgetExtension/Common/ArtworkViews.swift
  WidgetExtension/Common/CommonWidgetHelper.swift
  WidgetExtension/Now Playing/NowPlayingEntryView.swift
  WidgetExtension/Now Playing/NowPlayingWidget.swift
  WidgetExtension/Now Playing/NowPlayingWidgetBold.swift
  WidgetExtension/Up Next/UpNextLargeWidgetView.swift
  WidgetExtension/Up Next/UpNextMediumWidgetView.swift
  WidgetExtension/Up Next/UpNextWidgetEntryView.swift
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts Staging.xcscheme
Labels: Widgets

#2090 [Give Rating] Add new source for rate tapping event
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/StarRatingView.swift
Labels: Analytics

#2095 Reimagine Sharing: Add analytics for sharing screen
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Bookmarks/Episode/BookmarkEpisodeListController.swift
  podcasts/EpisodeDetailViewController.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/PodcastViewController.swift
  podcasts/Sharing/Clip/MediaTrimBar.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/SharingFooterView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/SharingHelper.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Reimagine Sharing

#2097 7.71 Release: Merge changes from 7.71.0.3 into `trunk`
  config/Version.xcconfig
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/StarRatingView.swift
  podcasts/TranscriptViewController.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2101 Update IMAGE ID
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: [Type] Tooling, Xcode Update

#2102 Transcripts: enable
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Transcripts

#2099 Reimagine Sharing: Add logo to all clip assets
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingModal.swift
Labels: Reimagine Sharing

#2103 7.71 Release: Merge changes from 7.71.0.4 into `trunk`
  config/Version.xcconfig
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
Labels: Releases

#2098 Widgets: track interaction
  WidgetExtension/Now Playing/NowPlayingEntryView.swift
  WidgetExtension/Now Playing/NowPlayingLockScreenWidget.swift
  WidgetExtension/Up Next/HungryForMoreView.swift
  WidgetExtension/Up Next/UpNextLockScreenWidget.swift
  WidgetExtension/Up Next/UpNextWidgetEntryView.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/AppPlayEpisodeIntentExtension.swift
Labels: Enhancement

#2107 Revert image id for release
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: Releases

#2106 Stats: add checks to prevent decreasing
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/StatsManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
Labels: [Type] Bug

#2109 Stats: sync from server if local stats are behind
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/RetrieveStatsTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  Modules/Server/Sources/PocketCastsServer/Public/StatsManager.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/StatsViewController.swift
Labels: [Type] Enhancement, Stats

#2110 7.71 Release: Merge changes from 7.71.0.5 into `trunk`
  config/Version.xcconfig
  podcasts/de.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2105 Discover Collection View: Feature Flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/DiscoverCollectionViewController.swift
  podcasts/MainTabBarController.swift
Labels: [Project] Discover Collection View
