Repository Automattic/pocket-casts-ios, pull requests merged in 2024-05, with the labels that each got.

#1684 Performance: Bulk save improvements
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/MainServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshOperation.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
Labels: Performance

#1683 Performance: Download task index
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
Labels: Performance

#1681 Performance: add `addedDate` INDEX
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
Labels: Performance

#1680 Performance: move calls to be async allowing a faster startup time
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/AppDelegate.swift
  podcasts/ChapterManager.swift
  podcasts/MainTabBarController.swift
Labels: Performance

#1679 Performance: remove bookmarks announcement
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/AppDelegate.swift
  podcasts/ChapterManager.swift
  podcasts/MainTabBarController.swift
  podcasts/Whats New/Announcements.swift
Labels: Performance

#1678 Performance: add `downloadTaskId` partial INDEX
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/AppDelegate.swift
  podcasts/ChapterManager.swift
  podcasts/MainTabBarController.swift
  podcasts/Whats New/Announcements.swift
Labels: enhancement, Performance

#1677 Performance: add `archived` INDEX to speed up filters
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/AppDelegate.swift
  podcasts/ChapterManager.swift
  podcasts/MainTabBarController.swift
  podcasts/Whats New/Announcements.swift
Labels: Performance

#1685 7.63 Release: Merge changes from 7.63.0.1 into `trunk`
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode+fromDatabase.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/MetadataTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/MainServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshOperation.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/AppDelegate+Defaults.swift
  podcasts/AppDelegate.swift
  podcasts/ChapterManager.swift
  podcasts/EffectsPlayer.swift
  podcasts/EpisodeCell.swift
  podcasts/MainTabBarController.swift
  podcasts/PodcastImageView.swift
  podcasts/ShowInfoCoordinator.swift
  podcasts/ShowNotesPlayerItemViewController.swift
  podcasts/Whats New/Announcements.swift
  podcasts/ca.lproj/Localizable.strings
Labels: Releases

#1653 Fixes #1389: Fall back to root VC if no `topMostPresented` is found
  podcasts/SceneHelper.swift
Labels: Bug

#1691 Revert 7.63 to 7.60.1
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/Login/GoogleSocialLogin.swift
Labels: Performance

#1693 Performance: add back improvements on top of 7.63
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseIndexHelper.swift
  podcasts/AppDelegate.swift
  podcasts/MainTabBarController.swift
  podcasts/Settings.swift
Labels: Performance

#1694 Performance: Settings Query
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDatabase.swift
  PocketCastsTests/UnitTests.xctestplan
Labels: Performance

#1696 Performance: Add bulkSave to episode refresh
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshOperation.swift
Labels: Performance

#1697 Performance: Podcast cache
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseIndexHelper.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/AutoAddCandidatesDataManagerTests.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/DataManager+TestDatabase.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/PodcastDataManagerTests.swift
  podcasts/Settings.swift
Labels: Performance

#1702 Performance: remove bookmark check
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
Labels: Performance

#1700 Performance: move filter queries to background
  podcasts/PlaylistViewController.swift
  podcasts/PlaylistsViewController.swift
Labels: Performance

#1701 Performance: check for pending downloads in the background
  podcasts/AppDelegate.swift
Labels: Performance

#1705 Performance: move DROP operations outside of migrations
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseIndexHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate.swift
  podcasts/MainTabBarController+Alert.swift
  podcasts/MainTabBarController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Performance

#1712 Filter discover items without categories
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/DiscoverViewController.swift
Labels: Categories Redesign

#1713 Revert "Remove unnecessary WHERE from query"
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
Labels: Bug

#1703 Performance: Background SiriShortcutsManager
  podcasts/AppDelegate.swift
Labels: Performance

#1715 Performance: `VACUUM` the database
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts/MainTabBarController+Alert.swift
  podcasts/MainTabBarController.swift
  podcasts/Settings.swift
Labels: Performance

#1710 Only propagate episode changes notifications if the file size actually changed
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/MetadataTask.swift
Labels: Performance

#1718 7.62.1 Release: Merge changes from 7.62.1.1 into `trunk`
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/DiscoverViewController.swift
  podcasts/SinglePodcastViewController.swift
Labels: Releases

#1720 Categories: Re-merge pull requests for Categories Redesign
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/UI/View+Modify.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AnalyticsHelper.swift
  podcasts/Categories/CategoriesModalPicker.swift
  podcasts/Categories/CategoriesSelectorView.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
  podcasts/Categories/CategoryButtonStyle.swift
  podcasts/CategoryPodcastsViewController.swift
  podcasts/CategorySummaryViewController.swift
  podcasts/DeveloperMenu.swift
  podcasts/DiscoverSummaryProtocol.swift
  podcasts/DiscoverViewController+CategoryRedesign.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/DiscoverViewController.swift
  podcasts/LargeListSummaryViewController.swift
  podcasts/LargeListSummaryViewController.xib
  podcasts/PodcastViewController.swift
  podcasts/SinglePodcastViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/ThemeableTable.swift
  podcasts/en.lproj/Localizable.strings
Labels: Categories Redesign

#1721 Categories: Update tracks events for Categories redesign
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Categories/CategoriesModalPicker.swift
  podcasts/Categories/CategoriesSelectorView.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
  podcasts/CategorySummaryViewController.swift
  podcasts/CollectionSummaryViewController.swift
  podcasts/CountrySummaryViewController.swift
  podcasts/DiscoverSummaryProtocol.swift
  podcasts/DiscoverViewController+CategoryRedesign.swift
  podcasts/DiscoverViewController.swift
  podcasts/FeaturedSummaryViewController.swift
  podcasts/LargeListSummaryViewController.swift
  podcasts/NetworkSummaryViewController.swift
  podcasts/SingleEpisodeViewController.swift
  podcasts/SinglePodcastViewController.swift
  podcasts/SmallPagedListSummaryViewController.swift
Labels: Categories Redesign

#1708 Improve folders performance
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts/FolderGridCell.swift
  podcasts/FolderListCell.swift
  podcasts/FolderPreviewView.swift
  podcasts/HomeGridListItem.swift
  podcasts/PodcastImageView.swift
  podcasts/PodcastManager+Delete.swift
  podcasts/PodcastSearchCell.swift
Labels: Performance

#1723 Standard Tags: add it back on 7.63
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  Modules/Server/Sources/PocketCastsServer/Public/Cache/CacheServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Cache/EpisodeInfoHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  PocketCastsTests/Tests/Playback/Chapters/ChapterManagerTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/ChapterManager.swift
  podcasts/EffectsPlayer.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinating.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinator.swift
  podcasts/EpisodeArtwork.swift
  podcasts/EpisodeDetailViewController+ShowNotes.swift
  podcasts/PodcastChapterParser.swift
  podcasts/PodcastIndexChapterDataRetriever.swift
  podcasts/ShowNotesPlayerItemViewController.swift
  podcasts/ShowNotesUpdater.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Standard Tags

#1724 Sleep Timer: add back automatically restart if playback is resumed within 5 minutes to 7.63
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Constants.swift
  podcasts/PlaybackManager.swift
  podcasts/Settings.swift
  podcasts/SleepTimerManager.swift
  podcasts/SleepTimerViewController.swift
Labels: Sleep Timer

#1728 Vacuum on clean up start and end
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
Labels: Performance

#1730 Update `CHANGELOG` and copies on `trunk`
  CHANGELOG.md
  fastlane/Frozen.strings
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1732 Re-add: #1607 and #1679
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/DeselectChaptersAnnouncementViewModel.swift
Labels: Deselecting Chapters

#1727 Use S3 for fastlane match
  .configure
  Gemfile.lock
  fastlane/Fastfile
Labels: tooling, continuous integration

#1739 Re add: -5 fix links that share position
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/AppDelegate.swift
  podcasts/EpisodeDetailViewController+Actions.swift
  podcasts/EpisodeDetailViewController.swift
  podcasts/EpisodeLoadingController.swift
  podcasts/MainTabBarController.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
Labels: Bug, clip sharing

#1729 Re add/watch main interface refactor
  Pocket Casts Watch App/Base.lproj/Interface.storyboard
  Pocket Casts Watch App/DownloadListViewModel.swift
  Pocket Casts Watch App/FilesListView.swift
  Pocket Casts Watch App/InterfaceController.swift
  Pocket Casts Watch App/InterfaceView.swift
  Pocket Casts Watch App/MenuRow.swift
  Pocket Casts Watch App/NavigationManager.swift
  Pocket Casts Watch App/PhoneSourceViewModel.swift
  Pocket Casts Watch App/PlaySourceViewModel.swift
  Pocket Casts Watch App/PodcastsListView.swift
  Pocket Casts Watch App/SourceInterfaceController.swift
  Pocket Casts Watch App/TopLevelItemRowController.swift
  Pocket Casts Watch App/UpNextViewModel.swift
  Pocket Casts Watch App/WatchHostingController.swift
  Pocket Casts Watch App/WatchInterfaceType.swift
  Pocket Casts Watch App/WatchSourceViewModel.swift
  podcasts.xcodeproj/project.pbxproj
Labels: watchOS

#1733 Re-add: Fall back to root VC if no topmostPresented is found
  podcasts/SceneHelper.swift
Labels: Bug

#1735 Re-add: Sleep Timer Improvements: shake device to restart sleep timer
  podcasts.xcodeproj/project.pbxproj
  podcasts/MainTabBarController.swift
  podcasts/PlaybackManager.swift
  podcasts/SleepTimerManager.swift
  podcasts/sleep-timer-restarted-sound.mp3
Labels: Sleep Timer

#1711 Fix crash audio high filter
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/DefaultPlayer.swift
Labels: Bug, crash

#1630 [Tooling] Run Danger & SwiftLint on the Linter Agent
  .buildkite/pipeline.yml
  .github/workflows/run-danger.yml
  Dangerfile
  Gemfile.lock
Labels: tooling

#1736 Re-add: Sleep Timer Improvements: fade out 5s before pausing playback
  podcasts.xcodeproj/project.pbxproj
  podcasts/DefaultPlayer.swift
  podcasts/EffectsPlayer.swift
  podcasts/FadeOutManager.swift
  podcasts/GoogleCastPlayer.swift
  podcasts/PlaybackManager.swift
  podcasts/PlaybackProtocol.swift
  podcasts/SleepTimerManager.swift
Labels: Sleep Timer

#1640 Sleep Timer: add the option to select the number of episodes
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts/CustomStepper.swift
  podcasts/PlaybackManager.swift
  podcasts/Settings.swift
  podcasts/SleepTimerManager.swift
  podcasts/SleepTimerViewController.swift
  podcasts/SleepTimerViewController.xib
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Sleep Timer

#1741 Re add/cleanup build warnings
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  Pocket Casts Watch App/Assets.xcassets/upnext-9-plus.imageset/Contents.json
  Pocket Casts Watch App/Assets.xcassets/upnext-9-plus.imageset/upnext-9+@2x.png
  Pocket Casts Watch App/NowPlayingControls.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Bookmarks/List/BookmarkRow.swift
  podcasts/LocalizationHelpers.swift
  podcasts/PodcastSettingsViewController+Table.swift
  podcasts/PodcastViewController.swift
  podcasts/Settings.xcassets/settings-notifications.imageset/Contents.json
  podcasts/Settings.xcassets/settings-notifications.imageset/notifications@2x.png
  podcasts/Settings.xcassets/settings-notifications.imageset/notifications@3x.png
  podcasts/SwiftUI/Motion.swift
  podcasts/SwiftUI/UnderlineLinkTextView.swift
  podcasts/TimeSlider.swift
Labels: continuous integration

#1738 Re-Add Update for CI to use Xcode 15.3
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  README.md
Labels: continuous integration

#1740 Re-add Bookmark share
  podcasts/Bookmarks/Episode/BookmarkEpisodeListController.swift
  podcasts/Bookmarks/List/BookmarkListRouter.swift
  podcasts/Bookmarks/List/BookmarkListViewModel.swift
  podcasts/Bookmarks/List/BookmarksListView.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift
  podcasts/Bookmarks/Podcast/BookmarksPodcastListController.swift
  podcasts/Bookmarks/Profile/BookmarksProfileListController.swift
Labels: Bookmarks

#1742 Fallback to default player when length is not available
  podcasts/EffectsPlayer.swift
Labels: Bug

#1744 Re add UpNext on tab bar
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AnalyticsHelper.swift
  podcasts/CommonImages.xcassets/profile-placeholder.imageset/Contents.json
  podcasts/CommonImages.xcassets/profile-placeholder.imageset/profile.pdf
  podcasts/MainTabBarController.swift
  podcasts/NowPlayingAnimationView.swift
  podcasts/PCViewController.swift
  podcasts/PodcastListViewController.swift
  podcasts/TabBar.xcassets/Contents.json
  podcasts/TabBar.xcassets/upnext_tab.imageset/Contents.json
  podcasts/TabBar.xcassets/upnext_tab.imageset/upnext.pdf
  podcasts/UpNextNowPlayingCell.swift
  podcasts/UpNextViewController.swift
Labels: Up Next

#1746 Re-add: New grid layout
  podcasts.xcodeproj/project.pbxproj
  podcasts/CircleView.swift
  podcasts/FolderGridCell.swift
  podcasts/FolderGridCell.xib
  podcasts/FolderListCell.swift
  podcasts/FolderPreviewView.swift
  podcasts/FolderViewController.swift
  podcasts/GridBadgeView.swift
  podcasts/GridHelper.swift
  podcasts/PCRefreshControl.swift
  podcasts/PodcastGridCell.swift
  podcasts/PodcastGridCell.xib
  podcasts/PodcastListCell.swift
  podcasts/PodcastListViewController.swift
  podcasts/UnplayedBadge.swift
  podcasts/UnplayedSashOverlayView.swift
Labels: Podcast grid layout

#1745 Re-add: convert bookmark sort options to server sort options
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  podcasts/Enumerations.swift
  podcasts/Settings.swift
Labels: Bookmarks

#1737 Categories: Tracks events
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AnalyticsHelper.swift
  podcasts/Categories/CategoriesSelectorView.swift
  podcasts/SinglePodcastViewController.swift
Labels: Categories Redesign

#1687 Fix 1686 grid margins go off screen
  podcasts/PCSearchBarController+Scrolling.swift
  podcasts/PodcastListViewController.swift
  podcasts/UITableView+MiniPlayer.swift
Labels: Bug, Podcast grid layout

#1751 Remove folders cache
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts/PodcastManager+Delete.swift
Labels: crash

#1755 7.63.1 Release: Merge changes from 7.63.1.0 into `trunk`
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  config/Version.xcconfig
  podcasts/PodcastManager+Delete.swift
Labels: Releases

#1749 Automation refactors to better support Enterprise builds
  .configure
  .configure-files/app_store_connect_fastlane_api_key.json.enc
  fastlane/Fastfile
Labels: tooling

#1752 Ensure mini-player is visible in the background when full player is displaying
  podcasts/MiniPlayerToFullPlayerAnimator.swift
Labels: Bug

#1757 7.64 Release: Merge changes from 7.64.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1756 Fix ThemableTable crash in `intrinsicContentSize` getter
  podcasts/ThemeableTable.swift
Labels: Bug

#1760 New grid layout improvements
  podcasts/CircleView.swift
  podcasts/FolderGridCell.swift
  podcasts/FolderGridCell.xib
  podcasts/GridBadgeView.swift
  podcasts/PodcastGridCell.swift
  podcasts/PodcastGridCell.xib
Labels: Up Next, UI Related, Podcast grid layout

#1765 7.64 Release: Merge changes from 7.64.0.1 into `trunk`
  config/Version.xcconfig
  podcasts/CircleView.swift
  podcasts/FolderGridCell.swift
  podcasts/FolderGridCell.xib
  podcasts/GridBadgeView.swift
  podcasts/MiniPlayerViewController.xib
  podcasts/PodcastGridCell.swift
  podcasts/PodcastGridCell.xib
  podcasts/ThemeableTable.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1758 Remove obsolete `register_device` lane
  fastlane/Fastfile
Labels: tooling

#1768 Remove unused `PodcastsIntentsUI.entitlements`
  PodcastsIntentsUI/PodcastsIntentsUI.entitlements
  podcasts.xcodeproj/project.pbxproj
Labels: tooling

#1772 Ensure mini-player is visible in the background when full player is displaying
  podcasts/MiniPlayerToFullPlayerAnimator.swift
Labels: Bug

#1674 Fix scroll indicator insets to adjust for mini-player
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppearanceViewController.swift
  podcasts/BadgeSettingsViewController.swift
  podcasts/CategoryPodcastsViewController.swift
  podcasts/Constants.swift
  podcasts/CountryChooserViewController.swift
  podcasts/DiscoverViewController.swift
  podcasts/DownloadSettingsViewController.swift
  podcasts/DownloadedFilesViewController.swift
  podcasts/DownloadsViewController.swift
  podcasts/ExpandedCollectionViewController.swift
  podcasts/ExpandedEpisodeListViewController.swift
  podcasts/FilterSelectionViewController.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/ListeningHistoryViewController.swift
  podcasts/PCViewController.swift
  podcasts/PlaylistViewController.swift
  podcasts/PlaylistsViewController.swift
  podcasts/PodcastChooserViewController.swift
  podcasts/PodcastHeaderListViewController.swift
  podcasts/PodcastListViewController.swift
  podcasts/PodcastSettingsViewController.swift
  podcasts/PodcastViewController.swift
  podcasts/ProfileViewController.swift
  podcasts/SettingsViewController.swift
  podcasts/SiriSettingsViewController.swift
  podcasts/StarredViewController.swift
  podcasts/UIScrollView+MiniPlayer.swift
  podcasts/UploadedSettingsViewController.swift
  podcasts/UploadedViewController.swift
  podcasts/WatchSettingsViewController.swift
Labels: Bug

#1773 Standard Tags: fix show notes failing to retry and not persisting
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinator.swift
Labels: Bug, Standard Tags

#1767 Remove legacy Today Extension leftovers
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Today Extension.xcscheme
Labels: tooling

#1776 Fix mini player dissapearing on the iPad
  podcasts/MiniPlayerViewController+Positioning.swift
Labels: Bug

#1762 Add lowerSnakeCased default remoteKey
  Modules/Utils/Sources/PocketCastsUtils/Extensions/StringExtension.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/StringExtensionsTest.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate.swift
  podcasts/DeveloperMenu.swift
  podcasts/FirebaseManager.swift
Labels: enhancement

#1781 Fixes bar for episode selection in Podcast screen
  podcasts/PodcastViewController.swift
Labels: Bug

#1780 Download Issues: Retry Cancelled Tasks
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate.swift
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/DownloadManager.swift
  podcasts/URLSession+Episode.swift
Labels: downloads

#1783 7.65 Release: Merge changes from 7.65.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/Resources/release_notes.txt
Labels: Releases

#1784 Download Issues: Log active download tasks on launch
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate+Analytics.swift
  podcasts/AppDelegate.swift
  podcasts/DownloadManager.swift
Labels: downloads

#1761 Load `.env` file in `Fastlane` or fail if not available
  fastlane/Fastfile
  fastlane/example.env
  fastlane/lib/helpers.rb
Labels: tooling

#1790 Sleep timer: add options to enable/disable shake and auto restart
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Constants.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/MainTabBarController.swift
  podcasts/Settings.swift
  podcasts/SleepTimerManager.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement, Sleep Timer

#1743 Re-add: Use content type to set extension for downloaded files
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/UserEpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DBUtils.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/BaseEpisode.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/UserEpisode+Encoding.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/UserEpisode.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/MetadataTask.swift
  podcasts/BaseEpisode+Formatting.swift
  podcasts/DownloadManager+URLSessionDelegate.swift
Labels: playback

#1793 Add FileLog file to the database export
  podcasts.xcodeproj/project.pbxproj
  podcasts/AnyPublisher+Async.swift
  podcasts/DatabaseExport.swift
Labels: tooling

#1791 Fix visibility of multi-select on UpNextView controller
  podcasts.xcodeproj/project.pbxproj
  podcasts/InsetAdjuster.swift
  podcasts/PCViewController.swift
  podcasts/UIScrollView+MiniPlayer.swift
  podcasts/UpNextViewController.swift
Labels: Bug

#1794 7.65 Release: Merge changes from 7.65.0.1 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate+Analytics.swift
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/DownloadManager.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/InsetAdjuster.swift
  podcasts/MainTabBarController.swift
  podcasts/PCViewController.swift
  podcasts/Settings.swift
  podcasts/SleepTimerManager.swift
  podcasts/Strings+Generated.swift
  podcasts/UIScrollView+MiniPlayer.swift
  podcasts/UpNextViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#1785 Download Issues: Cancel URLSession tasks when deleting unused podcasts
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  Pocket Casts Watch App/WatchSyncManager+ServerSyncDelegate.swift
  PocketCastsTests/Extensions/FMDatabaseQueue+Test.swift
  PocketCastsTests/Tests/End of Year/EndOfYearStoriesBuilderTests.swift
  PocketCastsTests/Tests/Utilities/PodcastManagerTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/DownloadManager+SessionManagement.swift
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/DownloadManager.swift
  podcasts/PodcastManager+Cleanup.swift
  podcasts/PodcastManager+Delete.swift
  podcasts/PodcastManager.swift
  podcasts/PodcastViewController.swift
  podcasts/ServerSyncManager.swift
Labels: downloads

#1789 Up Next: add history and the option to restore
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/UpNextDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/UpNextHistoryManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/UpNextSyncTask.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/PlaybackQueue.swift
  podcasts/SettingsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/Up Next History/UpNextEntryView.swift
  podcasts/Up Next History/UpNextHistoryModel.swift
  podcasts/Up Next History/UpNextHistoryView.swift
  podcasts/Up Next History/UpNextHistoryViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement, Up Next
