Repository Automattic/pocket-casts-ios, pull requests merged in 2024-02, with the labels that each got.

#1390 Refactor the IAPHandler to not make requests to the production API during testing
  PocketCastsTests/Extensions/XCTestCase+WaitForNotification.swift
  PocketCastsTests/Tests/IAP/IAPHelperTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/IAPHelper.swift
Labels: Refactor

#1393 Replace shared URLSession usage with URLConnection
  Modules/Server/Sources/PocketCastsServer/Private/TokenHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/URLConnection.swift
Labels: Refactor

#1391 Removes all of the files in the podcasts folder that aren't being used
  podcasts/ApiBaseTask.swift
  podcasts/ChangeEmailTask.swift
  podcasts/ChangePasswordTask.swift
  podcasts/EpisodeFilterViewController.swift
  podcasts/ErrorResponse.swift
  podcasts/FilterSettingsViewController.swift
  podcasts/FilterSettingsViewController.xib
  podcasts/KeychainHelper.swift
  podcasts/NewPasswordViewController.swift
  podcasts/NewPasswordViewController.xib
  podcasts/NotificationsHelper+Fire.swift
  podcasts/PodcastFilterViewController.swift
  podcasts/PodcastSearchOperation.swift
  podcasts/PositionSyncTask.swift
  podcasts/PurchaseReceiptTask.swift
  podcasts/RecommendEpisodesTask.swift
  podcasts/RedeemPromoCodeTask.swift
  podcasts/RefreshOperation.swift
  podcasts/ReleaseDateFilterViewController.swift
  podcasts/RetrieveCustomFilesTask.swift
  podcasts/RetrieveEpisodesTask.swift
  podcasts/RetrieveFileUploadStatus.swift
  podcasts/RetrieveFileUsageTask.swift
  podcasts/RetrieveFiltersTask.swift
  podcasts/RetrieveLastSyncDateTask.swift
  podcasts/RetrievePodcastsTask.swift
  podcasts/RetrieveStarredTask.swift
  podcasts/RetrieveStatsTask.swift
  podcasts/SJChapterIntent.swift
  podcasts/StarredSyncTask.swift
  podcasts/SubscriptionHelper.swift
  podcasts/SubscriptionStatusTask.swift
  podcasts/SyncHistoryTask.swift
  podcasts/SyncSettingsTask.swift
  podcasts/SyncTask+FullSync.swift
  podcasts/SyncTask+LocalChanges.swift
  podcasts/SyncTask.swift
  podcasts/UIButton+EasyActions.swift
  podcasts/URLConnection.swift
  podcasts/UpNextItem.swift
  podcasts/UpNextSyncTask.swift
  podcasts/UploadFileDeleteTask.swift
  podcasts/UploadFilePlayRequestTask.swift
  podcasts/UploadFileRequestTask.swift
  podcasts/UploadFilesUpdateTask.swift
  podcasts/UploadImageDeleteTask.swift
  podcasts/UploadImageRequestTask.swift
  podcasts/ValidatePromoCodeHandler.swift
  podcasts/api.pb.swift
  podcasts/files.pb.swift
Labels: tech debt

#1392 Fixes all the lint warnings
  podcasts/CarPlaySceneDelegate.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Settings.swift
  podcasts/SettingsViewController.swift
Labels: tech debt

#1398 Disable the IAPHelperTests
  PocketCastsTests/Tests/IAP/IAPHelperTests.swift
  PocketCastsTests/UnitTests.xctestplan
  podcasts.xcodeproj/xcshareddata/xcschemes/pocketcasts.xcscheme
Labels: Testing

#1384 CI Run for #788
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts/AutoAddToUpNextViewController+PodcastSelect.swift
Labels: continuous integration

#1401 Settings sync feature flag
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshOperation.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  podcasts/AppDelegate.swift
  podcasts/FeatureFlag.swift
Labels: enhancement, settings

#1409 [Xcode 15.2] Update CI/README
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  README.md
Labels: tooling

#1378 7.56 Release: Merge changes from 7.56.0.2 into `trunk`
  config/Version.xcconfig
Labels: Releases

#1405 Update protobuf files for Settings sync
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/files.pb.swift
Labels: settings

#1415 [Slumber] Strings
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement

#1413 Fix `SyncManager` variable name in non-debug builds
  podcasts/AppDelegate.swift
Labels: settings

#1416 7.57 Release: Merge changes from 7.57.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1361 SwiftLint setup update and code fixes
  .buildkite/pipeline.yml
  .swiftlint.yml
  Podfile
  Podfile.lock
  podcasts.xcodeproj/project.pbxproj
  podcasts/DateHeadingView.swift
  podcasts/SimpleActionView.swift
  podcasts/WhatsNewPageView.swift
Labels: tooling

#1408 [Slumber] Add Feature Flag
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/FeatureFlag.swift
  podcasts/Settings.swift
Labels: enhancement

#1406 Settings sync storage
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/CodableStore.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerEnums.swift
  Modules/Server/Sources/PocketCastsServer/Public/SettingsStore.swift
  Modules/Server/Tests/PocketCastsServerTests/SettingsStoreTests.swift
  Modules/Utils/Sources/PocketCastsUtils/General/ModifiedDate.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/ModifiedDateTests.swift
  podcasts/Enumerations.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/Settings.swift
Labels: settings

#1421 Fix SwiftLint strict error
  Modules/Utils/Tests/PocketCastsUtilsTests/ModifiedDateTests.swift
Labels: tooling

#1379 [Tracks] Track content type on playback events
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
Labels: analytics

#1394 Update account upgrade modal
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/pocketcasts.xcscheme
  podcasts/IAPHelper.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountPromptTableCell.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusButtonStyles.swift
  podcasts/Onboarding/Plus/PlusPurchaseModal.swift
  podcasts/Onboarding/Plus/SubscriptionPriceAndOfferView.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/UIScreen+Sizes.swift
  podcasts/en.lproj/Localizable.strings
Labels: Plus, Patron

#1382 [Library Update] Automattic-Tracks-iOS
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/IAPHelper.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
Labels: dependencies

#1407 Settings Sync
  Modules/Server/Sources/PocketCastsServer/Public/ApiSetting+ModifiedDate.swift
  Modules/Server/Sources/PocketCastsServer/Public/ApiSetting.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  Modules/Server/Tests/MockURLHandler.swift
  Modules/Server/Tests/PocketCastsServerTests/ApiSettingsTests+ModifiedDate.swift
  Modules/Server/Tests/PocketCastsServerTests/SyncSettingsTaskTests.swift
  podcasts.xcodeproj/project.pbxproj
Labels: settings

#1420 Build Environment runtime DEBUG check
  podcasts/AppDelegate.swift
Labels: Refactor

#1424 Fix SwiftLint whitespace issues
  Modules/Server/Sources/PocketCastsServer/Public/ApiSetting+ModifiedDate.swift
  Modules/Server/Tests/PocketCastsServerTests/ApiSettingsTests+ModifiedDate.swift
  Modules/Server/Tests/PocketCastsServerTests/SyncSettingsTaskTests.swift
Labels: tooling

#1410 Feature/updade account upgrade flows
  podcasts.xcodeproj/project.pbxproj
  podcasts/AccountViewController.swift
  podcasts/FeatureFlag.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountPromptTableCell.swift
  podcasts/Onboarding/Plus/Account Prompt/UpgradePrompt.swift
  podcasts/Onboarding/Plus/FeaturesCarousel.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Onboarding/Plus/UpgradeRoundedSegmentedControl.swift
  podcasts/Profile - SwiftUI/Account/AccountHeaderView.swift
Labels: Plus, Patron

#1423 Settings Sync import UserDefaults
  Modules/Server/Sources/PocketCastsServer/Public/SettingsStore.swift
  PocketCastsTests/Tests/Utilities/AppSettings+ImportUserDefaultsTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate+Defaults.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Settings.swift
Labels: settings

#1425 Setting Sync: General settings
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerEnums.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  Modules/Server/Tests/PocketCastsServerTests/SyncSettingsTaskTests.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Enumerations.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/MiniPlayerViewController.swift
  podcasts/NowPlayingPlayerItemViewController+Update.swift
  podcasts/PlaybackCatchUpHelper.swift
  podcasts/PlaybackManager.swift
  podcasts/Settings.swift
  podcasts/VideoViewController.swift
  podcasts/WatchManager.swift
Labels: settings

#1422 Improves large text size support and animations on the upgrade views
  podcasts/Onboarding/Plus/FeaturesCarousel.swift
  podcasts/Onboarding/Plus/SubscriptionPriceAndOfferView.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
Labels: Plus

#1397 [Deselecting Chapters] Add feature flag
  podcasts/AppDelegate.swift
  podcasts/FeatureFlag.swift
Labels: Deselecting Chapters

#1399 [Deselecting Chapters] Add checkbox to toggle chapter selection
  podcasts/PlayerChapterCell.swift
  podcasts/PlayerChapterCell.xib
Labels: Deselecting Chapters

#1426 [Deselecting Chapters] Playback
  PocketCastsTests/Tests/Playback/Chapters/ChapterManagerTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/ChapterInfo.swift
  podcasts/ChapterManager.swift
  podcasts/PlaybackManager.swift
  podcasts/PlayerChapterCell.swift
  podcasts/PlayerChapterCell.xib
Labels: Deselecting Chapters

#1418 Dangermattic checks update
  .github/workflows/run-danger.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: tooling

#1434 CI RUN: File Size Sometimes Showing As "0 Bytes" #1044
  podcasts/EpisodeDetailViewController+Actions.swift
Labels: Bug

#1435 Settings Sync: Update API sync settings protobuf models
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
Labels: settings

#1432 Settings sync: Podcast Custom Effects Settings
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/BaseEpisode.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/PodcastSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/ApiSetting.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+FullSync.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+ServerChanges.swift
  PocketCastsTests/Mocks/DataManagerMock.swift
  PocketCastsTests/Tests/Utilities/AppSettings+ImportUserDefaultsTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/Helpers/AnalyticsPlaybackHelper.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/DataManager+Import.swift
  podcasts/EffectsViewController.swift
  podcasts/HomeGridListItem.swift
  podcasts/ListPodcast.swift
  podcasts/PlaybackEffects.swift
  podcasts/PlaybackManager.swift
  podcasts/Podcast+Settings.swift
  podcasts/PodcastEffectsViewController+Table.swift
  podcasts/PodcastSettingsViewController+Table.swift
  podcasts/ServerSyncManager.swift
Labels: settings

#1438 Settings sync: Podcast Episodes Layout Menu
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/PodcastSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+ServerChanges.swift
  Pocket Casts Watch App Extension/OrderPicker.swift
  Pocket Casts Watch App Extension/PodcastEpisodeListViewModel.swift
  Pocket Casts Watch App Extension/SortOption.swift
  podcasts/DataManager+Import.swift
  podcasts/Enumerations.swift
  podcasts/EpisodeListSearchController.swift
  podcasts/EpisodesDataManager.swift
  podcasts/PlaybackManager.swift
  podcasts/Podcast+Formatting.swift
  podcasts/Podcast+Settings.swift
  podcasts/PodcastViewController.swift
  podcasts/SiriShortcutsManager.swift
Labels: settings

#1439 [What's New] Change how the announcements are return to allow remotely enabling them
  PocketCastsTests/Tests/Whats New/WhatsNewTests.swift
  podcasts/Whats New/WhatsNew.swift
Labels: Bug

#1431 [Deselecting Chapters] Persistence
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/BaseEpisode+Chapters.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/BaseEpisode.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/UserEpisode.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/BaseEpisodeTests.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/PocketCastsDataModelTests.swift
  podcasts/ChapterManager.swift
  podcasts/PlayerChapterCell.swift
Labels: Deselecting Chapters

#1436 [Deselecting chapters] Add header to toggle chapter selection
  PocketCastsTests/Mocks/FeatureFlagMock.swift
  PocketCastsTests/Tests/Playback/Chapters/ChapterManagerTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/ChapterInfo.swift
  podcasts/ChapterManager.swift
  podcasts/ChaptersHeader.swift
  podcasts/ChaptersViewController+Table.swift
  podcasts/ChaptersViewController.swift
  podcasts/ChaptersViewController.xib
  podcasts/PlaybackManager.swift
  podcasts/PlayerChapterCell.swift
  podcasts/PlayerChapterCell.xib
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Deselecting Chapters

#1443 Bugfix - fix crash on up next updates
  podcasts/UpNextViewController+Table.swift
  podcasts/UpNextViewController.swift
Labels: Bug

#1442 Settings Sync: Playback effects
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/PlaybackEffects.swift
  podcasts/PlaybackManager.swift
Labels: settings

#1445 Settings Sync: Warn data usage
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Settings.swift
Labels: settings

#1447 7.57 Release: Merge changes from 7.57.0.1 into `trunk`
  PocketCastsTests/Tests/Whats New/WhatsNewTests.swift
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/FeatureFlag.swift
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-slumber.imageset/Contents.json
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-slumber.imageset/moon-icon.svg
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/PaidFeature.swift
  podcasts/Settings.swift
  podcasts/SwiftUI/UnderlineLinkTextView.swift
  podcasts/UIViewController+Presenting.swift
  podcasts/UpNextViewController+Table.swift
  podcasts/UpNextViewController.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/SlumberViews.swift
  podcasts/Whats New/WhatsNew.swift
  podcasts/Whats New/WhatsNewFullView.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1449 [Deselect Chapters] Purchase flow
  PocketCastsTests/Tests/Playback/Chapters/ChapterManagerTests.swift
  podcasts/ChapterInfo.swift
  podcasts/ChaptersHeader.swift
  podcasts/ChaptersViewController+Table.swift
  podcasts/ChaptersViewController.swift
  podcasts/PaidFeature.swift
Labels: Deselecting Chapters

#1451 Settings Sync: Add bookmarks sort synced settings value
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Bookmarks/Episode/BookmarkEpisodeListController.swift
  podcasts/Bookmarks/List/BookmarkEpisodeListViewModel.swift
  podcasts/Bookmarks/List/BookmarkListViewModel.swift
  podcasts/Bookmarks/List/BookmarksListView.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTab.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift
  podcasts/Bookmarks/Podcast/BookmarksPodcastListController.swift
  podcasts/Enumerations.swift
  podcasts/Settings.swift
Labels: settings

#1456 Update search for podcast code to handle polling results
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/PodcastSearchOperation.swift
  Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  podcasts/AppDelegate+UrlHandling.swift
Labels: Bug

#1448 Settings Sync: Headphone Controls
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerEnums.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Settings.swift
Labels: settings

#1459 7.58 Release: Merge changes from 7.58.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1441 Settings Sync: Privacy Flags
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  Modules/Server/Sources/PocketCastsServer/Public/SubscriptionHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlagOverrideStore.swift
  Pocket Casts Watch App Extension/PodcastEpisodeListViewModel.swift
  PocketCastsTests/Mocks/FeatureFlagMock.swift
  PocketCastsTests/Tests/FeatureFlagTests.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/Analytics.swift
  podcasts/AnalyticsHelper.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Beta/BetaMenu.swift
  podcasts/ChapterInfo.swift
  podcasts/ChaptersViewController+Table.swift
  podcasts/Constants.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
  podcasts/MainTabBarController.swift
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/MiniPlayerViewController.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountPromptTableCell.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/PlaybackEffects.swift
  podcasts/Podcast+Settings.swift
  podcasts/PodcastEffectsViewController+Table.swift
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/ServerSyncManager.swift
  podcasts/Settings.swift
Labels: settings

#1455 Settings Sync: Auto Archive
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+Settings.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/PodcastSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+FullSync.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+ServerChanges.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/FeatureFlagTests.swift
  Pocket Casts Watch App Extension/WatchSyncManager.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsDescribable+Modules.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/ArchiveHelper.swift
  podcasts/DataManager+Import.swift
  podcasts/DownloadManager.swift
  podcasts/Episode+Formatting.swift
  podcasts/EpisodeDetailViewController+Actions.swift
  podcasts/EpisodeListSearchController.swift
  podcasts/EpisodeManager.swift
  podcasts/Podcast+Settings.swift
  podcasts/PodcastArchiveViewController+Table.swift
  podcasts/PodcastManager+Delete.swift
  podcasts/PodcastViewController.swift
  podcasts/Settings.swift
  podcasts/SupportConfig.swift
  podcasts/WatchManager.swift
Labels: settings

#1465 Settings Sync: Podcast List Layout
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  Pocket Casts Watch App Extension/SortOption.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Enumerations.swift
  podcasts/Folder+Formatting.swift
  podcasts/PodcastListViewController+Search.swift
  podcasts/PodcastListViewController.swift
  podcasts/PodcastPickerModel.swift
  podcasts/Settings.swift
Labels: settings

#1466 Fix Slumber link on upgrade
  podcasts/Onboarding/Plus/UpgradeCard.swift
Labels: Bug

#1470 7.58 Release: Merge changes from 7.58.0.1 into `trunk`
  config/Version.xcconfig
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1460 [Deselect Chapters] Design
  podcasts/ChaptersHeader.swift
  podcasts/ChaptersViewController+Table.swift
  podcasts/ChaptersViewController.swift
  podcasts/CommonImages.xcassets/rounded-deselected.imageset/Contents.json
  podcasts/CommonImages.xcassets/rounded-deselected.imageset/rounded-deselected.svg
  podcasts/CommonImages.xcassets/rounded-selected.imageset/Contents.json
  podcasts/CommonImages.xcassets/rounded-selected.imageset/rounded-selected.svg
  podcasts/PlaybackManager.swift
  podcasts/PlayerChapterCell.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Deselecting Chapters

#1462 [Deselect Chapters] Tracks
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsPlaybackHelper.swift
  podcasts/ChapterManager.swift
  podcasts/ChaptersViewController+Table.swift
  podcasts/ChaptersViewController.swift
  podcasts/PlaybackManager.swift
  podcasts/PlayerChapterCell.swift
  podcasts/PlayerContainerViewController.swift
Labels: Deselecting Chapters

#1467 [Deselect Chapters] Add it in the list of features
  podcasts/ChaptersViewController+Table.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/PaidFeature.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Deselecting Chapters

#1452 Settings Sync: Add files settings
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Settings.swift
Labels: settings

#1469 Remove unnecessary IAP sync on syncing remote flags
  podcasts/AppDelegate.swift
Labels: Patron

#1444 Settings Sync: Player Shelf
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/Server/Sources/PocketCastsServer/Public/ApiSetting.swift
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Enumerations.swift
  podcasts/Settings.swift
  podcasts/ShelfLoadState.swift
  podcasts/Unlockable/Unlockable+Bookmarks.swift
Labels: settings

#1463 Tooling: define common SwiftLint version
  .buildkite/commands/run-swiftlint.sh
  .buildkite/pipeline.yml
  .swiftlint.yml
  Podfile
  Podfile.lock
Labels: tooling

#1471 Encapsulate the StoreKit calls inside the IAPHelper class.
  podcasts/AppDelegate.swift
  podcasts/IAPHelper.swift
Labels: Refactor

#1474 Fix setting the new upgrade account flow feature flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Bug

#1454 Settings Sync: Up Next
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/AutoAddQueueDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/PodcastSettings+OldSettings.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/PodcastSettings.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/AutoAddCandidatesDataManagerTests.swift
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerEnums.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+ServerChanges.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlagMock.swift
  PocketCastsTests/Tests/Playback/Chapters/ChapterManagerTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/AutoAddToUpNextViewController+PodcastSelect.swift
  podcasts/AutoAddToUpNextViewController.swift
  podcasts/DataManager+Import.swift
  podcasts/PodcastSettingsViewController+Table.swift
Labels: settings

#1473 [Deselect Chapters] What's New
  podcasts.xcodeproj/project.pbxproj
  podcasts/CommonImages.xcassets/deselect_chapters.imageset/Contents.json
  podcasts/CommonImages.xcassets/deselect_chapters.imageset/deselect_chapters.svg
  podcasts/Strings+Generated.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/DeselectChaptersAnnouncementViewModel.swift
  podcasts/en.lproj/Localizable.strings
Labels: Deselecting Chapters

#1479 Main dispatch `Analytics.refreshRegistered` on sync
  podcasts/ServerSyncManager.swift
Labels: Bug

#1483 [Slumber] Make it available only for lifetime and yearly subscriptions
  podcasts/Constants.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/Whats New/SlumberViews.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bug

#1478 Fix constraints on Sleep Timer view
  podcasts/SleepTimerViewController.swift
  podcasts/SleepTimerViewController.xib
Labels: Bug

#1484 7.57.1 Release: Merge changes from 7.57.1.0 into `trunk`
  fastlane/Fastfile
  podcasts/Constants.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Strings+Generated.swift
  podcasts/Whats New/SlumberViews.swift
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#1485 Settings Sync: General Auto Download settings
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncSettingsTask.swift
  podcasts/AppSettings+ImportUserDefaults.swift
  podcasts/Settings.swift
Labels: settings

#1488 Merge slumber fix on 7.58
  podcasts/Constants.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Strings+Generated.swift
  podcasts/Whats New/SlumberViews.swift
  podcasts/en.lproj/Localizable.strings
Labels: Bug

#1482 [What's New] Ensure announcement is displayed after enabled
  PocketCastsTests/Tests/Whats New/WhatsNewTests.swift
  podcasts/Whats New/WhatsNew.swift
Labels: Bug

#1489 7.58 Release: Merge changes from 7.58.0.2 into `trunk`
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+LocalChanges.swift
  PocketCastsTests/Tests/Whats New/WhatsNewTests.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/Whats New/WhatsNew.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases
