Repository Automattic/pocket-casts-ios, pull requests merged in 2024-11, with the labels that each got.

#2376 Playback 2024: Ratings
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/UserPodcastRating.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/RatingsDataManager.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/RetrieveRatingsTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/UserPodcastRatingTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+UserPodcastRating.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/End of Year/End of Year 2023/EndOfYear2023StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/2024/Ratings2024Story.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/EndOfYear.xcassets/star.imageset/Contents.json
  podcasts/EndOfYear.xcassets/star.imageset/star.svg
  podcasts/Strings+Generated.swift
  podcasts/SwiftUI/SFSafariView.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024

#2377 Playback 2024: Sharing
  PocketCastsTests/Tests/End of Year/StoriesModelTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2023/EndOfYear2023StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/2023/CompletionRateStory2023.swift
  podcasts/End of Year/Stories/2023/YearOverYearStory2023.swift
  podcasts/End of Year/Stories/2024/CompletionRate2024Story.swift
  podcasts/End of Year/Stories/2024/ListeningTime2024Story.swift
  podcasts/End of Year/Stories/2024/Ratings2024Story.swift
  podcasts/End of Year/Stories/2024/Top5Podcasts2024Story.swift
  podcasts/End of Year/Stories/2024/YearOverYearCompare2024Story.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/StoryShareableProvider.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/EndOfYear.xcassets/logo_pill.imageset/Contents.json
  podcasts/EndOfYear.xcassets/logo_pill.imageset/logo_pill.svg
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024

#2379 Playback 2024: Localize Number Listened
  podcasts/End of Year/Stories/2024/NumberListened2024.swift
Labels: [Project] End of Year 2024

#2381 Playback 2024: Explicitly set Foreground Color
  podcasts/End of Year/Stories/2024/CompletionRate2024Story.swift
  podcasts/End of Year/Stories/2024/EpilogueStory2024.swift
  podcasts/End of Year/Stories/2024/PaidStoryWallView2024.swift
  podcasts/End of Year/Stories/2024/Top5Podcasts2024Story.swift
Labels: [Project] End of Year 2024

#2383 Referrals Force FF Referrals Send to default value true
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Referrals

#2380 Playback 2024: Analytics
  podcasts/End of Year/Stories/2024/CompletionRate2024Story.swift
  podcasts/End of Year/Stories/2024/EpilogueStory2024.swift
  podcasts/End of Year/Stories/2024/IntroStory2024.swift
  podcasts/End of Year/Stories/2024/ListeningTime2024Story.swift
  podcasts/End of Year/Stories/2024/NumberListened2024.swift
  podcasts/End of Year/Stories/2024/PaidStoryWallView2024.swift
  podcasts/End of Year/Stories/2024/Ratings2024Story.swift
  podcasts/End of Year/Stories/2024/Top5Podcasts2024Story.swift
  podcasts/End of Year/Stories/2024/TopSpotStory2024.swift
  podcasts/End of Year/Stories/2024/YearOverYearCompare2024Story.swift
Labels: [Project] End of Year 2024

#2391 Watch sync issue
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/MainServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/BackgroundSyncManager+URLSession.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/BackgroundSyncManager.swift
  Pocket Casts Watch App/ExtensionDelegate.swift
  Pocket Casts Watch App/WatchSyncManager.swift
  podcasts/DownloadManager+SessionManagement.swift
Labels: [Type] Bug, watchOS 11

#2393 EOY 2024: Fix header and duration issues
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/Stories/2023/IntroStory2023.swift
  podcasts/End of Year/Views/StoriesView.swift
Labels: [Project] End of Year 2024

#2401 Merge release/7.76 into trunk
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/MainServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/BackgroundSyncManager+URLSession.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/BackgroundSyncManager.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  Pocket Casts Watch App/ExtensionDelegate.swift
  Pocket Casts Watch App/WatchSyncManager.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/DownloadManager+SessionManagement.swift
  podcasts/Strings+Generated.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2399 Eoy2024: fix marquee alignment and sizes
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/Stories/2024/EpilogueStory2024.swift
  podcasts/End of Year/Stories/2024/Ratings2024Story.swift
  podcasts/End of Year/Views/MarqueeTextView.swift
Labels: [Project] End of Year 2024

#2402 Eoy2024: Fix footers text alignment
  podcasts/End of Year/Stories/2024/CompletionRate2024Story.swift
  podcasts/End of Year/Stories/2024/EpilogueStory2024.swift
  podcasts/End of Year/Stories/2024/ListeningTime2024Story.swift
  podcasts/End of Year/Stories/2024/LongestEpisode2024Story.swift
  podcasts/End of Year/Stories/2024/NumberListened2024.swift
  podcasts/End of Year/Stories/2024/PaidStoryWallView2024.swift
  podcasts/End of Year/Stories/2024/Ratings2024Story.swift
  podcasts/End of Year/Stories/2024/StoryFooter2024.swift
  podcasts/End of Year/Stories/2024/Top5Podcasts2024Story.swift
  podcasts/End of Year/Stories/2024/TopSpotStory2024.swift
  podcasts/End of Year/Stories/2024/YearOverYearCompare2024Story.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024

#2405 Update to support day hour minutes stats
  podcasts/End of Year/Stories/2024/ListeningTime2024Story.swift
Labels: [Project] End of Year 2024

#2406 EOY 2024: Add scale animation for completion
  podcasts/End of Year/Stories/2024/CompletionRate2024Story.swift
Labels: [Project] End of Year 2024

#2409 [Up Next Shuffle] Enable FF
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Projec] Up Next Shuffle

#2382 Playback 2024: Enable FF
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] End of Year 2024

#2404 [Paywall Experiment] Add dynamic header based on source
  podcasts/Constants.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountPromptTableCell.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Paywall Experiments

#2408 Merge release/7.76 into trunk
  config/Version.xcconfig
  podcasts/it.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2407 EOY 2024: Add logic to show eoy stories on image tap and on account sign in
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/Views/EndOfYearModal.swift
  podcasts/MainTabBarController.swift
Labels: [Project] End of Year 2024

#2412 Merge release/7.77 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2413 Merge release/7.76.1 into release/7.77
  config/Version.xcconfig
Labels: Releases

#2415 [Playback 2024] Prompt Playback 24 sheet after sign in with Google or Apple
  podcasts/Onboarding/LoginCoordinator.swift
Labels: [Type] Bug, [Project] End of Year 2024

#2419 [UpNextShuffle] Dismiss the UpNext vc to present the paywall
  podcasts/UpNextViewController.swift
Labels: [Type] Bug, [Projec] Up Next Shuffle

#2416 Download manager fix issues when streaming and downloading
  podcasts/DownloadManager.swift
  podcasts/FileManager+Helper.swift
  podcasts/MediaExporterResourceLoaderDelegate.swift
  podcasts/MediaFileHandle.swift
Labels: Downloads

#2414 [Sentry] Avoid force unwrap
  podcasts/PlaybackManager.swift
Labels: [Type] Bug

#2420 [Crash] Default Player crash with MTAudioProcessingTapCallbacks
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileLog.swift
  podcasts/DefaultPlayer.swift
Labels: [Type] Bug

#2421 Playback 2024: Remove duration from ending story in Playback 2024
  podcasts/End of Year/Stories/2024/EpilogueStory2024.swift
Labels: [Project] End of Year 2024

#2427 Playback 2024: Top Podcasts Title spacing
  podcasts/End of Year/Stories/2024/Top5Podcasts2024Story.swift
Labels: [Project] End of Year 2024

#2425 Watch sync improvements
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Area] watchOS

#2426 Playback 2024: Add periods to story descriptions
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024

#2447 Update Changelog
  CHANGELOG.md
Labels: Changelog

#2439 Merge release/7.77 into trunk
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileLog.swift
  config/Version.xcconfig
  podcasts/DefaultPlayer.swift
  podcasts/DownloadManager.swift
  podcasts/End of Year/Stories/2024/EpilogueStory2024.swift
  podcasts/End of Year/Stories/2024/Top5Podcasts2024Story.swift
  podcasts/FileManager+Helper.swift
  podcasts/MediaExporterResourceLoaderDelegate.swift
  podcasts/MediaFileHandle.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/PlaybackManager.swift
  podcasts/UpNextViewController.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2455 File downloads use switch instead of check box for include starred
  CHANGELOG.md
  podcasts/DownloadedFilesViewController.swift
Labels: [Project] Download Management

#2457 Ensure dismiss of referral tip is done before presenting EOY 2024
  podcasts/ProfileViewController.swift
Labels: [Type] Bug

#2452 [Winback] Add FF and first screen skeleton
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AccountViewController+TableView.swift
  podcasts/Cancel Subscription/CancelSubscriptionView.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewModel.swift
Labels: [Project] Winback

#2458 Manage downloads: show modal on auto-downloads and storage
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Constants.swift
  podcasts/DownloadSettingsViewController.swift
  podcasts/DownloadsViewController.swift
  podcasts/EpisodeManager.swift
  podcasts/ManageDownloadsBannerView.swift
  podcasts/ManageDownloadsCoordinator.swift
  podcasts/ManageDownloadsModalView.swift
  podcasts/Settings.swift
  podcasts/StorageAndDataUseViewController.swift
Labels: [Project] Download Management

#2448 Use Episode IDs from the sync task response instead of our local ones
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/BackgroundSyncManager+URLSession.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+ServerChanges.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask.swift
  Modules/Server/Tests/PocketCastsServerTests/SyncTaskTests+Episodes.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Type] Bug

#2461 Split build from upload in CI
  .buildkite/commands/release-build.sh
  .buildkite/commands/release-upload.sh
  .buildkite/release-builds.yml
  .gitignore
  config/Version.xcconfig
  fastlane/Fastfile
Labels: [Type] Tooling, Releases

#2463 [Tooling] Update release branch to `xcode-16.0-v10` VM on CI
  .buildkite/commands/release-upload.sh
  .buildkite/shared-pipeline-vars
Labels: [Type] Tooling

#2465 Install only necessary setup for `release-upload.sh`
  .buildkite/commands/release-upload.sh
Labels: [Type] Tooling

#2464 Fix Airplay stream issues
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/EpisodeManager.swift
Labels: [Type] Bug

#2462 Fix ratings star
  podcasts/End of Year/Stories/2024/Ratings2024Story.swift
  podcasts/EndOfYear.xcassets/playback-2024-star.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-2024-star.imageset/star.svg
Labels: [Type] Bug

#2460 Fix download date for stream downloads
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/DownloadManager.swift
  podcasts/EpisodesDataManager.swift
Labels: Downloads, [Type] Fix

#2467 Merge release/7.77 into trunk
  .buildkite/commands/release-build.sh
  .buildkite/commands/release-upload.sh
  .buildkite/release-builds.yml
  .buildkite/shared-pipeline-vars
  .gitignore
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  config/Version.xcconfig
  fastlane/Fastfile
  fastlane/Frozen.strings
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/DownloadManager.swift
  podcasts/End of Year/Stories/2023/CompletionRateStory2023.swift
  podcasts/End of Year/Stories/2023/ListenedNumbersStory2023.swift
  podcasts/End of Year/Stories/2023/ListeningTimeStory2023.swift
  podcasts/End of Year/Stories/2023/LongestEpisodeStory2023.swift
  podcasts/End of Year/Stories/2023/TopFivePodcastsStory2023.swift
  podcasts/End of Year/Stories/2023/TopListenedCategoriesStory2023.swift
  podcasts/End of Year/Stories/2023/TopOnePodcastStory2023.swift
  podcasts/End of Year/Stories/2023/YearOverYearStory2023.swift
  podcasts/End of Year/Stories/2024/CompletionRate2024Story.swift
  podcasts/End of Year/Stories/2024/ListeningTime2024Story.swift
  podcasts/End of Year/Stories/2024/LongestEpisode2024Story.swift
  podcasts/End of Year/Stories/2024/NumberListened2024.swift
  podcasts/End of Year/Stories/2024/Ratings2024Story.swift
  podcasts/End of Year/Stories/2024/Top5Podcasts2024Story.swift
  podcasts/End of Year/Stories/2024/TopSpotStory2024.swift
  podcasts/End of Year/Stories/2024/YearOverYearCompare2024Story.swift
  podcasts/End of Year/StoryShareableText.swift
  podcasts/EndOfYear.xcassets/playback-2024-star.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-2024-star.imageset/star.svg
  podcasts/EpisodeManager.swift
  podcasts/EpisodesDataManager.swift
  podcasts/ProfileViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2471 Restore using `install_swift_dependencies` and SwiftPM cache
  .buildkite/commands/shared_setup.sh
Labels: [Type] Tooling

#2466 [Winback] New Cancel Subscription view
  podcasts.xcodeproj/project.pbxproj
  podcasts/Cancel Subscription/CancelSubscriptionView.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewModel.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewRow.swift
  podcasts/CancelConfirmationViewModel.swift
  podcasts/CancelSubscription.xcassets/Contents.json
  podcasts/CancelSubscription.xcassets/chevron-small-right.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/chevron-small-right.imageset/chevron-small-right.svg
  podcasts/CancelSubscription.xcassets/cs-heart.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-heart.imageset/heart.svg
  podcasts/CancelSubscription.xcassets/cs-help.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-help.imageset/help.svg
  podcasts/CancelSubscription.xcassets/cs-skipbackward.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-skipbackward.imageset/skipbackward.svg
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Winback

#2469 [Winback] Link row to Help & Feedback
  podcasts.xcodeproj/project.pbxproj
  podcasts/Cancel Subscription/CancelSubscriptionOption.swift
  podcasts/Cancel Subscription/CancelSubscriptionView.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewModel.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewRow.swift
Labels: [Project] Winback

#2475 [Tooling] Update `Dangerfile` to run Rubocop with `bundle exec`
  Dangerfile
Labels: [Type] Tooling

#2468 Referrals: update share message
  CHANGELOG.md
  podcasts/Referrals/ReferralCardView.swift
  podcasts/Referrals/ReferralSendPassVC.swift
  podcasts/Referrals/ReferralSendPassView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Referrals

#2470 Set End of Year Modal shown immediately on presentation
  podcasts/End of Year/EndOfYear.swift
Labels: [Type] Bug

#2476 Merge release/7.77 into trunk
  config/Version.xcconfig
  podcasts/End of Year/EndOfYear.swift
Labels: Releases

#2478 Rename image
  podcasts/Cancel Subscription/CancelSubscriptionViewRow.swift
  podcasts/CancelSubscription.xcassets/cs-chevron.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-chevron.imageset/chevron-small-right.svg
Labels: [Type] Bug

#2477 Insert a note to the support ticket to indicate logs are attached
  podcasts/Zendesk/MessageSupportViewModel.swift
Labels: [Type] Other

#2474 [Winback] Apply Apple API for subscription cancellation
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/SubscriptionStatusTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+Account.swift
  podcasts/Cancel Subscription/CancelSubscriptionView.swift
  podcasts/CancelConfirmationViewModel.swift
  podcasts/IAPHelper.swift
Labels: [Project] Winback

#2484 Merge release/7.78 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2487 [Up Next Shuffle] Add Up Next Sheet
  podcasts.xcodeproj/project.pbxproj
  podcasts/Strings+Generated.swift
  podcasts/UpNext.xcassets/up-next-shuffle-sheet.imageset/Contents.json
  podcasts/UpNext.xcassets/up-next-shuffle-sheet.imageset/shuffle.svg
  podcasts/UpNextAnnouncementView.swift
  podcasts/Whats New/Announcements.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Enhancement

#2486 Ensure that the refresh of navigation buttons is made before the view appears
  CHANGELOG.md
  podcasts/PCViewController.swift
Labels: [Type] Bug

#2489 Merge release/7.77.1 into release/7.78
  CHANGELOG.md
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/StoryShareableProvider.swift
  podcasts/Strings+Generated.swift
  podcasts/UpNext.xcassets/up-next-shuffle-sheet.imageset/Contents.json
  podcasts/UpNext.xcassets/up-next-shuffle-sheet.imageset/shuffle.svg
  podcasts/UpNextAnnouncementView.swift
  podcasts/Whats New/Announcements.swift
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#2488 Change episode status when playing from bookmark
  CHANGELOG.md
  podcasts/PlaybackManager.swift
Labels: [Type] Bug, [Project] Bookmarks

#2491 Ensure display and play of bookmarks from podcasts not synced
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  podcasts/Bookmarks/List/BookmarkRow.swift
  podcasts/Bookmarks/List/BookmarkRowViewModel.swift
  podcasts/PlaybackManager.swift
Labels: [Type] Bug
