Repository Automattic/pocket-casts-ios, pull requests merged in 2024-07, with the labels that each got.

#1874 Search: fix an issue when showing episodes
  CHANGELOG.md
  podcasts/EpisodeLoadingController.swift
Labels: Bug, Search Improvements

#1878 7.67 Release: Merge changes from 7.67.0.3 into `trunk`
  config/Version.xcconfig
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1887 Apply Figma color to stars matching Android
  podcasts/Ratings/StarRatingView.swift
Labels: Give Rating

#1888 7.68 Release: Merge changes from 7.68.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1889 [Give Rating] Display avg value and no rating label
  podcasts/PodcastHeadingTableCell.swift
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/StarRatingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Give Rating

#1875 Update CI to support Xcode 15.4
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  README.md
Labels: continuous integration, Xcode update

#1892 [Give Ratings] Apply restriction to rate and modify the rate star
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts/Constants.swift
  podcasts/Ratings/RatePodcastView.swift
  podcasts/Ratings/RatePodcastViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Give Rating

#1895 Reimagine Sharing: Add Clip sharing item
  podcasts/PlayerColorHelper.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/Strings+Generated.swift
  podcasts/Styles.swift
  podcasts/en.lproj/Localizable.strings
Labels: clip sharing, Reimagine Sharing

#1867 Transcripts: Style and scroll
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/TranscriptManager.swift
  podcasts/TranscriptModel.swift
  podcasts/TranscriptsViewController.swift
Labels: Transcripts

#1896 Reimagine Sharing: Add scrollable timeline view
  Modules/Utils/Sources/PocketCastsUtils/Extensions/ComparableExtension.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Common SwiftUI/ModalView.swift
  podcasts/Common SwiftUI/RoundedCorner.swift
  podcasts/Sharing/AudioWaveformView.swift
  podcasts/Sharing/Clip/MediaTrimBar.swift
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/Clip/PlayButton.swift
  podcasts/Sharing/Clip/PlayheadView.swift
  podcasts/Sharing/Clip/ScrollableScrollView.swift
  podcasts/Sharing/SharingView.swift
Labels: clip sharing, Reimagine Sharing

#1902 [Give Ratings] API implementation
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/UserPodcastRatingTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+UserPodcastRating.swift
  Modules/Server/Sources/PocketCastsServer/Public/Helpers/JSONDecodableURLTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/Ratings/PodcastRatingTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/RatePodcastView.swift
  podcasts/Ratings/RatePodcastViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Give Rating

#1903 Update PR template to include reference to the project
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling

#1900 Reimagine Sharing: Add trim handles for clip trimming
  podcasts.xcodeproj/project.pbxproj
  podcasts/Sharing/Clip/MediaTrimView.swift
  podcasts/Sharing/Clip/TrimHandle.swift
  podcasts/Sharing/Clip/TrimSelectionView.swift
Labels: clip sharing, Reimagine Sharing

#1899 Transcripts: add player transition to Transcripts
  podcasts/NowPlayingPlayerItemViewController+Update.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/NowPlayingPlayerItemViewController.xib
  podcasts/PlayPauseButton.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PlayerContainerViewController.xib
  podcasts/SkipButton.swift
Labels: Transcripts

#1905 [Give Rating] Add tracks events
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Ratings/RatePodcastView.swift
  podcasts/Ratings/RatePodcastViewModel.swift
  podcasts/Ratings/StarRatingView.swift
Labels: Give Rating

#1915 [Give Ratings] Present login screen if not logged in
  podcasts/PodcastViewController.swift
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Give Rating

#1918 Fix video/mp4 content type back for file handling
  podcasts/FileTypeUtil.swift
Labels: Bug

#1908 [Give Rating] Minimum played episode rate required
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts/Ratings/RatePodcastViewModel.swift
Labels: Give Rating

#1920 7.68 Release: Merge changes from 7.68.0.1 into `trunk`
  config/Version.xcconfig
  podcasts/FileTypeUtil.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1912 Reimagine Sharing: Clip Links
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Reimagine Sharing

#1923 7.69 Release: Merge changes from 7.69.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1924 Adds CHANGELOG entry for mp4 playback fix
  CHANGELOG.md
Labels: documentation

#1770 Add "Change Avatar" button to account settings
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AccountViewController+TableView.swift
  podcasts/AccountViewController.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/CommonImages.xcassets/settings-avatar.imageset/Contents.json
  podcasts/CommonImages.xcassets/settings-avatar.imageset/ProfileIcon@2x.png
  podcasts/CommonImages.xcassets/settings-avatar.imageset/ProfileIcon@3x.png
  podcasts/Constants.swift
  podcasts/GravatarSafariViewController.swift
  podcasts/Profile - SwiftUI/Common Views/ProfileImage.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement

#1928 Show Notes: force the request to be made if an episode is missing
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinator.swift
Labels: Bug

#1926 Add podcast_shared event when sharing via podcast page
  podcasts/PodcastViewController.swift
Labels: analytics

#1909 Transcripts: show transcripts through a shelf button
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/UI/GradientView.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Enumerations.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/NowPlayingPlayerItemViewController+Update.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/NowPlayingPlayerItemViewController.xib
  podcasts/PlayerContainerViewController+Update.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PlayerContainerViewController.xib
  podcasts/PlayerItemViewController.swift
  podcasts/PlayerTabsView.swift
  podcasts/ShelfActionsViewController+Table.swift
  podcasts/TranscriptShelfButton.swift
  podcasts/TranscriptsViewController.swift
Labels: Transcripts

#1870 Transcripts filter content
  PocketCastsTests/Tests/Player/Transcripts/ComposeFilterTests.swift
  PocketCastsTests/Tests/Player/Transcripts/TranscriptModelFilterTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/TranscriptFilter.swift
  podcasts/TranscriptModel.swift
  podcasts/TranscriptsViewController.swift
Labels: Transcripts

#1932 [Give Ratings] Add Give Rating into Changelog for 7.70
  CHANGELOG.md
Labels: Give Rating

#1929 7.69 Release: Merge changes from 7.69.0.1 into `trunk`
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
  config/Version.xcconfig
  podcasts/Episode Info Coordinator/ShowInfoCoordinator.swift
  podcasts/ca.lproj/Localizable.strings
Labels: Releases

#1934 Make "Pocket Casts Champion" tappable and display a message
  podcasts/AccountViewController+TableView.swift
  podcasts/AccountViewController.swift
  podcasts/Profile - SwiftUI/Account/AccountHeaderView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement

#1941 Transcripts: HTML transcripts content layout
  PocketCastsTests/Tests/Player/Transcripts/TranscriptModelFilterTests.swift
  podcasts/TranscriptFilter.swift
  podcasts/TranscriptModel.swift
Labels: Transcripts

#1944 Check for empty transcripts
  PocketCastsTests/Tests/Player/Transcripts/TranscriptModelFilterTests.swift
  podcasts/TranscriptManager.swift
  podcasts/TranscriptModel.swift
Labels: Transcripts

#1945 [Kids Profile] Add Kids Profile banner
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  PocketCastsTests/Tests/Kids Profile/KidsProfileBannerViewModelTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Kids Profile/KidsProfileBannerTableCell.swift
  podcasts/Kids Profile/KidsProfileBannerView.swift
  podcasts/Kids Profile/KidsProfileBannerViewModel.swift
  podcasts/KidsProfile.xcassets/Contents.json
  podcasts/KidsProfile.xcassets/kids-profile-banner-face.imageset/Contents.json
  podcasts/KidsProfile.xcassets/kids-profile-banner-face.imageset/kids-profile-banner-face.svg
  podcasts/KidsProfile.xcassets/kids-profile-view-face.imageset/Contents.json
  podcasts/KidsProfile.xcassets/kids-profile-view-face.imageset/kids-profile-view-face.svg
  podcasts/ProfileViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Kids profile

#1949 Transcripts: Refactor transcript manager
  PocketCastsTests/Tests/Player/Transcripts/TranscriptManagerTests.swift
  PocketCastsTests/Tests/Player/Transcripts/sample.vtt
  podcasts.xcodeproj/project.pbxproj
  podcasts/TranscriptManager.swift
  podcasts/TranscriptsViewController.swift
Labels: Transcripts

#1943 Fix scrolling drift on Podcasts list grid view
  CHANGELOG.md
  podcasts/GridHelper.swift
  podcasts/PCSearchBarController+Scrolling.swift
Labels: Bug

#1957 7.69 Release: Merge changes from 7.69.0.2 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/GridHelper.swift
  podcasts/PCSearchBarController+Scrolling.swift
  podcasts/sv.lproj/Localizable.strings
Labels: Releases

#1946 Champion: display a bottom sheet
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Profile - SwiftUI/Account/AccountHeaderView.swift
  podcasts/Profile - SwiftUI/Account/ChampionView.swift
  podcasts/Strings+Generated.swift
  podcasts/Subscription.xcassets/crown.imageset/Contents.json
  podcasts/Subscription.xcassets/crown.imageset/crown.svg
  podcasts/en.lproj/Localizable.strings
Labels: enhancement

#1961 Transcripts dynamic font support
  podcasts/TranscriptsViewController.swift
Labels: Transcripts

#1958 SPM updates
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies

#1962 Adds support for JSON PodcastIndex.org format
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/TranscriptModel.swift
Labels: Transcripts

#1960 [Kids Profile] Thank You screen
  podcasts.xcodeproj/project.pbxproj
  podcasts/Kids Profile/KidsProfileSheet.swift
  podcasts/Kids Profile/KidsProfileSheetHost.swift
  podcasts/Kids Profile/KidsProfileSheetViewModel.swift
  podcasts/Kids Profile/KidsProfileThankYouScreen.swift
  podcasts/KidsProfile.xcassets/kids-profile-view-face.imageset/kids-profile-view-face.svg
  podcasts/ProfileViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/Styles.swift
  podcasts/en.lproj/Localizable.strings
Labels: Kids profile

#1953 Transcripts: Search UI
  Modules/Utils/Sources/PocketCastsUtils/Extensions/UI/CustomTextView.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/TranscriptSearchAccessoryView.swift
  podcasts/TranscriptsViewController.swift
Labels: Transcripts

#1968 Attempt crash discovery
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts/CategoryPodcastsTable.swift
  podcasts/CategoryPodcastsViewController.xib
  podcasts/ThemeableTable.swift
Labels: Bug

#1970 Fix typo in Changelog
  CHANGELOG.md
Labels: Bug

#1963 Fix display of multi-select of UpNext when displaying from the the main tab bar
  CHANGELOG.md
  podcasts/UpNextViewController.swift
  podcasts/UpNextViewController.xib
Labels: Bug

#1972 7.69 Changelog updated
  CHANGELOG.md
Labels: Bug

#1971 7.69 Release: Merge changes from 7.69.0.3 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts/CategoryPodcastsTable.swift
  podcasts/CategoryPodcastsViewController.xib
  podcasts/ThemeableTable.swift
  podcasts/UpNextViewController.swift
  podcasts/UpNextViewController.xib
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1967 Add new protocol and method to sort by name and uuid
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Sorting/PodcastSorter.swift
  Modules/Utils/Sources/PocketCastsUtils/Sorting/Sortable.swift
  Modules/Utils/Tests/PocketCastsUtilsTests/PodcastSorterTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Folder+Sortable.swift
  podcasts/HomeGridDataHelper.swift
  podcasts/Podcast+Sortable.swift
Labels: Bug

#1955 Implement data retriever with cache
  Modules/Server/Sources/PocketCastsServer/Public/Helpers/URLRequest+RefreshIfNeeded.swift
  PocketCastsTests/Tests/Playback/Chapters/ChapterManagerTests.swift
  PocketCastsTests/Tests/Player/Transcripts/TranscriptManagerTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Episode Info Coordinator/ShowInfoCoordinating.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinator.swift
  podcasts/Episode+Transcript.swift
  podcasts/ShowNotesUpdater.swift
  podcasts/TranscriptFormat.swift
  podcasts/TranscriptManager.swift
  podcasts/TranscriptModel.swift
  podcasts/TranscriptsDataRetriever.swift
Labels: Transcripts

#1966 [Kids Profile] Submit Feedback screen
  podcasts.xcodeproj/project.pbxproj
  podcasts/Kids Profile/KidsProfileSheet.swift
  podcasts/Kids Profile/KidsProfileSheetHost.swift
  podcasts/Kids Profile/KidsProfileSheetViewModel.swift
  podcasts/Kids Profile/KidsProfileSubmitScreen.swift
  podcasts/Kids Profile/KidsProfileThankYouScreen.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Kids profile
