Repository Automattic/pocket-casts-ios, pull requests merged in 2024-06, with the labels that each got.

#1798 Folders: add history and the option to restore
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/FolderHistoryManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+ServerChanges.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Folder History/FolderHistoryEntryView.swift
  podcasts/Folder History/FolderHistoryModel.swift
  podcasts/Folder History/FolderHistoryView.swift
  podcasts/Folder History/FolderHistoryViewController.swift
  podcasts/FolderPreviewView.swift
  podcasts/SettingsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement, folders, sync

#1796 Categories: Animation Tweaks
  podcasts/Categories/CategoriesSelectorView.swift
Labels: Categories Redesign

#1802 Fix missing DBTestCase
  podcasts.xcodeproj/project.pbxproj
Labels: Testing

#1769 Add automation and configuration for Prototype Builds
  Pocket Casts Watch App/Info.plist
  PodcastsIntents/PodcastsIntents.prototype.entitlements
  Share Extension/Share Extension.prototype.entitlements
  WidgetExtension/WidgetExtension.prototype.entitlements
  config/PocketCasts.base.xcconfig
  config/PocketCasts.debug.xcconfig
  config/PocketCasts.prototype.xcconfig
  config/PocketCasts.release.xcconfig
  config/PocketCasts.staging.xcconfig
  fastlane/Fastfile
  fastlane/lib/helpers.rb
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts Prototype Build.xcscheme
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts Staging.xcscheme
  podcasts/DeveloperMenu.swift
  podcasts/podcasts.prototype.entitlements
Labels: tooling

#1803 Switching tabs position to center Discover
  podcasts/MainTabBarController.swift
Labels: Up Next, UI Related, Discover

#1664 Developer: Database Export/Import file
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/DeveloperMenu.swift
  podcasts/PCBundleDoc.swift
  podcasts/podcasts-Info.plist
Labels: enhancement

#1804 Upgrade release toolkit from version 9.4.0 to latest, 11.0.2
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: tooling

#1805 Chapter Manager: add logs
  podcasts/ChapterManager.swift
Labels: Bug

#1806 Fix up next navigation items
  podcasts/UpNextViewController+Table.swift
  podcasts/UpNextViewController.swift
Labels: Bug, Up Next

#1809 Sleep Timer: ensure sleep timer is restarted due to shake only if sleep timer and the option is active
  podcasts/Settings.swift
  podcasts/SleepTimerManager.swift
Labels: enhancement

#1801 Playback: only update podcast if episode playback fails
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/DefaultPlayer.swift
  podcasts/PlaybackActionHelper.swift
  podcasts/PlaybackManager.swift
Labels: enhancement, playback

#1811 7.65 Release: Merge changes from 7.65.0.2 into `trunk`
  config/Version.xcconfig
  podcasts/ChapterManager.swift
  podcasts/MainTabBarController.swift
  podcasts/Settings.swift
  podcasts/SleepTimerManager.swift
  podcasts/UpNextViewController+Table.swift
  podcasts/UpNextViewController.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1812 Developer: Write the pcasts bundle on db export
  podcasts/DatabaseExport.swift
  podcasts/PCBundleDoc.swift
Labels: tooling

#1815 7.65 Release: Merge changes from 7.65.0.3 into `trunk`
  config/Version.xcconfig
Labels: Releases

#1818 7.66 Release: Merge changes from 7.66.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1816 Handle errors from token Keychain access
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ApiBaseTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/TokenHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+SocialAuth.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/BackgroundSyncManager.swift
  Modules/Utils/Sources/PocketCastsUtils/General/KeychainHelper.swift
  Pocket Casts Watch App/WatchSyncManager.swift
  podcasts/AuthenticationHelper.swift
  podcasts/WatchManager.swift
Labels: Bug

#1817 Fix Episode detail view on iPad
  podcasts/EpisodeDetailViewController.xib
Labels: Bug, iPad

#1771 Prototype Builds
  .buildkite/commands/build.sh
  .buildkite/commands/prototype-build.sh
  .buildkite/commands/prototype-upload.sh
  .buildkite/pipeline.yml
  .gitignore
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  fastlane/Fastfile
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: tooling

#1821 Accelerate Effects
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  PocketCastsTests/Tests/Playback/Effects/AudioUtilsTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AudioReadTask.swift
  podcasts/AudioUtils.swift
Labels: Performance

#1823 New grid tweaks
  CHANGELOG.md
  podcasts/GridBadgeView.swift
  podcasts/GridHelper.swift
  podcasts/PodcastGridCell.xib
  podcasts/PodcastListViewController.swift
Labels: Podcast grid layout

#1800 Refactor WatchOS source interface
  CHANGELOG.md
  Pocket Casts Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  Pocket Casts Watch App/Base.lproj/Interface.storyboard
  Pocket Casts Watch App/DownloadListView.swift
  Pocket Casts Watch App/DownloadListViewModel.swift
  Pocket Casts Watch App/ExtensionDelegate.swift
  Pocket Casts Watch App/FilesListView.swift
  Pocket Casts Watch App/FilesListViewModel.swift
  Pocket Casts Watch App/FilterEpisodeListViewModel.swift
  Pocket Casts Watch App/FiltersListView.swift
  Pocket Casts Watch App/FiltersListViewModel.swift
  Pocket Casts Watch App/InterfaceView.swift
  Pocket Casts Watch App/NavigationManager.swift
  Pocket Casts Watch App/NotificationController.swift
  Pocket Casts Watch App/PCInterfaceController.swift
  Pocket Casts Watch App/PocketCastsApp.swift
  Pocket Casts Watch App/PodcastsListView.swift
  Pocket Casts Watch App/Publishers.swift
  Pocket Casts Watch App/PushNotificationPayload.apns
  Pocket Casts Watch App/SessionManager.swift
  Pocket Casts Watch App/SourceInterfaceController.swift
  Pocket Casts Watch App/SourceInterfaceModel.swift
  Pocket Casts Watch App/SourceInterfaceNavigationView.swift
  Pocket Casts Watch App/UpNextView.swift
  Pocket Casts Watch App/UpNextViewModel.swift
  Pocket Casts Watch App/WatchHostingController.swift
  Pocket Casts Watch App/WatchInterfaceType.swift
  Pocket Casts Watch App/WatchSyncManager.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Strings+Generated.swift
  podcasts/WatchConstants.swift
  podcasts/en.lproj/Localizable.strings
Labels: watchOS

#1813 Developer: Network Debugging
  Modules/DataModel/Package.swift
  Modules/Server/Package.swift
  Modules/Utils/Package.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileLog.swift
  Podfile
  Podfile.lock
  podcasts.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/AppDelegate.swift
  podcasts/DatabaseExport.swift
  podcasts/DeveloperMenu.swift
Labels: tooling

#1643 Reimagine Sharing: Add `newSharing` feature flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Reimagine Sharing

#1819 AVExportSession - Update status of download correctly
  CHANGELOG.md
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/DownloadManager.swift
  podcasts/DownloadProgress.swift
  podcasts/DownloadProgressManager.swift
  podcasts/EpisodeCell.xib
  podcasts/MediaExporter.swift
  podcasts/PlaybackQueue.swift
Labels: playback

#1833 EffectsPlayer: remove different setup mechanisms
  podcasts/Constants.swift
  podcasts/EffectsPlayer.swift
  podcasts/FirebaseManager.swift
  podcasts/Settings.swift
Labels: enhancement

#1832 Fix background gradient on the mini-player
  CHANGELOG.md
  podcasts/MiniPlayerViewController.swift
Labels: Bug

#1836 Xcode 16.0 Beta 1: update project
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/MainTabBarController.swift
Labels: tooling

#1650 Reimagine Sharing: Add new Modal with sharing options
  podcasts.xcodeproj/project.pbxproj
  podcasts/Common SwiftUI/ModalView.swift
  podcasts/ModalCloseButton.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/OptionsPicker.swift
  podcasts/OptionsPickerRootController.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/SharingHelper.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Reimagine Sharing

#1837 Tracks: fix Up Next event
  podcasts/UpNextViewController.swift
Labels: analytics

#1839 7.66 Release: Merge changes from 7.66.0.2 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/GridBadgeView.swift
  podcasts/GridHelper.swift
  podcasts/MiniPlayerViewController.swift
  podcasts/PodcastGridCell.xib
  podcasts/PodcastListViewController.swift
  podcasts/UpNextViewController.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1835 New icon for prototype builds
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppIcon.xcassets/AppIconPrototype.appiconset/AppIcon-Electric-Blue.png
  podcasts/AppIcon.xcassets/AppIconPrototype.appiconset/Contents.json
Labels: tooling

#1838 Attach Up Next bottom to superview
  podcasts/UpNextViewController.xib
Labels: enhancement

#1841 Increase number of lines of labels for author and title
  podcasts/DiscoverFeaturedView.xib
Labels: Bug, UI Related

#1840 Reimagine Sharing: Add new sharing UI with shareable image preview
  podcasts.xcodeproj/project.pbxproj
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/Sharing/PocketCastsLogoPill.swift
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/SharingHelper.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Reimagine Sharing

#1850 Fix crash in Up Next when import file
  podcasts/UpNextViewController.swift
Labels: crash

#1845 7.66 Release: Merge changes from 7.66.0.3 into `trunk`
  config/Version.xcconfig
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
Labels: Releases

#1844 Deeplink: increase the time when waiting for a recent added podcast
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/PodcastSearchOperation.swift
  Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
Labels: enhancement

#1851 Add feature flag for transcripts
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Transcripts

#1854 Rename feature flag for control Stream and Cache solution
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/DownloadManager.swift
  podcasts/PlaybackManager.swift
  podcasts/PlaybackQueue.swift
Labels: playback

#1847 Reimagine Sharing: Add new sharing to Episode detail page
  podcasts/EpisodeDetailViewController.swift
  podcasts/Sharing/SharingModal.swift
Labels: Reimagine Sharing

#1849 Reimagine Sharing: Add basic sharing destinations
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/StoryShareableProvider.swift
  podcasts/End of Year/Views/View+Snapshot.swift
  podcasts/Sharing.xcassets/Contents.json
  podcasts/Sharing.xcassets/pocketcasts.imageset/Contents.json
  podcasts/Sharing.xcassets/pocketcasts.imageset/pocketcasts.pdf
  podcasts/Sharing/ShareDestination.swift
  podcasts/Sharing/ShareImageView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Reimagine Sharing

#1858 7.67 Release: Merge changes from 7.67.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1852 Transcripts add network parse code
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  PocketCastsTests/Tests/Playback/Chapters/ChapterManagerTests.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinating.swift
  podcasts/Episode Info Coordinator/ShowInfoCoordinator.swift
  podcasts/PlaybackManager.swift
  podcasts/ShowNotesUpdater.swift
Labels: Transcripts

#1855 Listening Speed: support up to 5x
  CHANGELOG.md
  podcasts/PlaybackManager.swift
  podcasts/PodcastEffectsViewController+Table.swift
Labels: enhancement

#1856 Discover Categories: Add category name + region to tapped & subscribe events
  podcasts/AnalyticsHelper.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
  podcasts/CategorySummaryViewController.swift
  podcasts/CollectionSummaryViewController.swift
  podcasts/CountrySummaryViewController.swift
  podcasts/DiscoverSummaryProtocol.swift
  podcasts/DiscoverViewController+CategoryRedesign.swift
  podcasts/DiscoverViewController.swift
  podcasts/FeaturedSummaryViewController.swift
  podcasts/LargeListSummaryViewController.swift
  podcasts/NetworkSummaryViewController.swift
  podcasts/SingleEpisodeViewController.swift
  podcasts/SinglePodcastViewController.swift
  podcasts/SmallPagedListSummaryViewController.swift
Labels: analytics, Categories Redesign

#1853 Transcripts add temporary player item to see transcripts
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts Staging.xcscheme
  podcasts/PlayerContainerViewController+Update.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PlayerTabsView.swift
  podcasts/Strings+Generated.swift
  podcasts/TranscriptsViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: Transcripts

#1863 7.67 Release: Merge changes from 7.67.0.1 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/AnalyticsHelper.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
  podcasts/CategorySummaryViewController.swift
  podcasts/CollectionSummaryViewController.swift
  podcasts/CountrySummaryViewController.swift
  podcasts/DiscoverSummaryProtocol.swift
  podcasts/DiscoverViewController+CategoryRedesign.swift
  podcasts/DiscoverViewController.swift
  podcasts/FeaturedSummaryViewController.swift
  podcasts/LargeListSummaryViewController.swift
  podcasts/NetworkSummaryViewController.swift
  podcasts/PlaybackManager.swift
  podcasts/PodcastEffectsViewController+Table.swift
  podcasts/SingleEpisodeViewController.swift
  podcasts/SinglePodcastViewController.swift
  podcasts/SmallPagedListSummaryViewController.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1864 Update CHANGELOG.md to include Widgets redesign
  CHANGELOG.md
Labels: documentation

#1859 Transcripts add parsing subtitles library
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/Constants.swift
  podcasts/PlaybackManager.swift
  podcasts/PlayerContainerViewController+Update.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/TranscriptManager.swift
  podcasts/TranscriptsViewController.swift
Labels: Transcripts

#1862 Release: revert branch protection to the old code
  fastlane/Fastfile
Labels: Releases

#1861 Add events for support email & feedback to match Android
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AnalyticsHelper.swift
Labels: analytics

#1868 Sleep Timer: add logs to debug issues with auto restart
  podcasts/PlaybackManager.swift
  podcasts/SleepTimerManager.swift
Labels: Sleep Timer

#1871 7.67 Release: Merge changes from 7.67.0.2 into `trunk`
  config/Version.xcconfig
  podcasts/PlaybackManager.swift
  podcasts/SleepTimerManager.swift
  podcasts/ca.lproj/Localizable.strings
Labels: Releases
