Repository Automattic/pocket-casts-ios, pull requests merged in 2024-01, with the labels that each got.

#1323 Now Playing Scrubber Accessibility
  CHANGELOG.md
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/NowPlayingPlayerItemViewController.xib
  podcasts/Strings+Generated.swift
  podcasts/TimeSlider.swift
  podcasts/en.lproj/Localizable.strings
Labels: accessibility

#1167 Enable test coverage for pocketcasts target
  PocketCastsTests/UnitTests.xctestplan
Labels: enhancement

#1309 Playback 2023: disable it
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/Stories/DynamicBackgroundView.swift
  podcasts/EndOfYear.xcassets/2022_big.imageset/2022_big@3x.png
  podcasts/EndOfYear.xcassets/2022_big.imageset/Contents.json
  podcasts/EndOfYear.xcassets/2022_small.imageset/2022_small@3x.png
  podcasts/EndOfYear.xcassets/2022_small.imageset/Contents.json
  podcasts/EndOfYear.xcassets/bottom_blob.imageset/Contents.json
  podcasts/EndOfYear.xcassets/bottom_blob.imageset/bottom_blob@3x.png
  podcasts/EndOfYear.xcassets/modal_background.imageset/Contents.json
  podcasts/EndOfYear.xcassets/modal_background.imageset/modal_background@3x.png
  podcasts/EndOfYear.xcassets/square_perspective.imageset/Contents.json
  podcasts/EndOfYear.xcassets/square_perspective.imageset/square_perspective@3x.png
  podcasts/EndOfYear.xcassets/top_blob.imageset/Contents.json
  podcasts/EndOfYear.xcassets/top_blob.imageset/top_blob@3x.png
  podcasts/FeatureFlag.swift
Labels: Playback 2023

#1324 7.54 Release: Merge changes from 7.54.0.5 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/Stories/DynamicBackgroundView.swift
  podcasts/EndOfYear.xcassets/2022_big.imageset/2022_big@3x.png
  podcasts/EndOfYear.xcassets/2022_big.imageset/Contents.json
  podcasts/EndOfYear.xcassets/2022_small.imageset/2022_small@3x.png
  podcasts/EndOfYear.xcassets/2022_small.imageset/Contents.json
  podcasts/EndOfYear.xcassets/bottom_blob.imageset/Contents.json
  podcasts/EndOfYear.xcassets/bottom_blob.imageset/bottom_blob@3x.png
  podcasts/EndOfYear.xcassets/modal_background.imageset/Contents.json
  podcasts/EndOfYear.xcassets/modal_background.imageset/modal_background@3x.png
  podcasts/EndOfYear.xcassets/square_perspective.imageset/Contents.json
  podcasts/EndOfYear.xcassets/square_perspective.imageset/square_perspective@3x.png
  podcasts/EndOfYear.xcassets/top_blob.imageset/Contents.json
  podcasts/EndOfYear.xcassets/top_blob.imageset/top_blob@3x.png
  podcasts/FeatureFlag.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/NowPlayingPlayerItemViewController.xib
  podcasts/Strings+Generated.swift
  podcasts/TimeSlider.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1321 Cleanup: remove patron feature flag.
  podcasts/AccountViewController.swift
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/FeatureFlag.swift
  podcasts/IapHelper.swift
  podcasts/IconSelectorCell.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Settings.swift
  podcasts/SettingsViewController.swift
Labels: Patron

#1325 Cleanup: remove bookmarks feature flag
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+ServerChanges.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask.swift
  Modules/Server/Tests/PocketCastsServerTests/SyncTaskTests+BookmarkImport.swift
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/Enumerations.swift
  podcasts/EpisodeCell.swift
  podcasts/EpisodeDetailViewController.swift
  podcasts/FeatureFlag.swift
  podcasts/HeadphoneSettingsViewController.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/PlaybackManager.swift
  podcasts/PlayerContainerViewController+Update.swift
  podcasts/PlayerTabsView.swift
  podcasts/PodcastHeadingTableCell.swift
  podcasts/Settings.swift
  podcasts/ShelfActionsViewController.swift
  podcasts/UserEpisodeDetailViewController+Table.swift
Labels: Bookmarks

#1327 7.54 Release: Merge changes from 7.54.0.6 into `trunk`
  config/Version.xcconfig
  fastlane/Fastfile
Labels: Releases

#1332 CarPlay Star button
  CHANGELOG.md
  podcasts/CarPlaySceneDelegate.swift
Labels: CarPlay

#1334 Fix typos - CI PR
  Pocket Casts Watch App Extension/SortOption.swift
  Pocket Casts Watch App Extension/String+prefixSourceUnicode.swift
  Pocket Casts Watch App Extension/WatchImageHelper.swift
  PocketCastsTests/Extensions/XCTestCase+eventually.swift
  podcasts/AEXML.swift
  podcasts/AVFileUtil.swift
  podcasts/AddCustomViewController.swift
  podcasts/Analytics/Adapters/Tracks/TracksSubscriptionData.swift
  podcasts/AppPlayEpisodeIntentExtension.swift
  podcasts/AudioPlayTask.swift
  podcasts/Common SwiftUI/List View/SearchableListViewModel.swift
  podcasts/ImageManager.swift
  podcasts/LocalizationHelpers.swift
  podcasts/MiniPlayerToFullPlayerAnimator.swift
  podcasts/PCHostingController.swift
  podcasts/PodcastViewController.swift
  podcasts/SwiftUI/HorizontalCarousel.swift
  podcasts/UpNextViewController+Table.swift
  podcasts/en.lproj/Localizable.strings
Labels: continuous integration

#1330 Fix: Update list views to use List
  CHANGELOG.md
  Pocket Casts Watch App Extension/DownloadListView.swift
  Pocket Casts Watch App Extension/EpisodeListView.swift
  Pocket Casts Watch App Extension/EpisodeRow.swift
  Pocket Casts Watch App Extension/FilesListView.swift
  Pocket Casts Watch App Extension/FilterEpisodeListView.swift
  Pocket Casts Watch App Extension/PodcastEpisodeListView.swift
  podcasts.xcodeproj/project.pbxproj
Labels: Bug, watchOS

#1310 Player: add a spring animation when dismissing
  podcasts/MiniPlayerToFullPlayerAnimator.swift
  podcasts/MiniPlayerViewController+TransitionDelegate.swift
  podcasts/MiniPlayerViewController.xib
  podcasts/PlayerContainerViewController+Gestures.swift
  podcasts/PlayerContainerViewController.swift
Labels: enhancement, Player

#1336 7.55 Release: Merge changes from 7.55.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1333 Navigates to podcast view when tapping on podcast name on Player.
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/NowPlayingPlayerItemViewController.xib
  podcasts/PlaybackManager.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PlayerItemViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: UX

#1337 Fix CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#1342 Plus upgrade mention Bookmarks alongside Folders
  podcasts.xcodeproj/project.pbxproj
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusLabel.swift
  podcasts/Onboarding/Plus/PlusLandingView.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/PlusDetailsViewController.swift
  podcasts/PlusDetailsViewController.xib
  podcasts/PlusFeaturesView.swift
  podcasts/PlusFeaturesView.xib
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Plus

#1344 Remove code coverage
  PocketCastsTests/UnitTests.xctestplan
Labels: tooling

#1347 Move Upgrade Card features under badge + free trial
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
Labels: Plus

#1350 Player transition: another attempt on fixing freezing issues
  podcasts/MiniPlayerToFullPlayerAnimator.swift
Labels: Bug

#1349 Fix tap on tab bar to display search
  podcasts/DiscoverViewController.swift
  podcasts/PodcastListViewController.swift
Labels: Bug, Discover

#1353 7.55 Release: Merge changes from 7.55.0.1 into `trunk`
  config/Version.xcconfig
  podcasts/DiscoverViewController.swift
  podcasts/MiniPlayerToFullPlayerAnimator.swift
  podcasts/PodcastListViewController.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1355 Player transition: fix UI freeze when Open Player Automatically is enabled
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/SceneHelper.swift
  podcasts/UIViewController+Presenting.swift
Labels: Bug

#1358 7.55 Release: Merge changes from 7.55.0.2 into `trunk`
  config/Version.xcconfig
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/SceneHelper.swift
  podcasts/UIViewController+Presenting.swift
Labels: Releases

#1356 Fix episode artwork showing behind the video player
  podcasts/MiniPlayerToFullPlayerAnimator.swift
Labels: Bug

#1363 7.55 Release: Merge changes from 7.55.0.3 into `trunk`
  config/Version.xcconfig
  podcasts/MiniPlayerToFullPlayerAnimator.swift
Labels: Releases

#1365 7.56 Release: Merge changes from 7.56.0.0 into `trunk`
  CHANGELOG.md
  Podfile.lock
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1326 Move Danger to GitHub Actions
  .buildkite/commands/danger-pr-check.sh
  .buildkite/commands/run-swiftlint.sh
  .buildkite/pipeline.yml
  .github/workflows/run-danger.yml
  Dangerfile
Labels: tooling

#1362 Subscription trial offer 50% off
  CHANGELOG.md
  Pocket Casts Configuration.storekit
  podcasts.xcodeproj/project.pbxproj
  podcasts/AnalyticsHelper.swift
  podcasts/Common SwiftUI/BookmarksLockedStateView.swift
  podcasts/Constants.swift
  podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
  podcasts/IapHelper.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/PlusPurchaseModal.swift
  podcasts/Onboarding/Plus/SubscriptionPriceAndOfferView.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Plus, Patron

#1367 [Library update] Lottie
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/BasePlayPauseButton.swift
  podcasts/NowPlayingAnimationView.swift
  podcasts/PlayPauseButton.swift
  podcasts/PlayPauseLabeledButton.swift
  podcasts/SkipButton.swift
  podcasts/SleepTimerButton.swift
Labels: dependencies

#1368 [Library Update] FMDB
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies

#1369 [Library Update] Firebase
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/pocketcasts.xcscheme
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies

#1351 Only log out user with auth errors
  Modules/Server/Sources/PocketCastsServer/Private/TokenHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+Account.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+SocialAuth.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ErrorResponse.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerConfig.swift
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/FeatureFlag.swift
  podcasts/Server+Strings.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Accounts

#1374 [Library Update] Agrume
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/ImageManager.swift
Labels: dependencies

#1370 Refactor IAP related code
  PocketCastsTests/Tests/IAP/IAPHelperTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AnalyticsHelper.swift
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/IAPHelper.swift
  podcasts/IAPTypes.swift
  podcasts/IconSelectorCell.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/PlusButtonStyles.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/PlusPurchaseModal.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
Labels: refactoring, Refactor

#1375 [Library Update] Kingfisher
  Podfile
  Podfile.lock
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies

#1377 Mocked URLConnection
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ApiBaseTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/TokenHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/Cache/CacheServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/MainServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/URLConnection.swift
  PocketCastsTests/Mocks/MockURLHandler.swift
  PocketCastsTests/Tests/Utilities/TokenHelperTests.swift
  podcasts.xcodeproj/project.pbxproj
Labels: refactoring

#1376 [Library Update] SwiftyJSON
  Modules/Server/Package.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+Account.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/MainServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  Modules/Server/Tests/Fixtures/refresh-response.json
  Modules/Server/Tests/PocketCastsServerTests/ServerHelperTests.swift
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies

#1386 Increase IAP helper tests timeouts
  PocketCastsTests/Tests/IAP/IAPHelperTests.swift
Labels: Bug

#1130 Ratings: add the structure for the give rating screen
  podcasts.xcodeproj/project.pbxproj
  podcasts/Beta/BetaMenu.swift
  podcasts/FeatureFlag.swift
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/RatePodcastView.swift
  podcasts/Ratings/RatePodcastViewModel.swift
  podcasts/Ratings/StarRatingView.swift
Labels: enhancement

#1131 Ratings: add screens design
  podcasts/HapticsHelper.swift
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastViewController.swift
  podcasts/Podcasts.xcassets/star-full.imageset/Contents.json
  podcasts/Podcasts.xcassets/star-full.imageset/full-star@2x.png
  podcasts/Podcasts.xcassets/star-full.imageset/full-star@3x.png
  podcasts/Podcasts.xcassets/star-half.imageset/Contents.json
  podcasts/Podcasts.xcassets/star-half.imageset/half-star@3x.png
  podcasts/Podcasts.xcassets/star.imageset/Contents.json
  podcasts/Podcasts.xcassets/star.imageset/star@2x.png
  podcasts/Podcasts.xcassets/star.imageset/star@3x.png
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/RatePodcastView.swift
  podcasts/Ratings/RatePodcastViewModel.swift
  podcasts/Ratings/StarRatingView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement

#1185 Ratings: adjustments
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastViewController.swift
  podcasts/Ratings/RatePodcastView.swift
  podcasts/Ratings/StarRatingView.swift
  podcasts/Strings+Generated.swift
  podcasts/SubscribeButton.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement
