Repository Automattic/pocket-casts-ios, pull requests merged in 2024-04, with the labels that each got.

#1580 Settings Sync: Use wrapped startFrom & skipLast values
  podcasts/PodcastSettingsViewController+Table.swift
Labels: settings

#1546 Settings Sync: Settings Unification
  podcasts/GeneralSettingsViewController.swift
  podcasts/MiniPlayerViewController.swift
  podcasts/PlaybackCatchUpHelper.swift
  podcasts/PlaybackManager.swift
  podcasts/Settings.swift
Labels: settings, continuous integration

#1582 Standard Tags: fixes issues with episode artwork
  podcasts/ImageManager.swift
  podcasts/PodcastImageView.swift
  podcasts/UpNextViewController.swift
Labels: Bug, Standard Tags

#1583 [Library Update] Google Sign In
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/Login/GoogleSocialLogin.swift
Labels: dependencies

#1584 [Library Update] Firebase
  podcasts.xcodeproj/project.pbxproj
Labels: dependencies

#1585 Add developer option to clear caches
  podcasts/DeveloperMenu.swift
  podcasts/ImageManager.swift
Labels: enhancement

#1586 7.61 Release: Merge changes from 7.61.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1588 [Deselect Chapters] Remove it from Patron and update copies
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: enhancement

#1591 7.60.1 Release: Merge changes from 7.60.1.0 into `trunk`
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#1589 Fix warnings in unit tests
  Modules/DataModel/Tests/PocketCastsDataModelTests/AutoAddCandidatesDataManagerTests.swift
  Modules/Server/Tests/PocketCastsServerTests/ApiSettingsTests+ModifiedDate.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
Labels: Testing

#1587 Settings Sync: Default Settings handling
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/PodcastSettings.swift
  Modules/Server/Sources/PocketCastsServer/Public/AppSettings.swift
  PocketCastsTests/Tests/Utilities/PodcastSettings+ImportUserDefaultsTests.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
Labels: settings

#1590 Enable `settingsSync` and `newSettingsStorage` flags
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: settings

#1593 Merge 7.60.1 into 7.61
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#1594 Disable performance tests for AutoAddCandidatesDataManager
  PocketCastsTests/UnitTests.xctestplan
Labels: Testing

#1592 Standard Tags: change the solution so it uses less resources
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/BaseEpisode.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/UserEpisode.swift
  podcasts/DeveloperMenu.swift
  podcasts/EpisodeDetailViewController+ShowNotes.swift
  podcasts/ImageManager.swift
  podcasts/PodcastImageView.swift
  podcasts/ShowInfoCoordinator.swift
  podcasts/ShowNotesPlayerItemViewController.swift
Labels: enhancement, Standard Tags

#1596 [Standard Tags] Cancel loading previous images to avoid unnecessary CPU/Network usage
  podcasts/ImageManager.swift
  podcasts/PodcastImageView.swift
Labels: enhancement, Standard Tags

#1601 Settings Sync: Only execute podcast cache at end of import
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  PocketCastsTests/Tests/Utilities/PodcastSettings+ImportUserDefaultsTests.swift
  PocketCastsTests/UnitTests.xctestplan
  podcasts/DataManager+Import.swift
Labels: settings

#1603 7.61 Release: Merge changes from 7.61.0.3 into `trunk`
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  PocketCastsTests/Tests/Utilities/PodcastSettings+ImportUserDefaultsTests.swift
  PocketCastsTests/UnitTests.xctestplan
  config/Version.xcconfig
  podcasts/DataManager+Import.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1602 Categories Redesign: Pills
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Categories/CategoriesSelectorView.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
  podcasts/Categories/CategoryButtonStyle.swift
  podcasts/DiscoverViewController.swift
Labels: Categories Redesign

#1606 Standard Tags: ensure metadata is updated when it needs to do so
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
Labels: Bug, Standard Tags

#1607 Deselect Chapters: enable for Plus users and general public announcement
  podcasts/PaidFeature.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/DeselectChaptersAnnouncementViewModel.swift
Labels: Deselecting Chapters

#1608 Standard Tags: fix artwork pulsing/blinking
  podcasts/EpisodeDetailViewController+ShowNotes.swift
  podcasts/PodcastImageView.swift
Labels: Standard Tags

#1609 7.61 Release: Merge changes from 7.61.0.4 into `trunk`
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
  config/Version.xcconfig
  podcasts/EpisodeDetailViewController+ShowNotes.swift
  podcasts/PaidFeature.swift
  podcasts/PodcastImageView.swift
  podcasts/Whats New/Announcements.swift
  podcasts/Whats New/DeselectChaptersAnnouncementViewModel.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
Labels: Releases

#1610 Fix renamed observable in CategoriesSelectorView
  podcasts/Categories/CategoriesSelectorView.swift
Labels: Bug

#1605 Categories Redesign: Modal picker
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  Modules/Utils/Sources/PocketCastsUtils/Extensions/UI/View+Modify.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Categories/CategoriesModalPicker.swift
  podcasts/Categories/CategoriesSelectorView.swift
Labels: Categories Redesign

#1617 7.61 Release: Merge changes from 7.61.0.5 into `trunk`
  config/Version.xcconfig
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1614 Categories: Sponsored Posts
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  podcasts/DiscoverViewController.swift
Labels: Categories Redesign

#1612 Sleep Timer: automatically restart if playback is resumed within 5 minutes
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Constants.swift
  podcasts/PlaybackManager.swift
  podcasts/Settings.swift
  podcasts/SleepTimerManager.swift
  podcasts/SleepTimerViewController.swift
Labels: Sleep Timer

#1611 Categories: Pills styling
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  podcasts/Categories/CategoriesSelectorView.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
  podcasts/Categories/CategoryButtonStyle.swift
Labels: Categories Redesign

#1623 7.62 Release: Merge changes from 7.62.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/Resources/release_notes.txt
Labels: Releases

#1618 Convert bookmark sort options from server to local sort option
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  podcasts/Enumerations.swift
  podcasts/Settings.swift
Labels: settings, sync, Bookmarks

#1613 UpNext on tab bar
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AnalyticsHelper.swift
  podcasts/CommonImages.xcassets/profile-placeholder.imageset/Contents.json
  podcasts/CommonImages.xcassets/profile-placeholder.imageset/profile.pdf
  podcasts/MainTabBarController.swift
  podcasts/NowPlayingAnimationView.swift
  podcasts/PCViewController.swift
  podcasts/PodcastListViewController.swift
  podcasts/TabBar.xcassets/Contents.json
  podcasts/TabBar.xcassets/upnext_tab.imageset/Contents.json
  podcasts/TabBar.xcassets/upnext_tab.imageset/upnext.pdf
  podcasts/UpNextNowPlayingCell.swift
  podcasts/UpNextViewController.swift
Labels: Up Next

#1620 Animation + style tweaks on Discover Categories
  podcasts/Categories/CategoriesSelectorView.swift
  podcasts/Categories/CategoryButtonStyle.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/DiscoverViewController.swift
  podcasts/SinglePodcastViewController.swift
Labels: Categories Redesign

#1621 Enable the Categories Redesign feature for 7.62
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Categories Redesign

#1622 Tweak tracks event properties for Categories Redesign
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AnalyticsHelper.swift
  podcasts/CategoryPodcastsViewController.swift
  podcasts/CategorySummaryViewController.swift
  podcasts/DeveloperMenu.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/DiscoverViewController.swift
  podcasts/PodcastViewController.swift
  podcasts/SinglePodcastViewController.swift
Labels: Categories Redesign

#1626 Add Most Popular section to Discover Categories page
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Categories/CategoryButtonStyle.swift
  podcasts/CategoryPodcastsViewController.swift
  podcasts/DiscoverViewController+CategoryRedesign.swift
  podcasts/DiscoverViewController.swift
  podcasts/LargeListSummaryViewController.swift
  podcasts/LargeListSummaryViewController.xib
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Categories Redesign

#1627 Sleep Timer Improvements: shake device to restart sleep timer
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts/MainTabBarController.swift
  podcasts/PlaybackManager.swift
  podcasts/SleepTimerManager.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  podcasts/sleep-timer-restarted-sound.mp3
Labels: Sleep Timer

#1629 Sleep Timer Improvements: fade out 5s before pausing playback
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts/DefaultPlayer.swift
  podcasts/EffectsPlayer.swift
  podcasts/FadeOutManager.swift
  podcasts/GoogleCastPlayer.swift
  podcasts/PlaybackManager.swift
  podcasts/PlaybackProtocol.swift
  podcasts/SleepTimerManager.swift
Labels: Sleep Timer

#1631 Categories: Regions Fix
  podcasts/DiscoverViewController.swift
Labels: Categories Redesign

#1632 7.62 Release: Merge changes from 7.62.0.1 into `trunk`
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AnalyticsHelper.swift
  podcasts/Categories/CategoriesSelectorView.swift
  podcasts/Categories/CategoryButtonStyle.swift
  podcasts/CategoryPodcastsViewController.swift
  podcasts/CategorySummaryViewController.swift
  podcasts/DeveloperMenu.swift
  podcasts/DiscoverViewController+CategoryRedesign.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/DiscoverViewController.swift
  podcasts/LargeListSummaryViewController.swift
  podcasts/LargeListSummaryViewController.xib
  podcasts/PodcastViewController.swift
  podcasts/SinglePodcastViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#1635 Standard Tags: fix an issue when an episode fails to load
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
  podcasts/ShowInfoCoordinator.swift
Labels: Bug, Standard Tags

#1636 Standard Tags: prioritize embedded chapters
  podcasts/ChapterManager.swift
Labels: enhancement, Standard Tags

#1638 7.62 Release: Merge changes from 7.62.0.2 into `trunk`
  Modules/Server/Sources/PocketCastsServer/Public/Cache/ShowInfoDataRetriever.swift
  config/Version.xcconfig
  podcasts/ChapterManager.swift
  podcasts/ShowInfoCoordinator.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#1628 New podcasts grid design
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts/CircleView.swift
  podcasts/FolderGridCell.swift
  podcasts/FolderGridCell.xib
  podcasts/FolderListCell.swift
  podcasts/FolderPreviewView.swift
  podcasts/FolderViewController.swift
  podcasts/GridBadgeView.swift
  podcasts/GridHelper.swift
  podcasts/PCRefreshControl.swift
  podcasts/PodcastGridCell.swift
  podcasts/PodcastGridCell.xib
  podcasts/PodcastListCell.swift
  podcasts/PodcastListViewController.swift
  podcasts/UnplayedBadge.swift
  podcasts/UnplayedSashOverlayView.swift
Labels: Podcast grid layout

#1651 Standard Tags: do not force unwrap custom episode artwork URLs
  podcasts/ImageManager.swift
Labels: Bug, Standard Tags

#1648 Order the popular discover categories
  podcasts/Categories/CategoriesSelectorView.swift
Labels: Categories Redesign

#1642 Disable the Settings Sync feature flag for the 7.63 beta releases
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: settings

#1654 CI Check for #1639
  podcasts/PCNavigationController.swift
Labels: continuous integration

#1656 Standard Tags: put behind a remote feature flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Standard Tags

#1659 7.61.1 Release: Merge changes from 7.61.1.0 into `trunk`
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Releases

#1658 Merge 7.61.1 into 7.62
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Releases

#1660 Categories Redesign: Visual Fixes
  podcasts/LargeListSummaryViewController.swift
  podcasts/LargeListSummaryViewController.xib
Labels: Categories Redesign

#1662 Performance: Podcast Cache
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/AutoAddCandidatesDataManagerTests.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/DataManager+TestDatabase.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/PodcastDataManagerTests.swift
Labels: Performance

#1663 Performance: Only re-run showTick when value changes
  podcasts/EpisodeCell.swift
Labels: Performance

#1672 Disable UpNext on the tab bar
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Up Next

#1676 7.63 Release: Merge changes from 7.63.0.0 into `trunk`
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#1668 [Library Update] Upgrade Firebase to 10.24.0
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies

#1670 Move logStaleDownloads to background dispatch
  podcasts/AppDelegate.swift
Labels: Performance

#1666 Only propagate episode changes if the file size actually changed
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/MetadataTask.swift
  podcasts/EpisodeCell.swift
Labels: Bug
