Repository Automattic/pocket-casts-ios, pull requests merged in 2024-12, with the labels that each got.

#2492 Merge release/7.78 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/StoryShareableProvider.swift
  podcasts/PCViewController.swift
  podcasts/Referrals/ReferralSendPassVC.swift
  podcasts/Sharing/ShareDestination.swift
  podcasts/Strings+Generated.swift
  podcasts/UpNext.xcassets/up-next-shuffle-sheet.imageset/Contents.json
  podcasts/UpNext.xcassets/up-next-shuffle-sheet.imageset/shuffle.svg
  podcasts/UpNextAnnouncementView.swift
  podcasts/Whats New/Announcements.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
Labels: Releases

#2494 Increase Touch zone on close search results
  CHANGELOG.md
  podcasts/New Search/Views/History/SearchHistoryCell.swift
Labels: [Type] Bug, iPad

#2495 [Crash] Use the proxy in the audio callback
  podcasts/DefaultPlayer.swift
Labels: [Type] Bug

#2498 [Update Xcode] Update Xcode image
  .buildkite/shared-pipeline-vars
Labels: Xcode Update

#2493 Add setting to control auto-downloads on follow
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/DownloadSettingsViewController.swift
  podcasts/PodcastViewController.swift
  podcasts/ServerPodcastManager+Subscription.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Auto Download

#2500 Fix `CHANGELOG.md`
  CHANGELOG.md
Labels: [Type] Tooling

#2499 Fix: Long chapter title get truncated
  CHANGELOG.md
  podcasts/ChaptersViewController+Table.swift
  podcasts/PlayerChapterCell.xib
Labels: [Type] Enhancement, Deselecting Chapters

#2501 Merge release/7.78 into trunk
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/Bookmarks/List/BookmarkRow.swift
  podcasts/Bookmarks/List/BookmarkRowViewModel.swift
  podcasts/DownloadSettingsViewController.swift
  podcasts/New Search/Views/History/SearchHistoryCell.swift
  podcasts/PlaybackManager.swift
  podcasts/PodcastViewController.swift
  podcasts/ServerPodcastManager+Subscription.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
Labels: Releases

#2503 [Winback] Plans view
  podcasts.xcodeproj/project.pbxproj
  podcasts/Cancel Subscription/Cancel Subscription/CancelSubscriptionView.swift
  podcasts/Cancel Subscription/Cancel Subscription/CancelSubscriptionViewRow.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlanRow.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansView.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewModel.swift
  podcasts/CancelSubscription.xcassets/cs-app-icon.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-app-icon.imageset/pc-app-icon.svg
  podcasts/IAPHelper.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Winback

#2508 [UpNextShuffle] Add Toast message
  podcasts/Strings+Generated.swift
  podcasts/UpNextViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Projec] Up Next Shuffle

#2512 Remove UpNextOnTabBar Feature Flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/MainTabBarController+shortcuts.swift
  podcasts/MainTabBarController.swift
Labels: Up Next

#2513 Remove FF for transcripts
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  podcasts/Enumerations.swift
  podcasts/Settings.swift
  podcasts/ShowNotesUpdater.swift
Labels: [Project] Transcripts

#2514 Feature Flag: remove `newPlayerTransition` feature flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/AboutView.swift
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/Stories/2024/PaidStoryWallView2024.swift
  podcasts/End of Year/Stories/Views/PaidStoryWallView.swift
  podcasts/FirebaseManager.swift
  podcasts/MainTabBarController.swift
  podcasts/MiniPlayerViewController+Gestures.swift
  podcasts/MiniPlayerViewController+Positioning.swift
  podcasts/MiniPlayerViewController.swift
  podcasts/PlayerContainerViewController+Gestures.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/SceneHelper.swift
  podcasts/Settings.swift
Labels: [Type] Enhancement

#2496 Fix typo in logs: `s/Throtled/Throttled`
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshManager.swift
Labels: [Type] Other

#2517 Merge release/7.78 into trunk
  config/Version.xcconfig
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2521 Revert default player audio callback
  podcasts/DefaultPlayer.swift
Labels: [Type] Bug

#2525 Send logs by email
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileLog.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/LogsView.swift
  podcasts/LogsViewController.swift
  podcasts/OnlineSupportController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Enhancement

#2519 Hack Week: Add filtering to beta flags menu
  podcasts/Beta/BetaMenu.swift
Labels: [Type] Enhancement

#2530 Playback 2024: Image share dimensions
  podcasts/End of Year/StoryShareableProvider.swift
Labels: [Project] End of Year 2024

#2532 Merge release/7.78.1 into release/7.79
  config/Version.xcconfig
  podcasts/End of Year/StoryShareableProvider.swift
Labels: Releases

#2520 Update Player shelf overflow menu items order
  podcasts/Enumerations.swift
Labels: Improvements

#2527 Remove new show notes endpoint FF
  Modules/Server/Sources/PocketCastsServer/Public/Cache/CacheServerHandler.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/EpisodeArtwork.swift
  podcasts/EpisodeDetailViewController+ShowNotes.swift
  podcasts/ShowNotesPlayerItemViewController.swift
  podcasts/ShowNotesUpdater.swift
Labels: [Type] Tech Debt

#2533 [Tooling] Do some `Fastfile` cleanup
  .rubocop.yml
  fastlane/Fastfile
Labels: [Type] Tooling

#2522 Pass the reference of the proxy if needed
  podcasts/DefaultPlayer.swift
Labels: [Type] Bug, crash

#2539 Protobuf: ensure protoc and swift-protobuf is up-to-date
  scripts/update_proto.sh
Labels: [Type] Tooling

#2480 Feature: Episode rich text description
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/ExpandableLabel.swift
  podcasts/PodcastHeadingTableCell.swift
Labels: [Type] Feature

#2545 Fix SettingsTests
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
Labels: [Type] Bug

#2544 Fix highPassFilterRenderCallback callback
  podcasts/DefaultPlayer.swift
Labels: crash

#2536 Hack week: Lock screen scrubber setting
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Constants.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/PlaybackManager.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Enhancement

#2548 Remove Rss Chapters FF
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/ChapterManager.swift
Labels: Feature Flag

#2546 Merge release/7.79 into trunk
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  config/Version.xcconfig
  podcasts/DefaultPlayer.swift
Labels: Releases

#2560 Remove deselect chapters FF
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  PocketCastsTests/Tests/Playback/Chapters/ChapterManagerTests.swift
  podcasts/ChapterInfo.swift
  podcasts/ChaptersViewController+Table.swift
  podcasts/Whats New/DeselectChaptersAnnouncementViewModel.swift
Labels: Feature Flag

#2557 [Tooling] Danger GitHub Actions configuration update
  .github/workflows/run-danger.yml
Labels: [Type] Tooling

#2558 Instantly update the view
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/PlusPaywallReviewsViewModel.swift
Labels: [Type] Enhancement

#2563 Add option to collapse again if tapped on ExpandableLabel
  podcasts/ExpandableLabel.swift
Labels: [Type] Feature

#2553 [Tooling] Cherry-pick lastest `Fastfile` tweaks from `trunk` into `release/7.79`
  .rubocop.yml
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: [Type] Tooling

#2554 [Tooling] Introduce `publish_release` lane
  fastlane/Fastfile
Labels: [Type] Tooling

#2556 Download copy error logging
  podcasts/DownloadManager+URLSessionDelegate.swift
Labels: Logging

#2561 [Winback] Filter view based on client
  podcasts/AccountViewController+TableView.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlanRow.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansView.swift
  podcasts/CancelConfirmationViewModel.swift
Labels: [Project] Winback

#2541 Stats: apply API changes to prevent reset
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Public/StatsManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+ServerChanges.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask.swift
  podcasts/StatsViewController.swift
Labels: [Type] Fix, Stats

#2568 Remove give ratings FF
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastViewController.swift
  podcasts/Ratings/PodcastRatingViewModel.swift
  podcasts/Ratings/StarRatingView.swift
  podcasts/Whats New/Announcements.swift
Labels: Feature Flag

#2572 Instantly update the view
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/PlusPaywallReviewsViewModel.swift
Labels: [Project] Paywall Experiments

#2573 watchOS 10: fix crash
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshManager.swift
Labels: [Type] Bug, crash

#2569 Add event to track Podcasts list discover button tap
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/PodcastListViewController.swift
Labels: Analytics

#2574 Merge release/7.78.2 into release/7.79
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshManager.swift
Labels: Releases

#2571 Remove categories redesign FF
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Categories Redesign

#2566 App Clip: Add target and player implementation
  Pocket Casts App Clip/Assets.xcassets/Contents.json
  Pocket Casts App Clip/Assets.xcassets/effects-off.imageset/Contents.json
  Pocket Casts App Clip/Assets.xcassets/effects-off.imageset/effects-off@2x.png
  Pocket Casts App Clip/Assets.xcassets/effects-off.imageset/effects-off@3x.png
  Pocket Casts App Clip/Assets.xcassets/effects-on.imageset/Contents.json
  Pocket Casts App Clip/Assets.xcassets/effects-on.imageset/effects-on@2x.png
  Pocket Casts App Clip/Assets.xcassets/effects-on.imageset/effects-on@3x.png
  Pocket Casts App Clip/Info.plist
  Pocket Casts App Clip/NowPlayingPlayerItemViewControllerRepresentable.swift
  Pocket Casts App Clip/NowPlayingView.swift
  Pocket Casts App Clip/Pocket_Casts_App_Clip.entitlements
  Pocket Casts App Clip/Pocket_Casts_App_ClipApp.swift
  Pocket Casts App Clip/Preview Content/Preview Assets.xcassets/Contents.json
  Pocket Casts App Clip/app-clip-Bridging-Header.h
  Podfile
  Podfile.lock
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts App Clip.xcscheme
  podcasts/Analytics/Analytics.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
  podcasts/Analytics/Helpers/AnalyticsPlaybackHelper.swift
  podcasts/AnalyticsHelper.swift
  podcasts/ChapterInfo.swift
  podcasts/Chapters.swift
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/DownloadManager.swift
  podcasts/Episode+Formatting.swift
  podcasts/EpisodeArtwork.swift
  podcasts/EpisodeManager.swift
  podcasts/FileTypeUtil.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/NowPlayingPlayerItemViewController+Update.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/OptionsPicker.swift
  podcasts/PCNavigationController.swift
  podcasts/PaidFeature.swift
  podcasts/PlaybackManager.swift
  podcasts/PlaybackQueue.swift
  podcasts/PlayerColorHelper.swift
  podcasts/PlayerContainerViewController+Scroll.swift
  podcasts/PlayerContainerViewController+Update.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PlayerContainerViewController.xib
  podcasts/PodcastManager.swift
  podcasts/ServerSyncManager.swift
  podcasts/ShowNotesUpdater.swift
  podcasts/SleepTimerManager.swift
  podcasts/ThemeColor.swift
  podcasts/VideoViewController.swift
  podcasts/effects_button.json
  podcasts/podcasts.entitlements
  podcasts/podcasts.prototype.entitlements
  podcasts/podcastsDebug.entitlements
  podcasts/skip.json
Labels: [Project] App Clip

#2580 Remove newSharing FF
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/EpisodeDetailViewController.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/SharingHelper.swift
  podcasts/Whats New/Announcements.swift
Labels: Feature Flag

#2578 [Winback] Offer Confirmation Screen
  podcasts.xcodeproj/project.pbxproj
  podcasts/Cancel Subscription/Cancel Subscription/Offer View/CancelSubscriptionOfferSuccessView.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewModel.swift
  podcasts/CancelSubscription.xcassets/cs-sparkle-black.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-sparkle-black.imageset/Sparkle_Black.svg
  podcasts/CancelSubscription.xcassets/cs-sparkle-blue.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-sparkle-blue.imageset/Sparkle_Blue.svg
  podcasts/CancelSubscription.xcassets/cs-sparkle-gray.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-sparkle-gray.imageset/Sparkle_Gray.svg
  podcasts/CancelSubscription.xcassets/cs-sparkle-green.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-sparkle-green.imageset/Sparkle_Green.svg
  podcasts/CancelSubscription.xcassets/cs-sparkle-indigo.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-sparkle-indigo.imageset/Sparkle_Indigo.svg
  podcasts/CancelSubscription.xcassets/cs-sparkle-red.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-sparkle-red.imageset/Sparkle_Red.svg
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Winback

#2576 Merge release/7.79 into trunk
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshManager.swift
  config/Version.xcconfig
  fastlane/Fastfile
  podcasts/Onboarding/Plus/UpgradeExperiment/Reviews/PlusPaywallReviewsViewModel.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2582 Disable private feed sharing
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/SharingHelper.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Enhancement

#2585 Disable private feed in lists
  podcasts/SharePodcastsViewController.swift
Labels: [Type] Enhancement

#2589 Pass BETA_RELEASE to release-upload.sh invocation
  .buildkite/commands/release-upload.sh
  .buildkite/release-builds.yml
Labels: [Type] Tooling
