Repository Automattic/pocket-casts-ios, pull requests merged in 2024-10, with the labels that each got.

#2229 Listening History Search enable Feature Flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Type] Feature, [Project] Listening History Search

#2223 Referrals: Integrate api calls on claim referral
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ReferralRedeemTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ReferralValidateTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+Referrals.swift
  podcasts/ProfileViewController.swift
  podcasts/Referrals/ReferralCardMiniView.swift
  podcasts/Referrals/ReferralsClaimPass.swift
  podcasts/Referrals/ReferralsCoordinator.swift
Labels: [Project] Referrals

#2228 Integrate onboarding flow when claiming guest pass
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Referrals/ReferralClaimPassVC.swift
  podcasts/Referrals/ReferralsClaimPass.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Referrals

#2231 Referrals: Add analytics
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/ProfileViewController.swift
  podcasts/Referrals/ReferralClaimPassVC.swift
  podcasts/Referrals/ReferralSendPassVC.swift
  podcasts/Referrals/ReferralsClaimPass.swift
Labels: [Project] Referrals

#2232 Update sorting by title to match Android
  podcasts/EpisodesDataManager.swift
Labels: [Type] Bug

#2233 Discover Collection View: Category and Region switching support
  podcasts.xcodeproj/project.pbxproj
  podcasts/Array+DiscoverItem.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
  podcasts/CategoryPodcastsViewController.swift
  podcasts/CategoryPodcastsViewController.xib
  podcasts/CountryChooserViewController.swift
  podcasts/CountrySummaryViewController.swift
  podcasts/DiscoverCellType.swift
  podcasts/DiscoverCollectionViewController+Categories.swift
  podcasts/DiscoverCollectionViewController+DiscoverDelegate.swift
  podcasts/DiscoverCollectionViewController+Search.swift
  podcasts/DiscoverCollectionViewController.swift
  podcasts/DiscoverSummaryProtocol.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/LargeListSummaryViewController.swift
  podcasts/SmallPagedListSummaryViewController.swift
  podcasts/ThemeableCollectionView.swift
Labels: [Project] Discover Collection View

#2236 Discover Collection View: Loading states
  podcasts.xcodeproj/project.pbxproj
  podcasts/Array+DiscoverItem.swift
  podcasts/ContentUnavailableConfiguration.swift
  podcasts/DiscoverCollectionViewController+DiscoverDelegate.swift
  podcasts/DiscoverCollectionViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Discover Collection View

#2237 Enable `discoverCollectionView` feature flag
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Discover Collection View

#2239 Referrals: Add analytics when share pass screen is dismissed
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Referrals/ReferralSendPassView.swift
Labels: [Project] Referrals

#2214 Map custom treatments
  PocketCastsTests/Tests/ABTest/ABTestProviderTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/ABTest/ABTest.swift
  podcasts/ABTest/Variation+CustomTreatment.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
Labels: [Project] Paywall Experiments

#2241 Add missing type
  CHANGELOG.md
  podcasts/FileTypeUtil.swift
Labels: [Type] Bug

#2243 Merge/release 7.74.02 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/EpisodesDataManager.swift
  podcasts/FileTypeUtil.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: continuous integration

#2238 Discover Collection View: Call appearance methods on cells
  podcasts/DiscoverCellType.swift
  podcasts/DiscoverCollectionViewController+Search.swift
  podcasts/DiscoverCollectionViewController.swift
Labels: [Project] Discover Collection View

#2248 [Widget] iOS 18: Now Playing Widget support Tint Color
  WidgetExtension/Common/ArtworkViews.swift
  WidgetExtension/Common/Widget+Accentable.swift
  WidgetExtension/Now Playing/NowPlayingEntryView.swift
  WidgetExtension/Up Next/EpisodeView.swift
  podcasts.xcodeproj/project.pbxproj
Labels: [Type] Bug, [Area] iOS 18

#2252 Update transcript not available string
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Transcripts

#2249 [Widget] iOS 18: Up Next Widget support Tint Color
  CHANGELOG.md
  WidgetExtension/Up Next/EpisodeView.swift
  WidgetExtension/Up Next/HungryForMoreView.swift
  WidgetExtension/Up Next/UpNextLargeWidgetView.swift
  WidgetExtension/Up Next/UpNextMediumWidgetView.swift
  WidgetExtension/Up Next/UpNextWidgetEntryView.swift
Labels: [Type] Bug, [Area] iOS 18

#2256 Merge release/7.74 into trunk
  CHANGELOG.md
  WidgetExtension/Common/ArtworkViews.swift
  WidgetExtension/Common/Widget+Accentable.swift
  WidgetExtension/Now Playing/NowPlayingEntryView.swift
  WidgetExtension/Up Next/EpisodeView.swift
  WidgetExtension/Up Next/HungryForMoreView.swift
  WidgetExtension/Up Next/UpNextLargeWidgetView.swift
  WidgetExtension/Up Next/UpNextMediumWidgetView.swift
  WidgetExtension/Up Next/UpNextWidgetEntryView.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts.xcodeproj/project.pbxproj
  podcasts/Strings+Generated.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2261 [Custom Playback Settings] Feature Flag & Segmented Control
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/EffectsViewController.swift
  podcasts/EffectsViewController.xib
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Custom Playback Settings

#2260 Merge release/7.74 into trunk
  config/Version.xcconfig
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2235 Referrals: IAP setup
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ReferralValidateTask.swift
  Pocket Casts Configuration.storekit
  podcasts/IAPHelper.swift
  podcasts/IAPTypes.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Referrals/Banner/ReferralsClaimBannerTableCell.swift
  podcasts/Referrals/Banner/ReferralsClaimBannerView.swift
  podcasts/Referrals/ReferralsClaimPass.swift
  podcasts/Referrals/ReferralsCoordinator.swift
  podcasts/Referrals/ReferralsOfferInfo.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  podcasts/podcastsDebug.entitlements
Labels: [Project] Referrals

#2257 Discover Collection View: Auto Layout & cell reuse warnings
  podcasts/CollectionSummaryViewController.xib
  podcasts/CountrySummaryViewController.xib
  podcasts/DiscoverCollectionViewController.swift
  podcasts/FeaturedSummaryViewController.xib
  podcasts/LargeListCell.xib
  podcasts/SmallPagedListSummaryViewController.xib
Labels: [Project] Discover Collection View

#2270 Fix iOS 18 Share Extension: Call openURL on cast version of UIApplication
  Share Extension/ShareViewController.swift
Labels: [Type] Bug

#2273 Revert paywall title
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Update

#2272 [7.75] CHANGELOG update
  CHANGELOG.md
Labels: Changelog

#2271 Merge release/7.75 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2279 Hot Fix: Fix Sponsored Podcast ordering in the Featured section
  podcasts/FeaturedSummaryViewController.swift
Labels: [Type] Bug

#2277 Remove Gravatar feature flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/AccountViewController.swift
Labels: [Type] Tech Debt

#2276 SPM update
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Dependencies

#2269 [Custom Playback Settings] Add main logic to switch between global and local settings
  podcasts/EffectsViewController.swift
  podcasts/PlaybackManager.swift
Labels: [Project] Custom Playback Settings

#2278 Fix Sponsored Podcast ordering in the Featured section
  podcasts/FeaturedSummaryViewController.swift
Labels: [Type] Bug

#2275 [Sentry] [NSConcreteFileHandle writeData:]: No space left on device
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Logging/PersistentTextWriting.swift
Labels: [Type] Bug

#2265 [Tooling] Add script to spell-check `en.lproj` strings
  fastlane/Fastfile
Labels: [Type] Tooling

#2247 Playback Skipping: Custom Resource Loader with file cache
  CHANGELOG.md
  podcasts.xcodeproj/project.pbxproj
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/DownloadManager.swift
  podcasts/MediaExporterResourceLoaderDelegate.swift
  podcasts/MediaFileHandle.swift
Labels: playback

#2274 Referrals: Implement discount offer
  podcasts/IAPHelper.swift
  podcasts/Referrals/ReferralsCoordinator.swift
  podcasts/Referrals/ReferralsOfferInfo.swift
Labels: [Project] Referrals

#2282 Referrals Show welcome screen after purchase with referral
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Referrals/ReferralsClaimPass.swift
  podcasts/Referrals/ReferralsCoordinator.swift
Labels: [Project] Referrals

#2292 Referrals: Enable by default
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Referrals

#2291 Merge release/7.75 into trunk
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Logging/PersistentTextWriting.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/EffectsViewController.swift
  podcasts/FeaturedSummaryViewController.swift
  podcasts/PlaybackManager.swift
  podcasts/ProfileViewController.swift
  podcasts/Referrals/Banner/ReferralsClaimBannerTableCell.swift
  podcasts/Referrals/Banner/ReferralsClaimBannerView.swift
  podcasts/Referrals/ReferralsClaimPass.swift
  podcasts/Referrals/ReferralsCoordinator.swift
  podcasts/Strings+Generated.swift
  podcasts/TipView.swift
  podcasts/ca.lproj/InfoPlist.strings
  podcasts/ca.lproj/Intents.strings
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2288 End of Year 2024: Add of end_of_year_2024 feature flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] End of Year 2024

#2285 [Custom Playback Settings] Apply global to local
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  podcasts/EffectsViewController.swift
  podcasts/PlaybackEffects.swift
  podcasts/PlaybackManager.swift
  podcasts/PodcastEffectsViewController+Table.swift
Labels: [Project] Custom Playback Settings

#2293 [Custom Playback Settings] Add Analytics
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsPlaybackHelper.swift
  podcasts/EffectsViewController.swift
  podcasts/PodcastEffectsViewController+Table.swift
Labels: [Project] Custom Playback Settings

#2301 Vacuum on all releases
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/MainTabBarController.swift
  podcasts/Settings.swift
Labels: crash

#2299 [Global Playback Settings] Enable Feature Flag
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Custom Playback Settings

#2300 [Global Playback Settings] Improvements in main logic
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/EffectsViewController.swift
  podcasts/PlaybackEffects.swift
  podcasts/PlaybackManager.swift
Labels: [Project] Custom Playback Settings

#2303 Update `release-toolkit` to latest version
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: [Type] Tooling

#2302 Merge release/7.75 into trunk
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsPlaybackHelper.swift
  podcasts/EffectsViewController.swift
  podcasts/IAPHelper.swift
  podcasts/MainTabBarController.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/PlaybackEffects.swift
  podcasts/PlaybackManager.swift
  podcasts/PodcastEffectsViewController+Table.swift
  podcasts/Referrals/ReferralsClaimPass.swift
  podcasts/Referrals/ReferralsCoordinator.swift
  podcasts/Referrals/ReferralsOfferInfo.swift
  podcasts/Settings.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2304 Fix/1644 show dynamic island on player
  CHANGELOG.md
  podcasts/PCViewController.swift
  podcasts/PlayerContainerViewController.swift
Labels: [Type] Bug

#2295 Auto downloading episode: Global Settings UI
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/DownloadSettingsViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Auto Downloading Episodes

#2310 Set search view bottom constraint to safe area
  podcasts/DiscoverCollectionViewController+Search.swift
  podcasts/PlaybackManager.swift
Labels: [Type] Bug

#2311 [Up next shuffle] Modify modal
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Strings+Generated.swift
  podcasts/UpNextViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Projec] Up Next Shuffle

#2308 Enable FF Paywall experiment
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Paywall Experiments

#2306 Playback 2024: Add multi-year support for End of Year/Playback
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EndOfYearDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncYearListeningHistoryTask.swift
  PocketCastsTests/Mocks/EndOfYearManagerMock.swift
  PocketCastsTests/Tests/End of Year/EndOfYearStoriesBuilderTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Constants.swift
  podcasts/DeveloperMenu.swift
  podcasts/End of Year/End of Year 2023/EndOfYear2023StoriesModel.swift
  podcasts/End of Year/End of Year 2023/EndOfYear2023Story.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/Views/EndOfYearModal.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/MainTabBarController.swift
  podcasts/PodcastListViewController.swift
  podcasts/ProfileViewController.swift
  podcasts/Settings.swift
Labels: [Project] End of Year 2024

#2313 Playback 2024: Cell & Modal Prompt + Multi year developer option
  podcasts.xcodeproj/project.pbxproj
  podcasts/DeveloperMenu.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/Views/EndOfYearCard.swift
  podcasts/End of Year/Views/EndOfYearModal.swift
  podcasts/End of Year/Views/EndOfYearPromptCell.swift
  podcasts/EndOfYear.xcassets/playback-24.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-24.imageset/playback-24.svg
  podcasts/EndOfYear.xcassets/playback-featured.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-featured.imageset/playback-featured.svg
  podcasts/EndOfYearDeveloperMenuButton.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024

#2315 Playback 2024: Intro story
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2023/EndOfYear2023StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/Stories/2023/CompletionRateStory2023.swift
  podcasts/End of Year/Stories/2023/EpilogueStory2024.swift
  podcasts/End of Year/Stories/2023/IntroStory2023.swift
  podcasts/End of Year/Stories/2023/ListenedNumbersStory2023.swift
  podcasts/End of Year/Stories/2023/ListeningTimeStory2023.swift
  podcasts/End of Year/Stories/2023/LongestEpisodeStory2023.swift
  podcasts/End of Year/Stories/2023/TopFivePodcastsStory2023.swift
  podcasts/End of Year/Stories/2023/TopListenedCategoriesStory2023.swift
  podcasts/End of Year/Stories/2023/TopOnePodcastStory2023.swift
  podcasts/End of Year/Stories/2023/YearOverYearStory2023.swift
  podcasts/End of Year/Stories/2024/IntroStory2024.swift
  podcasts/End of Year/Stories/2024/TopSpotStory2024.swift
  podcasts/EndOfYear.xcassets/playback-sticker-2024.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-sticker-2024.imageset/playback-sticker-2024.svg
  podcasts/EndOfYear.xcassets/playback-sticker-new.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-sticker-new.imageset/playback-sticker-new.svg
  podcasts/Humane-Medium.otf
  podcasts/SwiftUI/PositionModifier.swift
  podcasts/podcasts-Info.plist
Labels: [Project] End of Year 2024

#2318 Auto-Downloading of Episode: Add logic for auto downloads limits
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/ServerSyncDelegateProtocol.swift
  Pocket Casts Watch App/WatchSyncManager+ServerSyncDelegate.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate+Defaults.swift
  podcasts/BundlePodcastCell.swift
  podcasts/CategorySponsoredCell.swift
  podcasts/DiscoverCollectionViewController+DiscoverDelegate.swift
  podcasts/DiscoverPodcastTableCell.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/IncomingShareListViewController.swift
  podcasts/NetworkViewController.swift
  podcasts/New Search/Views/Results/RoundedSubscribeButtonView.swift
  podcasts/PodcastManager.swift
  podcasts/PodcastViewController.swift
  podcasts/ServerPodcastManager+Subscription.swift
  podcasts/ServerSyncManager.swift
  podcasts/Settings.swift
Labels: [Project] Auto Downloading Episodes

#2332 Revert FF by default
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Type] Other, Feature Flag

#2329 [Up Next Shuffle] Add Tracks event
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/UpNextViewController.swift
Labels: [Projec] Up Next Shuffle

#2322 Add FFs to control referrals send and claim flows separately
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Referrals/ReferralsCoordinator.swift
Labels: [Project] Referrals

#2333 Referrals: Simplify sharing by just sharing text and url
  podcasts/Referrals/ReferralSendPassVC.swift
Labels: [Project] Referrals

#2336 [Custom Playback Settings] Hide segmented for local Files
  podcasts/EffectsViewController.swift
Labels: [Project] Custom Playback Settings

#2339 Merge release/7.75 into trunk
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  podcasts/EffectsViewController.swift
  podcasts/Referrals/ReferralSendPassVC.swift
  podcasts/Referrals/ReferralsCoordinator.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2324 Playback 2024: Epilogue Screen
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/Stories/2023/EpilogueStory2023.swift
  podcasts/End of Year/Stories/2024/EpilogueStory2024.swift
  podcasts/End of Year/Stories/MDCSwiftUIWrapper.swift
  podcasts/EndOfYear.xcassets/playback-24-heart.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-24-heart.imageset/playback-24-heart.svg
  podcasts/Strings+Generated.swift
  podcasts/Styles.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024

#2335 Playback 2024: Listening Time Story + sharing refactors
  PocketCastsTests/Tests/End of Year/StoriesModelTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2023/EndOfYear2023StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/2024/ListeningTime2024Story.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/StoriesController.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/EndOfYear.xcassets/playback-sticker-way-to-go.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-sticker-way-to-go.imageset/playback-sticker-way-to-go.svg
  podcasts/Humane-Bold.otf
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  podcasts/podcasts-Info.plist
Labels: [Project] End of Year 2024

#2341 Remove long press gesture on referrals banner view
  podcasts/Referrals/Banner/ReferralsClaimBannerView.swift
Labels: [Project] Referrals

#2338 Ensures that watch sync is done in the background
  CHANGELOG.md
  podcasts/WatchManager.swift
Labels: [Type] Bug, crash

#2327 [Up Next Shuffle] Add shuffle logic
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/PlaybackManager.swift
  podcasts/UpNextViewController.swift
Labels: [Projec] Up Next Shuffle

#2334 Download button on player
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/BaseEpisode.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  podcasts/Enumerations.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/NowPlayingPlayerItemViewController+Update.swift
  podcasts/ShelfActionsViewController+Table.swift
  podcasts/ShelfLoadState.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Auto Downloading Episodes

#2343 Merge release/7.76 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2337 [Custom Playback Settings] Apply same logic for when a user enable the podcast settings
  podcasts/EffectsViewController.swift
  podcasts/PlaybackManager.swift
  podcasts/PodcastEffectsViewController+Table.swift
Labels: [Project] Custom Playback Settings

#2344 Disable Up Next Shuffle FF and update Changelog
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Feature Flag

#2340 Playback 2024: Top 5 Podcasts List
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/Stories/2024/Top5Podcasts2024Story.swift
  podcasts/EndOfYear.xcassets/playback-2024-shape-pentagon.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-2024-shape-pentagon.imageset/playback-2024-shape-pentagon.svg
  podcasts/EndOfYear.xcassets/playback-2024-shape-two-ovals.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-2024-shape-two-ovals.imageset/playback-2024-shape-two-ovals.svg
  podcasts/EndOfYear.xcassets/playback-2024-shape-wavy-circle.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-2024-shape-wavy-circle.imageset/playback-2024-shape-wavy-circle.svg
Labels: [Project] End of Year 2024

#2345 Merge release/7.76 into trunk
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/BaseEpisode.swift
  PocketCastsTests/Tests/Utilities/SettingsTests.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/EffectsViewController.swift
  podcasts/Enumerations.swift
  podcasts/NowPlayingPlayerItemViewController+Shelf.swift
  podcasts/NowPlayingPlayerItemViewController+Update.swift
  podcasts/PlaybackManager.swift
  podcasts/PodcastEffectsViewController+Table.swift
  podcasts/ShelfActionsViewController+Table.swift
  podcasts/ShelfLoadState.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#2347 Playback 2024: Longest Episode
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/Stories/2024/LongestEpisode2024Story.swift
  podcasts/End of Year/Stories/Views/PodcastCover.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/EndOfYear.xcassets/playback-sticker-phew.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-sticker-phew.imageset/playback-sticker-phew.svg
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024

#2356 [Enhancement] Replace Subscribe with Follow
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/BundlePodcastCell.swift
  podcasts/CategorySponsoredCell.swift
  podcasts/DescriptiveCollectionCell.swift
  podcasts/DiscoverFeaturedView.swift
  podcasts/DiscoverPodcastTableCell.swift
  podcasts/FilterPreviewViewController.swift
  podcasts/ImportExportViewController.swift
  podcasts/LargeListCell.swift
  podcasts/Onboarding/Import/ImportViewModel.swift
  podcasts/PodcastFilterOverlayController.swift
  podcasts/PodcastGroupCell.swift
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastSettingsViewController+Table.swift
  podcasts/PodcastSettingsViewController.swift
  podcasts/PodcastViewController.swift
  podcasts/SinglePodcastViewController.swift
  podcasts/SmallListCell.swift
  podcasts/Strings+Generated.swift
  podcasts/SubscribeButton.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Enhancement

#2361 Additional Logging for Upload file task, 401 handling, keychain clearing, and sign out
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ApiBaseTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/UploadFilePlayRequestTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/TokenHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncManager.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/AuthenticationHelper.swift
  podcasts/SyncSigninViewController.swift
Labels: Logging

#2363 [Custom Playback Settings] Simplify logic
  podcasts/EffectsViewController.swift
  podcasts/PlaybackEffects.swift
  podcasts/PlaybackManager.swift
  podcasts/PodcastEffectsViewController+Table.swift
Labels: [Project] Custom Playback Settings

#2358 Fix glitch on podcast header animation on subscribe
  podcasts/PodcastViewController.swift
Labels: [Type] Bug

#2362 Use a single icon for folders upsell
  CHANGELOG.md
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastHeadingTableCell.xib
  podcasts/PodcastListViewController.swift
Labels: [Type] Enhancement, folders

#2359 Playback 2024: Listened Count
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/Stories/2024/NumberListened2024.swift
  podcasts/End of Year/Stories/Views/CommonStoryViews.swift
Labels: [Project] End of Year 2024

#2350 Playback 2024: Completion Rate + Pay Wall
  PocketCastsTests/Tests/End of Year/StoriesModelTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2023/EndOfYear2023StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/2024/CompletionRate2024Story.swift
  podcasts/End of Year/Stories/2024/EpilogueStory2024.swift
  podcasts/End of Year/Stories/2024/ListeningTime2024Story.swift
  podcasts/End of Year/Stories/2024/PaidStoryWallView2024.swift
  podcasts/End of Year/Stories/2024/SubscriptionBadge2024.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/StoryShareableProvider.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/EndOfYear.xcassets/playback-24-patron-badge.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-24-patron-badge.imageset/playback-24-patron-badge.svg
  podcasts/EndOfYear.xcassets/playback-24-plus-badge.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-24-plus-badge.imageset/playback-24-plus-badge.svg
  podcasts/EndOfYear.xcassets/playback-24-union.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-24-union.imageset/playback-24-union.svg
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024

#2364 Merge release/7.76 into trunk
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  podcasts/EffectsViewController.swift
  podcasts/PlaybackEffects.swift
  podcasts/PlaybackManager.swift
  podcasts/PodcastEffectsViewController+Table.swift
  podcasts/PodcastViewController.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2367 Playback 2024: Top Spot
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/Stories/2024/StoryFooter2024.swift
  podcasts/End of Year/Stories/2024/TopSpotStory2024.swift
  podcasts/End of Year/StoriesController.swift
  podcasts/EndOfYear.xcassets/playback-sticker-top-spot.imageset/Contents.json
  podcasts/EndOfYear.xcassets/playback-sticker-top-spot.imageset/playback-sticker-top-spot.svg
  podcasts/PodcastImage.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024

#2368 Playback 2024: Fix indicator color in EoY 2024 Stories
  PocketCastsTests/Tests/End of Year/StoriesModelTests.swift
  podcasts/End of Year/End of Year 2023/EndOfYear2023StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/End of Year/Views/StoryIndicator.swift
Labels: [Project] End of Year 2024

#2369 Playback 2024: Loading and Error screens
  PocketCastsTests/Tests/End of Year/StoriesModelTests.swift
  podcasts/End of Year/End of Year 2023/EndOfYear2023StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/EndOfYearStoriesBuilder.swift
  podcasts/End of Year/Stories/2024/Top5Podcasts2024Story.swift
  podcasts/End of Year/Stories/EndOfYearStoriesDataSource.swift
  podcasts/End of Year/StoriesDataSource.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/Views/StoriesView.swift
Labels: [Project] End of Year 2024

#2371 Playback 2024: Year over year compare
  PocketCastsTests/Tests/End of Year/YearOverYearCompareTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/End of Year/End of Year 2024/EndOfYear2024StoriesModel.swift
  podcasts/End of Year/End of Year 2024/EndOfYear2024Story.swift
  podcasts/End of Year/Stories/2024/CompletionRate2024Story.swift
  podcasts/End of Year/Stories/2024/PaidStoryWallView2024.swift
  podcasts/End of Year/Stories/2024/YearOverYearCompare2024Story.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] End of Year 2024
