Repository Automattic/pocket-casts-ios, pull requests merged in 2025-04, with the labels that each got.

#2903 [Newform AppsFlyer Integration] Update Privacy page
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerAdapter.swift
  podcasts/Analytics/Analytics.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate+Analytics.swift
  podcasts/PrivacySettings/PrivacySettingsDataSource.swift
  podcasts/PrivacySettings/PrivacySettingsLegacyDataSource.swift
  podcasts/PrivacySettings/PrivacySettingsViewController.swift
  podcasts/PrivacySettings/PrivacySettingsViewController.xib
Labels: [Project] Newform AppsFlyer Integration

#2916 Fix generated subtitles crash
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/TranscriptManager.swift
Labels: crash, [Project] Transcripts

#2918 Merge release/7.86 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerAdapter.swift
  podcasts/Analytics/Analytics.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate+Analytics.swift
  podcasts/PlaybackManager.swift
  podcasts/PrivacySettings/PrivacySettingsDataSource.swift
  podcasts/PrivacySettings/PrivacySettingsLegacyDataSource.swift
  podcasts/PrivacySettings/PrivacySettingsViewController.swift
  podcasts/PrivacySettings/PrivacySettingsViewController.xib
  podcasts/TranscriptManager.swift
  podcasts/ca.lproj/InfoPlist.strings
  podcasts/ca.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2919 [Hotfix] Fix generated subtitles crash (#2916)
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/TranscriptManager.swift
Labels: crash, hotfix

#2920 Merge release/7.85.1 into release/7.86
  config/Version.xcconfig
Labels: Releases

#2913 Funding tag support - Add funding button to podcast view
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/PodcastHeaderView.swift
  podcasts/PodcastViewController.swift
  podcasts/Podcasts.xcassets/podcast-funding.imageset/Contents.json
  podcasts/Podcasts.xcassets/podcast-funding.imageset/podcast-funding.svg
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Feature - Small

#2917 [Newform AppsFlyer Integration] Enable Feature Flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Newform AppsFlyer Integration

#2924 Revert FF Enabled
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Newform AppsFlyer Integration

#2930 Merge release/7.85.2 into release/7.86
  podcasts/FoldersCoordinator.swift
Labels: Releases

#2908 [Podcast view change ] Design review
  podcasts/CommonImages.xcassets/chevron-small-down.imageset/Contents.json
  podcasts/CommonImages.xcassets/chevron-small-down.imageset/chevron-small-down.svg
  podcasts/FakeNavViewController.swift
  podcasts/PodcastHeaderModel.swift
  podcasts/PodcastHeaderView.swift
  podcasts/PodcastViewController.swift
  podcasts/Ratings/StarRatingView.swift
Labels: [Project] Podcast View Changes

#2931 Merge release/7.86 into trunk
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/CommonImages.xcassets/chevron-small-down.imageset/Contents.json
  podcasts/CommonImages.xcassets/chevron-small-down.imageset/chevron-small-down.svg
  podcasts/FakeNavViewController.swift
  podcasts/FoldersCoordinator.swift
  podcasts/PodcastHeaderModel.swift
  podcasts/PodcastHeaderView.swift
  podcasts/PodcastViewController.swift
  podcasts/Podcasts.xcassets/podcast-funding.imageset/Contents.json
  podcasts/Podcasts.xcassets/podcast-funding.imageset/podcast-funding.svg
  podcasts/Ratings/StarRatingView.swift
  podcasts/Strings+Generated.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
Labels: Releases

#2933 Update funding button color
  podcasts/PodcastHeaderView.swift
Labels: [Project] Podcast View Changes

#2923 [Encourage Account Creation] Full screen login
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Onboarding/Login/LoginLandingHostingController.swift
  podcasts/Onboarding/Login/LoginLandingView.swift
  podcasts/Onboarding/LoginCoordinator.swift
Labels: [Project] Encourage Account Creation

#2936 Merge release/7.86 into trunk
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  podcasts/Onboarding/Login/LoginLandingHostingController.swift
  podcasts/Onboarding/Login/LoginLandingView.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/PodcastHeaderView.swift
  podcasts/ca.lproj/Localizable.strings
Labels: Releases

#2937 [Newform AppsFlyer Integration] Display att for new users only
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Analytics/Adapters/Apple ATT/AppTrackingTransparencyController.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/MainTabBarController.swift
  podcasts/PrivacySettings/PrivacySettingsDataSource.swift
Labels: [Project] Newform AppsFlyer Integration

#2939 Merge release/7.86 into trunk
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  podcasts/Analytics/Adapters/Apple ATT/AppTrackingTransparencyController.swift
  podcasts/AppDelegate+Defaults.swift
  podcasts/MainTabBarController.swift
  podcasts/PrivacySettings/PrivacySettingsDataSource.swift
Labels: Releases

#2934 [Notifications revamp] Feature flag and settings UI
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/NotificationsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Notifications Revamp

#2941 Update downloading indicator color on up next to match the color on episode list
  CHANGELOG.md
  podcasts/PlayerCell.swift
Labels: [Type] Bug, Up Next

#2947 updated funding link to open in external browser
  podcasts/PodcastViewController.swift
Labels: [Type] Enhancement, Standard Tags

#2948 Merge release/7.86 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/PlayerCell.swift
  podcasts/PodcastViewController.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/InfoPlist.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/InfoPlist.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/InfoPlist.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/InfoPlist.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/InfoPlist.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/ja.lproj/InfoPlist.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/InfoPlist.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/InfoPlist.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/sv.lproj/InfoPlist.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/InfoPlist.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2954 Up Next Emptying: Debug info.txt file + Watch App Installed App Data
  podcasts.xcodeproj/project.pbxproj
  podcasts/DatabaseExport.swift
  podcasts/DebugInfo.swift
  podcasts/SupportConfig.swift
  podcasts/WatchManager.swift
Labels: [Area] watchOS, Logging

#2950 Podcast view changes - tweak on layout and interaction
  podcasts/PodcastHeaderDescriptionView.swift
  podcasts/PodcastHeaderView.swift
  podcasts/PodcastViewController.swift
  podcasts/RichExpandableDescriptionView.swift
Labels: [Project] Podcast View Changes

#2943 [Notifications Revamp] - Onboarding notifications - Part I
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/AppearanceViewController.swift
  podcasts/Constants.swift
  podcasts/DeveloperMenu.swift
  podcasts/MainTabBarController.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
  podcasts/Notifications/NotificationsCoordinator.swift
  podcasts/NotificationsHelper.swift
  podcasts/NotificationsViewController.swift
  podcasts/Settings.swift
  podcasts/SettingsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  scripts/notifications/filters.apns
  scripts/notifications/settings_appearance_theme.apns
  scripts/notifications/settings_import.apns
  scripts/notifications/signup.apns
  scripts/notifications/upnext.apns
  scripts/notifications/upsell.apns
Labels: [Project] Notifications Revamp

#2958 [Encourage Account Creation] Add analytics events
  PocketCastsTests/Tests/Encourage Account Creation/InformationalBannerViewModelTests.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/ListeningHistoryViewController.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerType.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerView.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerViewCoordinator.swift
  podcasts/Onboarding/Encourage Account Creation/Modal/InformationalModalView.swift
  podcasts/Onboarding/Encourage Account Creation/Modal/InformationalModalViewModel.swift
Labels: [Project] Encourage Account Creation

#2962 [Newform AppsFlyer Integration] Catch app installed event
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerAdapter.swift
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerDataProvider.swift
  podcasts/AppDelegate.swift
Labels: [Project] Newform AppsFlyer Integration

#2964 Fix flashing when switching tabs
  CHANGELOG.md
  podcasts/MainTabBarController.swift
Labels: [Type] Bug

#2965 Merge release/7.86 into trunk
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerAdapter.swift
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerDataProvider.swift
  podcasts/AppDelegate.swift
  podcasts/MainTabBarController.swift
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-librofm.imageset/Contents.json
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-librofm.imageset/libro.fm-icon.svg
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/PodcastHeaderDescriptionView.swift
  podcasts/PodcastHeaderView.swift
  podcasts/PodcastViewController.swift
  podcasts/RichExpandableDescriptionView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/it.lproj/InfoPlist.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ru.lproj/InfoPlist.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/InfoPlist.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2955 [Encourage Account Creation] Add banners
  PocketCastsTests/Tests/Encourage Account Creation/InformationalBannerViewCoordinatorTests.swift
  PocketCastsTests/Tests/Encourage Account Creation/InformationalBannerViewModelTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/DeveloperMenu.swift
  podcasts/InformationalModal.xcassets/eac_filters_banner.imageset/Contents.json
  podcasts/InformationalModal.xcassets/eac_filters_banner.imageset/retry.svg
  podcasts/InformationalModal.xcassets/eac_listening_history_banner.imageset/Contents.json
  podcasts/InformationalModal.xcassets/eac_listening_history_banner.imageset/clock-large.svg
  podcasts/InformationalModal.xcassets/eac_profile_banner.imageset/Contents.json
  podcasts/InformationalModal.xcassets/eac_profile_banner.imageset/heart.svg
  podcasts/InformationalModal.xcassets/informational_card_backups.imageset/backups@2x.png
  podcasts/InformationalModal.xcassets/informational_card_backups.imageset/backups@3x.png
  podcasts/ListeningHistoryViewController.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerType.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerView.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerViewCoordinator.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerViewModel.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalProfileBannerCell.swift
  podcasts/Onboarding/Encourage Account Creation/Modal/InformationalFeatureCardItem.swift
  podcasts/Onboarding/Encourage Account Creation/Modal/InformationalModalView.swift
  podcasts/Onboarding/Encourage Account Creation/Modal/InformationalModalViewModel.swift
  podcasts/PlaylistsViewController.swift
  podcasts/ProfileViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/SwiftUI/HorizontalCarouselCardViewContainer.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Encourage Account Creation

#2959 Up Next Emptying: Apple Watch log export
  podcasts/DatabaseExport.swift
  podcasts/Zendesk/FileLog+FileUpload.swift
Labels: [Area] watchOS, Logging

#2960 [Fix] Avoid to assign wrong frame position
  podcasts/AudioReadTask.swift
Labels: [Type] Bug

#2969 [Fix] Add Libro.fm URL
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
Labels: [Type] Bug

#2971 Fix switch to effects player
  podcasts/PlaybackManager.swift
Labels: [Type] Bug, [Project] App Clip

#2963 [Notifications Revamp] Onboarding notifications check task completion
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate+Analytics.swift
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/DeveloperMenu.swift
  podcasts/Notifications/NotificationsCoordinator+AnalyticsAdapter.swift
  podcasts/Notifications/NotificationsCoordinator.swift
Labels: [Project] Notifications Revamp

#2973 Merge release/7.86.1 into trunk
  config/Version.xcconfig
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
  podcasts/PlaybackManager.swift
Labels: Releases

#2974 Merge release/7.86.1 into trunk
  Gemfile.lock
Labels: Releases

#2968 [Encourage Account Creation] Enable feature flag
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Encourage Account Creation

#2975 Merge release/7.87 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2970 Up Next Emptying: Save apple watch logs to file
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileRotating.swift
  podcasts/WatchManager+Send.swift
  podcasts/WatchManager.swift
Labels: [Area] watchOS, Logging

#2977 Up Next Emptying: Logging Additions
  Modules/Server/Sources/PocketCastsServer/Private/UserDefaults+DataProtection.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/UpNextSyncTask.swift
  podcasts/AppDelegate+SiriShortcuts.swift
  podcasts/PlaybackManager.swift
  podcasts/PlaybackQueue.swift
  podcasts/Up Next History/UpNextHistoryModel.swift
Labels: Up Next, Logging

#2985 [Improve Podcast Sorting] Add new Feature Flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/PodcastListViewController+Search.swift
Labels: [Project] Improving Podcast Sorting

#2987 [Hotfix] General fixes for 7.86.2
  podcasts/AppDelegate+Analytics.swift
  podcasts/PodcastHeaderModel.swift
  podcasts/PodcastHeaderView.swift
Labels: [Type] Bug

#2988 Merge release/7.86.2 into release/7.87
  podcasts/AppDelegate+Analytics.swift
Labels: Releases

#2984 [Notifications Revamp] Onboarding staff picks
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/DeveloperMenu.swift
  podcasts/DiscoverCollectionViewController+DiscoverDelegate.swift
  podcasts/DiscoverSummaryProtocol.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/MainTabBarController.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
  podcasts/Notifications/NotificationsCoordinator+AnalyticsAdapter.swift
  podcasts/Notifications/NotificationsCoordinator.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  scripts/notifications/discover-staff-picks.apns
Labels: [Project] Notifications Revamp

#3000 [Enhancement] Improve AppsFlyer setup
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerAdapter.swift
Labels: [Project] Newform AppsFlyer Integration

#3001 Merge release/7.87 into trunk
  Modules/Server/Sources/PocketCastsServer/Private/UserDefaults+DataProtection.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/UpNextSyncTask.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileRotating.swift
  config/Version.xcconfig
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerAdapter.swift
  podcasts/AppDelegate+Analytics.swift
  podcasts/AppDelegate+SiriShortcuts.swift
  podcasts/PlaybackManager.swift
  podcasts/PlaybackQueue.swift
  podcasts/Up Next History/UpNextHistoryModel.swift
  podcasts/WatchManager+Send.swift
  podcasts/WatchManager.swift
  podcasts/ca.lproj/Localizable.strings
Labels: Releases

#2996 [Notifications Revamp] Notification permissions settings
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Common SwiftUI/BannerView.swift
  podcasts/DisclosureCell.swift
  podcasts/NotificationsHelper.swift
  podcasts/NotificationsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/SwitchCell.swift
  podcasts/UIApplication+OpenStandardURLs.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Notifications Revamp

#3003 Recommendations: Add Feature Flag
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Feature Flag, [Project] Improving Podcast Recommendations

#3004 [Encourage Account Creation] Update Banner view
  podcasts.xcodeproj/project.pbxproj
  podcasts/Common SwiftUI/BannerView.swift
  podcasts/CommonImages.xcassets/cross-little.imageset/Contents.json
  podcasts/CommonImages.xcassets/cross-little.imageset/cross-little.svg
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerView.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerViewCoordinator.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerViewModel.swift
Labels: [Project] Encourage Account Creation

#3005 Watch Log crash fix
  podcasts/WatchManager+Send.swift
  podcasts/WatchManager.swift
Labels: crash

#3014 Merge release/7.87 into trunk
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts/Common SwiftUI/BannerView.swift
  podcasts/CommonImages.xcassets/cross-little.imageset/Contents.json
  podcasts/CommonImages.xcassets/cross-little.imageset/cross-little.svg
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerView.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerViewCoordinator.swift
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerViewModel.swift
  podcasts/WatchManager+Send.swift
  podcasts/WatchManager.swift
  podcasts/ca.lproj/Localizable.strings
Labels: Releases

#3020 Remove watch log on send
  podcasts/WatchManager.swift
Labels: [Area] watchOS

#3015 Recommendations: Authentication property handling
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
  podcasts/CategoryPodcastsViewController.swift
  podcasts/CategorySummaryViewController.swift
  podcasts/CollectionSummaryViewController.swift
  podcasts/DiscoverCollectionViewController+Categories.swift
  podcasts/DiscoverCollectionViewController+DiscoverDelegate.swift
  podcasts/DiscoverCollectionViewController.swift
  podcasts/DiscoverEpisodeViewModel.swift
  podcasts/DiscoverItem+Helper.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/FeaturedSummaryViewController.swift
  podcasts/LargeListSummaryViewController.swift
  podcasts/NetworkSummaryViewController.swift
  podcasts/NetworkViewController.swift
  podcasts/SinglePodcastViewController.swift
  podcasts/SmallPagedListSummaryViewController.swift
  podcasts/SupporterContributionsViewController.swift
  podcasts/SupporterGratitudeViewController.swift
  podcasts/SupporterPodcastViewController.swift
Labels: [Project] Improving Podcast Recommendations

#3021 Merge release/7.87 into trunk
  config/Version.xcconfig
  podcasts/WatchManager.swift
Labels: Releases

#2998 [Improve Podcast Sorting] Add new sort option
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Folder.swift
  Modules/Server/Sources/PocketCastsServer/Private/ServerConverter.swift
  Pocket Casts Watch App/SortOption.swift
  podcasts/Enumerations.swift
  podcasts/FolderViewController.swift
  podcasts/HomeGridDataHelper.swift
  podcasts/PodcastListViewController+Search.swift
  podcasts/PodcastListViewController.swift
  podcasts/PodcastManager.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Improving Podcast Sorting

#3026 [Improving Sorting Option] Enable FF and Update Changelog
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Improving Podcast Sorting

#2840 GRDB: ensure FMDB and GRDB compatibility
  Modules/DataModel/Sources/PocketCastsDataModel/Private/DB/GRDB/GRDBDatabase.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Episode+fromDictionary.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDictionary.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/AutoAddCandidatesDataManagerTests.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/DataManager+TestDatabase.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/FmdbGrdbTests.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/Podcast+fixture.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/PodcastDataManagerTests.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager.swift
  PocketCastsTests/Extensions/FMDatabaseQueue+Test.swift
  PocketCastsTests/Helpers/DBTestCase.swift
  PocketCastsTests/Tests/Utilities/DownloadManagerTests.swift
  PocketCastsTests/Tests/Utilities/PodcastManagerTests.swift
Labels: [Type] Tech Debt

#3007 GRDB: fix crash on `BookmarkDataManager`
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Bookmarks/BookmarkDataManager.swift
Labels: [Type] Tech Debt

#3009 GRDB: enable for `DEBUG` environment
  Modules/DataModel/Tests/PocketCastsDataModelTests/DataManager+TestDatabase.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  PocketCastsTests/Extensions/FMDatabaseQueue+Test.swift
  PocketCastsTests/Helpers/DBTestCase.swift
  PocketCastsTests/Tests/Utilities/DownloadManagerTests.swift
  PocketCastsTests/Tests/Utilities/PodcastManagerTests.swift
Labels: [Type] Tech Debt

#3022 [Recommendations] Authentication failure handling
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  podcasts/ContentUnavailableConfiguration.swift
  podcasts/DeveloperMenu.swift
  podcasts/DiscoverCellType.swift
  podcasts/DiscoverCollectionViewController.swift
Labels: Discover, [Project] Improving Podcast Recommendations

#3006 [Notifications Revamp] ReEngagement notifications
  podcasts/Constants.swift
  podcasts/DeveloperMenu.swift
  podcasts/Notifications/NotificationsCoordinator+AnalyticsAdapter.swift
  podcasts/Notifications/NotificationsCoordinator.swift
  podcasts/NotificationsViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  scripts/notifications/reengagement_weekly.apns
Labels: [Project] Notifications Revamp

#3024 [Improve podcast Sorting] Add tooltip and Analytics
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/PodcastListViewController+Tip.swift
  podcasts/PodcastListViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Improving Podcast Sorting

#3027 Recommendations: Discover "Large list with podcast" display style
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/LargeListSummaryCellHeaderView.swift
  podcasts/LargeListSummaryViewController.swift
  podcasts/LargeListSummaryViewController.xib
Labels: Discover, [Project] Improving Podcast Recommendations

#3011 [Notifications Revamp] Notification Trending
  podcasts/Constants.swift
  podcasts/DeveloperMenu.swift
  podcasts/Notifications/NotificationsCoordinator+AnalyticsAdapter.swift
  podcasts/Notifications/NotificationsCoordinator.swift
  podcasts/NotificationsViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
  scripts/notifications/discover-trending.apns
Labels: [Project] Notifications Revamp

#3034 [Winback Updates] Update Available Plans
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlanRow.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansView.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansViewModel.swift
  podcasts/IAPHelper.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Plus/SubscriptionPriceAndOfferView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Winback

#3028 Increase Log maximum file size by 10x
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileLog.swift
Labels: [Area] watchOS, Logging

#3044 Merge release/7.87 into trunk
  config/Version.xcconfig
  podcasts/PCMessageSupportViewModel.swift
  podcasts/Zendesk/MessageSupportView.swift
  podcasts/Zendesk/MessageSupportViewModel.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#3046 Merge release/7.88 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#3037 Notifications refactor groups
  podcasts/DeveloperMenu.swift
  podcasts/Notifications/NotificationsCoordinator+AnalyticsAdapter.swift
  podcasts/Notifications/NotificationsCoordinator.swift
  podcasts/NotificationsViewController.swift
Labels: [Project] Notifications Revamp

#3050 [Winback Updates] Add loading button when loading offer
  podcasts/Cancel Subscription/Cancel Subscription/Offer View/CancelSubscriptionWinbackOfferView.swift
Labels: [Project] Winback

#3052 [Newform AppsFlyer Integration] Add FB SDK - 7.87.1 Hotfix
  .configure
  .configure-files/pocket_casts_credentials.json.enc
  PocketCastsTests/Tests/Analytics/AppsFlyerAdapterTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/Analytics/Adapters/Apple ATT/AppTrackingTransparencyController.swift
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerAdapter.swift
  podcasts/Analytics/Adapters/Newform AppsFlyer/AppsFlyerDataProvider.swift
  podcasts/AppDelegate+SiriShortcuts.swift
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/AppDelegate.swift
  podcasts/Credentials/ApiCredentials.tpl
  podcasts/SceneDelegate.swift
Labels: hotfix

#3053 Suggested Folders: Add new upgrade source
  podcasts/Constants.swift
  podcasts/FoldersCoordinator.swift
Labels: Analytics, Suggested Folders

#3054 Merge release/7.87.1 into release/7.88
  podcasts/Constants.swift
  podcasts/FoldersCoordinator.swift
Labels: Releases
