Repository Automattic/pocket-casts-ios, pull requests merged in 2025-08, with the labels that each got.

#3384 Merge release/7.94 into trunk
  config/Version.xcconfig
  podcasts/ca.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
Labels: Releases

#3372 [New onboarding] Tweaks after design review
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Onboarding/Plus/NewUpgrade/Animations/BookmarksAnimationView.swift
  podcasts/Onboarding/Plus/NewUpgrade/Animations/FoldersAnimationView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeProductsView.swift
  podcasts/ShelfActionsViewController+Table.swift
Labels: New Onboarding

#3385 Header cell always have a minimum size of 44
  podcasts/HeadingCell.xib
Labels: [Type] Bug

#3371 [Banner Ads] Design Review tweaks
  podcasts/Common SwiftUI/BannerAdView.swift
  podcasts/NowPlayingPlayerItemViewController.swift
Labels: [Project] Banner Ads

#3368 Handle upsell deep link using subscriptionRequiredPage
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/Constants.swift
Labels: [Feature] Deep Links, [Project] Banner Ads

#3393 [Banner Ads] Only show Banner Ads for non-subscribers
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/PodcastListViewController.swift
Labels: [Project] Banner Ads

#3392 Improved logging and miscellaneous cleanup
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/UpNextHistoryManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts/DownloadManager+Logging.swift
  podcasts/EpisodeManager.swift
  podcasts/Up Next History/UpNextHistoryModel.swift
Labels: Logging

#3374 GRDB: add `read`/`write` methods to `EpisodeDataManager`
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
Labels: [Type] Tech Debt

#3375 GRDB: add `read`/`write` methods to `PodcastDataManager`
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
Labels: [Type] Tech Debt

#3395 [Playlists] Smart Rule: Podcasts
  podcasts/FilterChipCollectionView.swift
  podcasts/PodcastFilterOverlayController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Playlists

#3378 GRDB: add `read`/`write` methods to `UpNextChangesDataManager`
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/UpNextChangesDataManager.swift
Labels: [Type] Tech Debt

#3380 GRDB: add `read`/`write` methods to `AutoAddCandidatesDataManager `
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/AutoAddQueueDataManager.swift
Labels: [Type] Tech Debt

#3407 [New Onboarding] Newsletter opt in on Notifications page
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Notifications/NotificationsPermissionsView.swift
  podcasts/Strings+Generated.swift
  podcasts/SwiftUI/SelectCircleButtonStyle.swift
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3403 Update ASC description
  fastlane/AppStoreStrings.po
  fastlane/metadata/default/description.txt
Labels: Update

#3409 [Playlists] Starred Smart rule screen
  podcasts.xcodeproj/project.pbxproj
  podcasts/FilterChipCollectionView.swift
  podcasts/PodcastFilterOverlayController.swift
  podcasts/SmartRuleToggleHeaderView.swift
  podcasts/StarredFilterOverlayController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Playlists

#3389 GRDB: add `read`/`write` methods to `FolderHistoryManager` and `UpNextHistoryManager`
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/FolderHistoryManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/UpNextHistoryManager.swift
Labels: [Type] Tech Debt

#3411 [Playlists] UI adjustments
  podcasts/DownloadFilterOverlayController.swift
  podcasts/EpisodeFilterOverlayController.swift
  podcasts/EpisodePreviewCell.swift
  podcasts/EpisodePreviewCell.xib
  podcasts/FilterChipCollectionView.swift
  podcasts/FilterDurationViewController.swift
  podcasts/FilterDurationViewController.xib
  podcasts/MediaFilterOverlayController.swift
  podcasts/PCViewController.swift
  podcasts/PlaylistCell.swift
  podcasts/PlaylistsViewController+Table.swift
  podcasts/PlaylistsViewController.swift
  podcasts/PodcastFilterOverlayController.swift
  podcasts/ReleaseDateFilterOverlayController.swift
  podcasts/SmartRuleToggleHeaderView.swift
  podcasts/StarredFilterOverlayController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Playlists

#3413 [Banner Ads] Banner ad spacing on podcast list
  podcasts/PodcastListViewController+CollectionView.swift
Labels: [Project] Banner Ads

#3417 Merge release/7.95 into trunk
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  config/Version.xcconfig
  fastlane/metadata/de-DE/description.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/es-ES/description.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/description.txt
  fastlane/metadata/it/description.txt
  fastlane/metadata/ja/description.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/nl-NL/description.txt
  fastlane/metadata/pt-BR/description.txt
  fastlane/metadata/ru/description.txt
  fastlane/metadata/sv/description.txt
  fastlane/metadata/zh-Hans/description.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/description.txt
  fastlane/metadata/zh-Hant/release_notes.txt
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/PCBundleDoc.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#3414 Fix watch logging
  Modules/Utils/Sources/PocketCastsUtils/Logging/FileLog.swift
  podcasts/WatchManager+Send.swift
  podcasts/WatchManager.swift
Labels: [Area] watchOS, Logging

#3420 Update CHANGELOG with Lock Screen Scrubber fix
  CHANGELOG.md
Labels: Changelog

#3418 Add a share button to Transcripts
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/TranscriptViewController.swift
Labels: [Type] Enhancement

#3419 [New Onboarding] Account creation/login changes
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppTheme.swift
  podcasts/Onboarding/Login/LoginButtonStyles.swift
  podcasts/Onboarding/Login/LoginLandingView.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Strings+Generated.swift
  podcasts/Styles.swift
  podcasts/SyncSigninView.swift
  podcasts/SyncSigninViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3421 [New Onboarding] Recommendations screen
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
  podcasts/DeveloperMenu.swift
  podcasts/Onboarding/DiscoverPodcastsGridView.swift
  podcasts/Onboarding/FadeGradientModifier.swift
  podcasts/Onboarding/Import/ImportLandingView.swift
  podcasts/Onboarding/Import/ImportViewModel.swift
  podcasts/Onboarding/OnboardingRecommendationsView.swift
  podcasts/Onboarding/PodcastSubscribeButton.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Changelog, New Onboarding

#3432 Do not switch file if we already have the streamed file being played
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/PlaybackManager.swift
Labels: playback

#3429 [Playlists] Smart Playlist - Part 2
  podcasts.xcodeproj/project.pbxproj
  podcasts/EpisodeDateHelper.swift
  podcasts/ListEpisode.swift
  podcasts/New Creation/New Preview/PlaylistPreviewViewController+Table.swift
  podcasts/New Creation/New Preview/PlaylistPreviewViewController.swift
  podcasts/New Creation/New Preview/PlaylistPreviewViewModel.swift
  podcasts/New Creation/New Preview/Rules/Episode Preview/PlaylistEpisodePreviewRowView.swift
  podcasts/New Creation/New Preview/Rules/SmartPlaylistRuleRowView.swift
  podcasts/New Creation/New Preview/Rules/SmartPlaylistRulesCell.swift
  podcasts/New Creation/New Preview/Rules/SmartPlaylistRulesContainerView.swift
  podcasts/New Creation/New Preview/Rules/SmartPlaylistRulesView.swift
  podcasts/PodcastFilterOverlayController.swift
  podcasts/StarredFilterOverlayController.swift
Labels: [Project] Playlists

#3433 Merge release/7.96 into trunk
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
  podcasts/PlaybackManager.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#3437 Turn off specific sessions options that do not work on AppClips
  podcasts/DownloadManager.swift
  podcasts/MediaExporterResourceLoaderDelegate.swift
Labels: [Project] App Clip, Bug

#3447 Watch Logging crash fix
  podcasts/WatchManager+Send.swift
  podcasts/WatchManager.swift
Labels: [Area] watchOS

#3446 Add FF to enable theme properties
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/Analytics/Analytics.swift
Labels: Enhancement

#3435 [New Onboarding] Onboarding flow changes
  podcasts/DeveloperMenu.swift
  podcasts/End of Year/StoriesConfiguration.swift
  podcasts/End of Year/StoriesModel.swift
  podcasts/End of Year/Views/StoriesView.swift
  podcasts/Onboarding/Import/ImportDetailsView.swift
  podcasts/Onboarding/Intro Carousel/IntroCarouselView.swift
  podcasts/Onboarding/Login/LoginLandingHostingController.swift
  podcasts/Onboarding/Login/LoginLandingView.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/Models/PlusPurchaseModel.swift
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/OnboardingRecommendationsView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/PCSearchView.swift
  podcasts/Referrals/ReferralsCoordinator.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3442 [New Onboarding] Analytics updates for the Account Creation onboarding changes
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Onboarding/DiscoverPodcastsGridView.swift
  podcasts/Onboarding/Intro Carousel/IntroCarouselView.swift
  podcasts/Onboarding/LoginCoordinator.swift
  podcasts/Onboarding/OnboardingRecommendationsView.swift
Labels: New Onboarding

#3448 [Banner Ads] Split feature flag for podcast & player
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeTier.swift
  podcasts/PodcastListViewController.swift
Labels: [Project] Banner Ads
