Repository Automattic/pocket-casts-ios, pull requests merged in 2025-09, with the labels that each got.

#3456 Merge release/7.96 into trunk
  config/Version.xcconfig
Labels: Releases

#3431 [New onboarding] Interests UI
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/DeveloperMenu.swift
  podcasts/Onboarding/InterestButton.swift
  podcasts/Onboarding/InterestsView.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3462 [New onboarding] Interests screen analytics
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Onboarding/InterestsView.swift
Labels: New Onboarding

#3459 [Banner Ads] Enable Feature Flags
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Banner Ads

#3466 [New onboarding] Interests button animation
  podcasts/Onboarding/InterestButton.swift
  podcasts/Onboarding/InterestsView.swift
Labels: Onboarding

#3470 GRDB: default `Bool` to false
  Modules/DataModel/Sources/PocketCastsDataModel/Private/DB/GRDB/GRDBResultSet.swift
Labels: [Type] Bug

#3451 [Playlist] Smart Playlist detail and options
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeFilterDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/PlaylistHelper.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/PlaylistQueryBuilder.swift
  Pocket Casts Watch App/WatchSourceViewModel.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Array+Episode.swift
  podcasts/CarPlaySceneDelegate+Interaction.swift
  podcasts/EpisodeTableHelper.swift
  podcasts/EpisodesDataManager.swift
  podcasts/FilterEditOptionsViewController.swift
  podcasts/FilterManager.swift
  podcasts/ListEpisode.swift
  podcasts/New Creation/New Preview/PlaylistPreviewViewController.swift
  podcasts/New Creation/New Preview/PlaylistPreviewViewModel.swift
  podcasts/New Detail/Playlist Header/PlaylistBlurHeaderView.swift
  podcasts/New Detail/Playlist Header/PlaylistHeaderView.swift
  podcasts/New Detail/Playlist Header/PlaylistHeaderViewCell.swift
  podcasts/New Detail/PlaylistDetailViewController+EditActions.swift
  podcasts/New Detail/PlaylistDetailViewController+EmptyState.swift
  podcasts/New Detail/PlaylistDetailViewController+MultiSelect.swift
  podcasts/New Detail/PlaylistDetailViewController+Observers.swift
  podcasts/New Detail/PlaylistDetailViewController+Search.swift
  podcasts/New Detail/PlaylistDetailViewController+Swipe.swift
  podcasts/New Detail/PlaylistDetailViewController+TableView.swift
  podcasts/New Detail/PlaylistDetailViewController.swift
  podcasts/New Detail/PlaylistDetailViewModel.swift
  podcasts/PlaybackManager.swift
  podcasts/PlaylistArtworkView.swift
  podcasts/PlaylistCellView.swift
  podcasts/PlaylistCellViewModel.swift
  podcasts/PlaylistsViewController.swift
  podcasts/SiriShortcutsManager.swift
  podcasts/Strings+Generated.swift
  podcasts/SwiftUI/AsyncImageView.swift
  podcasts/WatchManager.swift
  podcasts/WidgetHelper.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Playlists

#3471 Merge release/7.97 into trunk
  Modules/DataModel/Sources/PocketCastsDataModel/Private/DB/GRDB/GRDBResultSet.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
  podcasts/WatchManager+Send.swift
  podcasts/WatchManager.swift
  podcasts/ca.lproj/Localizable.strings
Labels: Releases

#3477 [Playlists] Base for showing manual Playlists
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeFilterDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Pocket Casts Watch App/WatchSourceViewModel.swift
  podcasts/BadgeSettingsViewController.swift
  podcasts/CarPlaySceneDelegate+Tabs.swift
  podcasts/CommonImages.xcassets/filter_new_episode.imageset/Contents.json
  podcasts/CommonImages.xcassets/filter_new_episode.imageset/plus-circle-ol.svg
  podcasts/DownloadSettingsViewController.swift
  podcasts/EpisodesDataManager.swift
  podcasts/FilterManager.swift
  podcasts/FilterPreviewViewController.swift
  podcasts/New Creation/New Playlist/NewPlaylistViewController.swift
  podcasts/New Creation/New Preview/PlaylistPreviewViewModel.swift
  podcasts/New Detail/Playlist Header/PlaylistHeaderView.swift
  podcasts/New Detail/PlaylistDetailViewController+EmptyState.swift
  podcasts/New Detail/PlaylistDetailViewModel.swift
  podcasts/PlaylistCellViewModel.swift
  podcasts/PlaylistManager.swift
  podcasts/PlaylistRefreshOperation.swift
  podcasts/PlaylistViewController.swift
  podcasts/PlaylistsViewController.swift
  podcasts/PodcastSettingsViewController+Table.swift
  podcasts/ShortcutManager.swift
  podcasts/SiriSettingsViewController.swift
  podcasts/StarredFilterOverlayController.swift
  podcasts/Strings+Generated.swift
  podcasts/WatchManager.swift
  podcasts/WidgetHelper.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Playlists

#3478 [Fix] Fix constraint for podcast chooser
  CHANGELOG.md
  podcasts/PodcastChooserViewController.swift
  podcasts/PodcastChooserViewController.xib
  podcasts/PodcastFilterOverlayController.swift
Labels: [Type] Bug

#3474 Update watch sync user agent to watchOS
  Pocket Casts Watch App/WatchSyncManager+ServerSyncDelegate.swift
Labels: [Area] watchOS

#3480 Fixes the You Might Like tab reloading when popping back
  CHANGELOG.md
  podcasts/PodcastViewController.swift
Labels: Bug

#3493 Merge release/7.98 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#3485 [Playlists] Podcast and Autodownload settings
  podcasts.xcodeproj/project.pbxproj
  podcasts/DownloadSettingsViewController.swift
  podcasts/FilterSelectionViewController.swift
  podcasts/New Detail/Playlist Header/PlaylistHeaderView.swift
  podcasts/New Detail/PlaylistDetailViewController+Observers.swift
  podcasts/New Detail/PlaylistDetailViewController.swift
  podcasts/New Detail/PlaylistDetailViewModel.swift
  podcasts/PlaylistCell.swift
  podcasts/PlaylistCellView.swift
  podcasts/PlaylistCellViewModel.swift
  podcasts/PlaylistSelectionViewController.swift
  podcasts/PlaylistSelectionViewController.xib
  podcasts/PodcastSettingsViewController+Table.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Playlists

#3494 Remove FF for podcastViewChanges
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/FakeNavViewController.swift
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastHeadingTableCell.xib
  podcasts/PodcastViewController+NetworkLoad.swift
  podcasts/PodcastViewController+TableData.swift
  podcasts/PodcastViewController.swift
Labels: Feature Flag

#3492 [Search improvements] Show podcast and episodes on vertical list
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/New Search/Model/SearchResultsModel.swift
  podcasts/New Search/Views/Results/NewSearchResultsView.swift
  podcasts/New Search/Views/Results/SearchResultCell.swift
  podcasts/New Search/Views/Results/SearchResultsView.swift
  podcasts/New Search/Views/SearchView.swift
  podcasts/PodcastTableCellView.swift
  podcasts/Styles.swift
Labels: Search Improvements

#3499 GRDB FF Removal
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Type] Enhancement

#3503 Fix animation sizing to work correctly when using larger fonts or on smaller devices.
  podcasts/Onboarding/Plus/NewUpgrade/Animations/FoldersAnimationView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
Labels: New Onboarding

#3504 [Bug] Fix About Form background color
  CHANGELOG.md
  podcasts/AboutView.swift
Labels: [Type] Bug

#3502 Don't show gradient when presenting the new flow with title above
  podcasts/Onboarding/Login/LoginLandingView.swift
Labels: Bug

#3498 Remove notifications revamp FF
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/AppDelegate+Analytics.swift
  podcasts/AppDelegate.swift
  podcasts/NavigationManager.swift
  podcasts/NotificationsViewController.swift
  podcasts/Onboarding/OnboardingFlow.swift
Labels: Feature Flag

#3506 [New Onboarding] Layout fix notifications permissions view
  podcasts/DeveloperMenu.swift
  podcasts/Notifications/NotificationsPermissionsView.swift
Labels: New Onboarding

#3507 [Banner ads] Accessibility fix
  podcasts/Common SwiftUI/BannerAdView.swift
  podcasts/NowPlayingPlayerItemViewController.swift
Labels: [Area] Accessibility, [Project] Banner Ads

#3510 Missing generated file update
  podcasts/Strings+Generated.swift
Labels: [Type] Fix

#3511 [Hotfix] Remove banner when the view will appear if necessary
  podcasts/PodcastListViewController.swift
Labels: [Type] Fix

#3515 Merge release/7.97.1 into release/7.98
  CHANGELOG.md
  podcasts/Onboarding/Login/LoginLandingView.swift
  podcasts/PodcastListViewController.swift
Labels: Releases

#3518 [Search Improvements] Add direct play button
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/MainEpisodeActionView.swift
  podcasts/New Search/Views/Results/SearchResultCell.swift
  podcasts/New Search/Views/Results/SearchResultCellModel.swift
  podcasts/PlaybackManager.swift
Labels: Search Improvements

#3523 Update Subscription status for banner ad removal info
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/SubscriptionStatusTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/files.pb.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  Modules/Server/Sources/PocketCastsServer/Public/SubscriptionHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncManager.swift
  podcasts.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/PodcastListViewController.swift
Labels: [Project] Banner Ads

#3527 Merge release/7.98 into trunk
  config/Version.xcconfig
Labels: Releases

#3529 Update swift-protobuf version to 1.31.1
  podcasts.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Dependencies

#3530 [Hotfix] Early reload Subscription status and fix condition to display AD
  Modules/Server/Sources/PocketCastsServer/Public/SubscriptionHelper.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/AppDelegate.swift
Labels: hotfix

#3531 Merge release/7.98 into trunk
  Modules/Server/Sources/PocketCastsServer/Public/SubscriptionHelper.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  podcasts/AppDelegate.swift
Labels: Releases

#3532 Enable the inline bookmarks tab feature flag
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Bookmarks
