Repository Automattic/pocket-casts-ios, pull requests merged in 2025-01, with the labels that each got.

#2590 [Changelog] Update Changelog
  CHANGELOG.md
Labels: Changelog

#2586 Remove logout from background requests
  CHANGELOG.md
  Modules/Server/Sources/PocketCastsServer/Private/TokenHelper.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerConfig.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/AppDelegate.swift
Labels: [Type] Bug

#2595 Merge release/7.79 into trunk
  .buildkite/commands/release-upload.sh
  .buildkite/release-builds.yml
  CHANGELOG.md
  config/Version.xcconfig
Labels: Releases

#2592 App Clip: Remove custom playback effect settings
  Pocket Casts App Clip/Assets.xcassets/AccentColor.colorset/Contents.json
  Pocket Casts App Clip/Assets.xcassets/player_effects_less.imageset/Contents.json
  Pocket Casts App Clip/Assets.xcassets/player_effects_less.imageset/speed-decrease@2x.png
  Pocket Casts App Clip/Assets.xcassets/player_effects_less.imageset/speed-decrease@3x.png
  Pocket Casts App Clip/Assets.xcassets/player_effects_more.imageset/Contents.json
  Pocket Casts App Clip/Assets.xcassets/player_effects_more.imageset/speed-increase@2x.png
  Pocket Casts App Clip/Assets.xcassets/player_effects_more.imageset/speed-increase@3x.png
  Pocket Casts App Clip/Assets.xcassets/player_speed.imageset/Contents.json
  Pocket Casts App Clip/Assets.xcassets/player_speed.imageset/speed@2x.png
  Pocket Casts App Clip/Assets.xcassets/player_speed.imageset/speed@3x.png
  Pocket Casts App Clip/Assets.xcassets/player_trim.imageset/Contents.json
  Pocket Casts App Clip/Assets.xcassets/player_trim.imageset/silence@2x.png
  Pocket Casts App Clip/Assets.xcassets/player_trim.imageset/silence@3x.png
  Pocket Casts App Clip/Assets.xcassets/player_volumeboost.imageset/Contents.json
  Pocket Casts App Clip/Assets.xcassets/player_volumeboost.imageset/volumeboost@2x.png
  Pocket Casts App Clip/Assets.xcassets/player_volumeboost.imageset/volumeboost@3x.png
  podcasts/EffectsViewController.swift
  podcasts/PodcastEffectsViewController+Table.swift
Labels: [Type] Enhancement

#2597 App Clip: Remove App Clip podfile target + deployment target to 15
  Podfile
  Podfile.lock
  podcasts.xcodeproj/project.pbxproj
Labels: [Project] App Clip

#2593 [Winback] Add Analytics events
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Cancel Subscription/Cancel Subscription/Offer View/CancelSubscriptionOfferSuccessView.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansView.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansViewModel.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewModel.swift
  podcasts/CancelConfirmationViewModel.swift
  podcasts/OnlineSupportController.swift
Labels: [Project] Winback

#2599 Merge release/7.79 into trunk
  .buildkite/commands/prototype-upload.sh
  .buildkite/commands/release-upload.sh
Labels: Releases

#2600 App clip: Analytics logging updates
  Pocket Casts App Clip/NowPlayingView.swift
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
Labels: [Project] App Clip

#2594 Add dismiss option to manage downloads banner
  podcasts/DownloadsViewController.swift
  podcasts/ManageDownloadsBannerView.swift
  podcasts/ManageDownloadsCoordinator.swift
Labels: [Project] Download Management

#2604 Remove App Clip from build phases
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts App Clip.xcscheme
Labels: [Project] App Clip

#2605 Set correct color set for text for download banner
  podcasts/ManageDownloadsBannerView.swift
Labels: [Project] Download Management

#2606 Ensure that podcast HTML description is active by default.
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Type] Enhancement

#2607 Merge release/7.80 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2608 [Tooling] Fix `Fastfile` changes being accidentally reverted during a past conflict resolution
  fastlane/Fastfile
Labels: [Type] Tooling

#2612 [AppClips] Re-Enable build phases scheme
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts App Clip.xcscheme
Labels: [Project] App Clip

#2611 Disable End Of The Year 2024
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] End of Year 2024

#2610 CarPlay: only cache the episode image if it exists
  CHANGELOG.md
  podcasts/CarPlayImageHelper.swift
Labels: [Type] Bug, [Area] CarPlay

#2616 Rename Pride Icon to be just Pride
  podcasts/IconSelectorCell.swift
Labels: [Type] Other

#2617 Update project and automation to build with App Clip
  config/PocketCasts.debug.xcconfig
  config/PocketCasts.release.xcconfig
  config/PocketCasts.staging.xcconfig
  fastlane/Fastfile
  podcasts.xcodeproj/project.pbxproj
Labels: [Type] Tooling, [Project] App Clip

#2618 Streamline App Clip removal logic
  fastlane/Fastfile
Labels: [Type] Enhancement, [Type] Tooling

#2620 Podcast rich test: ensure html description main thread
  podcasts/ExpandableLabel.swift
Labels: [Type] Bug, crash

#2619 Rename Lock Screen Scrubbing settings
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Improvements

#2621 Merge release/7.80 into trunk
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  fastlane/Fastfile
  fastlane/Frozen.strings
  podcasts/CarPlayImageHelper.swift
  podcasts/ExpandableLabel.swift
  podcasts/Strings+Generated.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2624 Add remote keys as subtitle
  podcasts/Beta/BetaMenu.swift
Labels: [Type] Enhancement

#2555 Add a configuration to allow the display of the Toast above the mini-player
  podcasts/Common SwiftUI/Toast/Toast.swift
  podcasts/Common SwiftUI/Toast/ToastView.swift
  podcasts/Common SwiftUI/Toast/ToastViewModel.swift
  podcasts/SwiftUI/MiniPlayerPaddingModifier.swift
  podcasts/UpNextViewController.swift
Labels: [Projec] Up Next Shuffle

#2625 [App Clips] Add Associated Domains to App Clips
  Pocket Casts App Clip/Pocket_Casts_App_Clip.entitlements
  podcasts/podcasts.entitlements
  podcasts/podcasts.prototype.entitlements
  podcasts/podcastsDebug.entitlements
Labels: [Project] App Clip

#2638 Track audit - Add missing plus promotion flow events
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/IAPTypes.swift
  podcasts/Onboarding/Plus/Account Prompt/UpgradePrompt.swift
  podcasts/Onboarding/Plus/FeaturesCarousel.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
Labels: Analytics

#2643 Update CTA button to show `Start Free Trial` when a free period promotion is available.
  podcasts/Common SwiftUI/BookmarksLockedStateView.swift
  podcasts/Onboarding/Models/PlusAccountPromptViewModel.swift
  podcasts/Onboarding/Plus/PlusPurchaseModal.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Onboarding/Plus/UpgradeLandingView.swift
Labels: Plus

#2649 Safe access array indexes
  podcasts/PodcastViewController+TableData.swift
Labels: [Type] Bug, crash

#2651 Download banner copy change
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Download Management

#2650 Merge release/7.80 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  podcasts/Common SwiftUI/Toast/Toast.swift
  podcasts/Common SwiftUI/Toast/ToastView.swift
  podcasts/Common SwiftUI/Toast/ToastViewModel.swift
  podcasts/EpisodeDetailViewController.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/PodcastViewController+TableData.swift
  podcasts/ShowNotesPlayerItemViewController.swift
  podcasts/SwiftUI/MiniPlayerPaddingModifier.swift
  podcasts/UpNextViewController.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2646 Track audit - Add missing user files events
  podcasts/AddCustomViewController.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/UploadedViewController.swift
  podcasts/UploadedViewController.xib
  podcasts/UserEpisodeManager.swift
Labels: Analytics

#2648 Add event for dismissing upgrading banner
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/PlusLockedInfoView.swift
Labels: Analytics

#2654 [Winback] Update main title
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Winback

#2652 [Winback] Retry screen
  podcasts/Cancel Subscription/Cancel Subscription/CancelSubscriptionView.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansView.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansViewModel.swift
  podcasts/CancelSubscription.xcassets/cs-yield.imageset/Contents.json
  podcasts/CancelSubscription.xcassets/cs-yield.imageset/cs-yield.svg
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Winback

#2657 Merge release/7.80 into trunk
  config/Version.xcconfig
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Releases

#2658 Track audit: Add missing filter events
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
  podcasts/CreateFilterViewController.swift
  podcasts/DownloadSettingsViewController.swift
  podcasts/FilterEditOptionsViewController.swift
  podcasts/PlaylistViewController+TableData.swift
  podcasts/PlaylistsViewController.swift
Labels: Analytics

#2656 Use new share UI on bookmarks share
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Bookmarks/Episode/BookmarkEpisodeListController.swift
  podcasts/Bookmarks/Player/BookmarksPlayerTabController.swift
  podcasts/Bookmarks/Podcast/BookmarksPodcastListController.swift
  podcasts/Bookmarks/Profile/BookmarksProfileListController.swift
  podcasts/SharingHelper.swift
Labels: [Project] Bookmarks, [Project] Reimagine Sharing

#2659 [Winbck] Fix Plans view background colors
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlanRow.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansView.swift
Labels: [Project] Winback

#2660 Merge release/7.81 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2622 Update woo icon in About screen
  podcasts/AboutView.swift
  podcasts/AboutViewLogos.swift
  podcasts/Settings.xcassets/automattic-logo.imageset/Contents.json
  podcasts/Settings.xcassets/automattic-logo.imageset/automattic-logo.pdf
  podcasts/Settings.xcassets/family_woo_logo.imageset/Contents.json
  podcasts/Settings.xcassets/family_woo_logo.imageset/logo-woo.pdf
  podcasts/Settings.xcassets/family_woo_logo.imageset/woo.png
  podcasts/Settings.xcassets/family_woo_logo.imageset/woo@2x.png
  podcasts/Settings.xcassets/family_woo_logo.imageset/woo@3x.png
  podcasts/Settings.xcassets/family_wp_logo.imageset/Contents.json
  podcasts/Settings.xcassets/family_wp_logo.imageset/WordPress Logo.png
  podcasts/Settings.xcassets/family_wp_logo.imageset/WordPress Logo@2x.png
  podcasts/Settings.xcassets/family_wp_logo.imageset/WordPress Logo@3x.png
Labels: [Type] Enhancement

#2661 Remove the option to share bookmarks for user files.
  CHANGELOG.md
  podcasts/Bookmarks/List/BookmarksListView.swift
Labels: [Project] Bookmarks

#2662 [Analytics audit] Theme usage properties
  PocketCastsTests/Tests/Analytics/AnalyticsAppThemeProviderTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/Analytics.swift
  podcasts/Analytics/AnalyticsAppThemeProvider.swift
  podcasts/AppDelegate+Analytics.swift
Labels: Analytics

#2669 [Winback] Modify cancel confirmation screen
  podcasts/CancelConfirmationView.swift
Labels: [Project] Winback

#2671 Analytics audit: update transcript show event
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/TranscriptViewController.swift
Labels: Analytics

#2666 Analytics audit: Implement bookmark editing missing events
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Bookmarks/Editing/BookmarkEditTitleViewController.swift
  podcasts/Bookmarks/List/BookmarkListViewModel.swift
Labels: Analytics

#2672 Analytics audit: Implement select podcast events
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsCoordinator.swift
  podcasts/AutoAddToUpNextViewController+PodcastSelect.swift
  podcasts/AutoAddToUpNextViewController.swift
  podcasts/DownloadSettingsViewController.swift
  podcasts/FilterChipCollectionView.swift
  podcasts/NotificationsViewController.swift
  podcasts/PodcastChooserViewController.swift
  podcasts/PodcastFilterOverlayController.swift
Labels: Analytics

#2675 Analytics audit: Update general settings events
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/GeneralSettingsViewController.swift
Labels: Analytics

#2688 Use latest ci-toolkit, 3.9.1, to print better logs when caching
  .buildkite/shared-pipeline-vars
Labels: [Type] Tooling

#2682 [Analytics Audit] Add events to the About Screen
  podcasts/AboutView.swift
  podcasts/AboutViewModel.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/LegalAndMoreView.swift
Labels: Analytics

#2681 [Analytics Audit] Podcast view
  podcasts/AboutView.swift
  podcasts/AboutViewModel.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsEpisodeHelper.swift
  podcasts/ExpandableLabel.swift
  podcasts/LegalAndMoreView.swift
  podcasts/PodcastViewController.swift
Labels: Analytics

#2683 [Analytics Audit] Add missing share events
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Sharing/SharingFooterView.swift
  podcasts/Sharing/SharingModal.swift
  podcasts/Sharing/SharingView.swift
Labels: Analytics

#2690 [Analytics Audit] Add the Discover List share button tapped event
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/DiscoverCollectionViewController+DiscoverDelegate.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/ExpandedCollectionViewController.swift
  podcasts/PodcastHeaderListViewController.swift
Labels: Analytics

#2686 [Analytics Audit] OPML import finished property update
  podcasts/OpmlImporter.swift
Labels: Analytics

#2694 [Analytics Audit] Referral Banner dismiss event
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Referrals/Banner/ReferralsClaimBannerTableCell.swift
Labels: Analytics

#2691 [Analytics Audit] Add year param for all EOY events
  podcasts/End of Year/Analytics+story.swift
  podcasts/End of Year/EndOfYear.swift
  podcasts/End of Year/Stories/2023/EpilogueStory2023.swift
  podcasts/End of Year/Stories/2024/EpilogueStory2024.swift
  podcasts/End of Year/Stories/2024/PaidStoryWallView2024.swift
  podcasts/End of Year/Stories/2024/Ratings2024Story.swift
  podcasts/End of Year/Views/EndOfYearModal.swift
  podcasts/End of Year/Views/StoriesView.swift
Labels: Analytics

#2687 Do not close episode details when archiving an episode
  podcasts/EpisodeDetailViewController+Actions.swift
Labels: [Type] Enhancement

#2685 [Winback] Modify the layout to update the text based on the plan frequency and type
  podcasts/Cancel Subscription/Cancel Subscription/CancelSubscriptionView.swift
  podcasts/Cancel Subscription/Cancel Subscription/CancelSubscriptionViewRow.swift
  podcasts/Cancel Subscription/Cancel Subscription/Offer View/CancelSubscriptionOfferSuccessView.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansView.swift
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlansViewModel.swift
  podcasts/Cancel Subscription/CancelSubscriptionOption.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Winback

#2684 Fix HTML description crash
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/ExpandableLabel.swift
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastHeadingTableCell.xib
  podcasts/RichExpandableDescriptionView.swift
Labels: [Type] Fix

#2696 Update twitter in about screen to x.com
  podcasts/AboutView.swift
  podcasts/SocialsHelper.swift
  podcasts/Strings+L10n.swift
Labels: [Type] Fix

#2698 Analytics audit: Add missing sleep timer settings
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/MainTabBarController.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
  podcasts/SleepTimerViewController.swift
  podcasts/SleepTimerViewController.xib
Labels: Analytics, Sleep Timer

#2699 Fix slow loading of bookmarks
  podcasts/Bookmarks/List/BookmarkRowViewModel.swift
Labels: [Project] Bookmarks

#2702 Analytics audit: add remove from listening history events
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsEpisodeHelper.swift
  podcasts/Constants.swift
  podcasts/Enumerations.swift
  podcasts/EpisodeManager.swift
  podcasts/ListeningHistoryViewController.swift
  podcasts/MultiSelectFooterView.swift
  podcasts/MultiSelectHelper.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: Analytics

#2710 Add missing changelog entry
  CHANGELOG.md
Labels: Releases

#2709 [Podcast Feed Reload] Add Reload button
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/EpisodeListSearchController.swift
  podcasts/PodcastFeedViewModel.swift
  podcasts/PodcastViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Podcast Feed Update

#2673 [App Clips] Back Merge
  CHANGELOG.md
  Pocket Casts App Clip/Pocket_Casts_App_Clip.entitlements
  config/PocketCasts.debug.xcconfig
  config/PocketCasts.release.xcconfig
  config/PocketCasts.staging.xcconfig
  fastlane/Fastfile
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts App Clip.xcscheme
  podcasts/Analytics/Adapters/Tracks/TracksAdapter.swift
  podcasts/PlayerContainerViewController.swift
  podcasts/podcasts.entitlements
  podcasts/podcasts.prototype.entitlements
  podcasts/podcastsDebug.entitlements
Labels: [Project] App Clip

#2711 Merge release/7.81 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Analytics/Helpers/AnalyticsEpisodeHelper.swift
  podcasts/Bookmarks/List/BookmarkRowViewModel.swift
  podcasts/Constants.swift
  podcasts/Enumerations.swift
  podcasts/EpisodeManager.swift
  podcasts/GeneralSettingsViewController.swift
  podcasts/ListeningHistoryViewController.swift
  podcasts/MainTabBarController.swift
  podcasts/ManageDownloadsCoordinator.swift
  podcasts/MultiSelectFooterView.swift
  podcasts/MultiSelectHelper.swift
  podcasts/NavigationManager.swift
  podcasts/NavigationProtocol.swift
  podcasts/Settings.swift
  podcasts/SleepTimerViewController.swift
  podcasts/SleepTimerViewController.xib
  podcasts/Strings+Generated.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
Labels: Releases

#2713 Unarchive any bulk episodes marked as unplayed.
  CHANGELOG.md
  podcasts/MultiSelectHelper.swift
Labels: [Type] Bug

#2716 Introduce dismiss policy for Toast view
  podcasts/Common SwiftUI/Toast/Toast.swift
  podcasts/Common SwiftUI/Toast/ToastView.swift
  podcasts/Common SwiftUI/Toast/ToastViewModel.swift
Labels: [Type] Enhancement

#2717 Fix/html description resize
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastViewController+TableData.swift
  podcasts/PodcastViewController.swift
  podcasts/RichExpandableDescriptionView.swift
Labels: [Type] Bug

#2719 Merge release/7.81 into trunk
  config/Version.xcconfig
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastViewController+TableData.swift
  podcasts/PodcastViewController.swift
  podcasts/RichExpandableDescriptionView.swift
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2720 [Tooling] Introduce pipelines to trigger release tasks on CI
  .buildkite/commands/release-build.sh
  .buildkite/release-builds.yml
  .buildkite/release-pipelines/code-freeze.yml
  .buildkite/release-pipelines/finalize-hotfix-release.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix-release.yml
  .buildkite/release-pipelines/publish-release.yml
  fastlane/Fastfile
Labels: [Type] Tooling
