Repository Automattic/pocket-casts-ios, pull requests merged in 2025-02, with the labels that each got.

#2714 [Podcast Feed Reload] Pull Down to Reload feed
  podcasts.xcodeproj/project.pbxproj
  podcasts/CustomRefreshControl.swift
  podcasts/EpisodeListSearchController.swift
  podcasts/PodcastFeedViewModel.swift
  podcasts/PodcastViewController.swift
Labels: [Project] Podcast Feed Update

#2722 Merge release/7.82 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2723 Remove AC from Build Phases
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts App Clip.xcscheme
Labels: [Type] Fix

#2724 Merge release/7.82 into trunk
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts App Clip.xcscheme
  podcasts/ca.lproj/Localizable.strings
Labels: Releases

#2728 [Winback] Update yearly offer description
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Winback

#2725 [Podcast Feed Reload] API implementation
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/MainServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Refresh/RefreshManager.swift
  podcasts/PodcastFeedViewModel.swift
  podcasts/PodcastViewController.swift
Labels: [Project] Podcast Feed Update

#2726 [Podcast Feed Reload] Add Analytics
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/PodcastFeedViewModel.swift
  podcasts/PodcastViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Podcast Feed Update

#2731 [App Clips] Add Build Phases
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts App Clip.xcscheme
  podcasts/NowPlayingPlayerItemViewController.swift
Labels: [Project] App Clip

#2732 Merge release/7.82 into trunk
  config/Version.xcconfig
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/Pocket Casts App Clip.xcscheme
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/Onboarding/Welcome/WelcomeViewModel.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2734 [Tooling] Protect the `release/*` branch with the same settings as `trunk`
  fastlane/Fastfile
Labels: [Type] Tooling

#2735 [Podcast Feed Reload] Add tooltip
  CHANGELOG.md
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Constants.swift
  podcasts/PodcastViewController+NetworkLoad.swift
  podcasts/PodcastViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/TipView.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Podcast Feed Update

#2737 Fix downloads copies errors
  CHANGELOG.md
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/StorageManager.swift
Labels: [Type] Bug, Downloads

#2743 [Tooling] Allow admins to push on release branch
  fastlane/Fastfile
Labels: [Type] Tooling

#2742 [Winback] Remove website line
  podcasts/CancelConfirmationView.swift
Labels: [Project] Winback

#2733 [Winback] Implement offer API
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/WinbackOfferTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Public/API/ApiServerHandler+Winback.swift
  podcasts/Cancel Subscription/Cancel Subscription/CancelSubscriptionView.swift
  podcasts/Cancel Subscription/CancelSubscriptionOption.swift
  podcasts/Cancel Subscription/CancelSubscriptionViewModel.swift
  podcasts/CancelConfirmationView.swift
  podcasts/IAPHelper.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Winback

#2741 [Podcast Feed Reload] Enable feature flag by default
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Podcast Feed Update

#2746 Merge release/7.82 into trunk
  Pocket Casts App Clip/NowPlayingView.swift
  config/Version.xcconfig
  podcasts/PlayerColorHelper.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#2744 Default Player: Fix retain self
  podcasts/DefaultPlayer.swift
Labels: crash, Player

#2751 Add Up Next Shuffle into the list
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-up-next-shuffle.imageset/Contents.json
  podcasts/Onboarding.xcassets/Plus/Plus Feature/plus-feature-up-next-shuffle.imageset/shuffle-paywall.svg
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Enhancement

#2753 Skip translations progress check
  fastlane/Fastfile
Labels: [Type] Tooling, continuous integration

#2750 [Podcast Feed Reload] Check app install state to skip tooltip
  PocketCastsTests/Tests/Analytics/AppLifecyleAnalyticsTests.swift
  podcasts/Analytics/AppLifecyleAnalytics.swift
  podcasts/AppDelegate.swift
Labels: [Project] Podcast Feed Update

#2754 [Tooling] Fix `finalize_release` and the `release/*` branch checkout
  .buildkite/commands/checkout-release-branch.sh
  .buildkite/commands/release-build.sh
  .buildkite/release-pipelines/finalize-hotfix-release.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix-release.yml
Labels: [Type] Tooling

#2755 Merge release/7.82 into trunk
  .buildkite/commands/checkout-release-branch.sh
  .buildkite/commands/release-build.sh
  .buildkite/release-pipelines/finalize-hotfix-release.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix-release.yml
  config/Version.xcconfig
  fastlane/Fastfile
  podcasts/Analytics/Helpers/AnalyticsEpisodeHelper.swift
  podcasts/DownloadManager.swift
  podcasts/ServerSyncManager.swift
Labels: Releases

#2749 [Winback] Enable Feature Flag
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Winback

#2748 Add sync hash table to control episode download cache
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  PocketCastsTests/Tests/Utilities/ThreadSafeDictionaryTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/DownloadManager+URLSessionDelegate.swift
  podcasts/DownloadManager.swift
  podcasts/ThreadSafeDictionary.swift
Labels: [Type] Bug

#2757 Merge release/7.83 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#2761 [Tooling] Fix `publish-release.yml` and `release-upload.sh` not checking out the release branch first
  .buildkite/commands/checkout-release-branch.sh
  .buildkite/commands/release-build.sh
  .buildkite/commands/release-upload.sh
  .buildkite/release-pipelines/new-hotfix-release.yml
  .buildkite/release-pipelines/publish-release.yml
Labels: [Type] Tooling

#2765 [Tooling] Fix `release-upload.sh` parameters
  .buildkite/commands/release-upload.sh
  .buildkite/release-builds.yml
Labels: [Type] Tooling

#2767 [Suggested Folders] Initial screen UI
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/CreateFolderView.swift
  podcasts/PodcastListViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/Styles.swift
  podcasts/SuggestedFoldersView.swift
  podcasts/en.lproj/Localizable.strings
Labels: Suggested Folders

#2769 Do proper return on analytics opt out when not an APPCLIP
  CHANGELOG.md
  podcasts/AnalyticsHelper.swift
Labels: [Type] Bug

#2770 Merge release/7.82.1 into release/7.83
  CHANGELOG.md
  podcasts/AnalyticsHelper.swift
Labels: Releases

#2772 [Suggested Folders] Show suggested folders in grid view
  podcasts.xcodeproj/project.pbxproj
  podcasts/FolderPreviewView.swift
  podcasts/FolderPreviewWrapper.swift
  podcasts/GridFoldersView.swift
  podcasts/SuggestedFoldersView.swift
Labels: Suggested Folders

#2758 Remove supporter badge UI code from Podcast detail
  podcasts/PodcastHeadingTableCell.swift
  podcasts/PodcastHeadingTableCell.xib
  podcasts/PodcastViewController.swift
Labels: [Type] Tech Debt

#2776 [Suggested folders] Show suggested folder podcast list
  podcasts.xcodeproj/project.pbxproj
  podcasts/GridFoldersView.swift
  podcasts/PodcastImageViewWrapper.swift
  podcasts/Styles.swift
  podcasts/SuggestedFolderPodcastView.swift
  podcasts/SuggestedFoldersView.swift
  podcasts/SwiftUI/CustomHorizontalMargin.swift
  podcasts/SwiftUI/NavigationContainer.swift
Labels: Suggested Folders

#2771 App Clip & Sharing: update for new URLs
  Pocket Casts App Clip/Pocket_Casts_App_Clip.entitlements
  podcasts/podcasts.entitlements
  podcasts/podcasts.prototype.entitlements
  podcasts/podcastsDebug.entitlements
Labels: [Type] Enhancement

#2781 App Clip/App Links: add changes to 7.83
  Pocket Casts App Clip/Pocket_Casts_App_Clip.entitlements
  podcasts/podcasts.entitlements
  podcasts/podcasts.prototype.entitlements
  podcasts/podcastsDebug.entitlements
Labels: [Type] Enhancement

#2784 Add App Clip and App Link changes to 7.82.2
  Pocket Casts App Clip/Pocket_Casts_App_Clip.entitlements
  podcasts/podcasts.entitlements
  podcasts/podcasts.prototype.entitlements
  podcasts/podcastsDebug.entitlements
Labels: [Type] Enhancement

#2785 Merge release/7.82.2 into release/7.83
  podcasts/podcasts.entitlements
  podcasts/podcasts.prototype.entitlements
  podcasts/podcastsDebug.entitlements
Labels: Releases

#2777 Implement suggested folders upsell view
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/PodcastListViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/SuggestedFoldersUpSellView.swift
  podcasts/en.lproj/Localizable.strings
Labels: Suggested Folders

#2791 Merge release/7.83 into trunk
  config/Version.xcconfig
  podcasts/podcasts.entitlements
  podcasts/podcasts.prototype.entitlements
  podcasts/podcastsDebug.entitlements
  podcasts/sv.lproj/Localizable.strings
Labels: Releases

#2790 [Suggested folders] Code reorganization
  podcasts.xcodeproj/project.pbxproj
  podcasts/FoldersCoordinator.swift
  podcasts/GridFoldersView.swift
  podcasts/PodcastListViewController.swift
  podcasts/SuggestedFoldersModel.swift
  podcasts/SuggestedFoldersView.swift
Labels: Suggested Folders

#2792 [Suggested folders] Apply suggestions to the database
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/FoldersCoordinator.swift
  podcasts/SuggestedFolderPodcastView.swift
  podcasts/SuggestedFoldersModel.swift
  podcasts/SuggestedFoldersUpSellView.swift
  podcasts/SuggestedFoldersView.swift
Labels: Suggested Folders
