Repository Automattic/pocket-casts-ios, pull requests merged in 2025-10, with the labels that each got.

#3520 [Playlists] Handle custom order
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PlaylistDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/PlaylistQueryBuilder.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/PlaylistEpisodeManipulationTests.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/api.pb.swift
  Modules/Server/Sources/PocketCastsServer/Private/Protobuffer/files.pb.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sync/SyncTask+ServerChanges.swift
  Modules/Server/Tests/PocketCastsServerTests/SyncTaskManualPlaylistTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsDescribable+Modules.swift
  podcasts/DataModel+Strings.swift
  podcasts/New Creation/New Playlist/NewPlaylistViewController.swift
  podcasts/New Creation/New Preview/Rules/Episode Preview/PlaylistEpisodePreviewRowView.swift
  podcasts/New Creation/New Preview/Rules/SmartPlaylistRulesView.swift
  podcasts/New Detail/Custom Order/PlaylistDetailCustomOrderViewController.swift
  podcasts/New Detail/Custom Order/PlaylistEpisodePreviewCell.swift
  podcasts/New Detail/PlaylistDetailViewController+EditActions.swift
  podcasts/New Detail/PlaylistDetailViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Playlists

#3540 Unpin dev team from Xcode project file to fix prototype builds
  podcasts.xcodeproj/project.pbxproj
Labels: [Type] Tooling

#3541 Unpin dev team from Xcode project file
  podcasts.xcodeproj/project.pbxproj
Labels: [Type] Tooling

#3538 Keep downloads & Up Next queue on unsubscribe
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PlaylistDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/PlaylistQueryBuilder.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/PlaylistQueryBuilderTests.swift
  Modules/DataModel/Tests/PocketCastsDataModelTests/SQLiteValidator.swift
  podcasts/PodcastManager+Cleanup.swift
  podcasts/PodcastManager+Delete.swift
Labels: Up Next

#3539 Re-arrange OR condition for Banner AD feature flag
  Modules/Server/Sources/PocketCastsServer/Public/SubscriptionHelper.swift
  podcasts/NowPlayingPlayerItemViewController.swift
Labels: [Type] Enhancement

#3525 [Search Improvements] Predictive search
  Modules/Server/Sources/PocketCastsServer/Public/Search/PodcastSearchTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/Search/PredictiveSearchTask.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerConstants.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/CommonImages.xcassets/search.imageset/Contents.json
  podcasts/New Search/Helpers/SearchAnalyticsHelper.swift
  podcasts/New Search/Model/SearchResultsModel.swift
  podcasts/New Search/SearchResultsViewController.swift
  podcasts/New Search/Views/Results/NewSearchResultsView.swift
  podcasts/New Search/Views/Results/PredictiveList.swift
  podcasts/New Search/Views/Results/SearchResultsView.swift
  podcasts/PCSearchBarController.swift
  podcasts/Settings.swift
Labels: Search Improvements

#3542 Move Up Next queue change to 7.100 release in Changelog
  CHANGELOG.md
Labels: Changelog

#3545 [Playlists] Add episode search
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/EpisodeDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/PodcastDataManager.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  podcasts/EpisodeTableHelper.swift
  podcasts/EpisodesDataManager.swift
  podcasts/New Search/Views/Results/LocalSearchCoordinator.swift
  podcasts/New Search/Views/Results/LocalSearchView.swift
  podcasts/New Search/Views/Results/LocalSearchViewModel.swift
Labels: [Project] Playlists
