Repository Automattic/pocket-casts-ios, pull requests merged in 2025-06, with the labels that each got.

#3219 [Banner Ads] Add Feature Flag
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Banner Ads

#3220 [Fix] Fix crash on Core Audio task
  podcasts/AudioReadTask.swift
Labels: crash

#3226 [Beta] Changelog Update
  CHANGELOG.md
Labels: Changelog

#3221 [Banner Ads] Podcast list
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Common SwiftUI/BannerAdView.swift
  podcasts/PodcastListViewController+CollectionView.swift
  podcasts/PodcastListViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Banner Ads

#3232 [CI] Update CI to use Xcode 16.4
  .buildkite/shared-pipeline-vars
  README.md
Labels: continuous integration

#3234 Provision SwiftLint via SwiftPM
  .swiftlint.yml
  BuildTools/Empty.swift
  BuildTools/Package.resolved
  BuildTools/Package.swift
  Makefile
  Podfile
  Podfile.lock
  podcasts.xcodeproj/project.pbxproj
Labels: [Type] Tooling

#3229 Fix crash on accessing DownloadManagers cache dictionaries
  podcasts/DownloadManager.swift
  podcasts/ThreadSafeDictionary.swift
Labels: crash

#3242 [Transcript in Episode View] Update CHANGELOG and enable FF
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Project] Transcripts, [Project] Transcript Enhancement

#3245 Merge release/7.90 into trunk
  config/Version.xcconfig
  podcasts/ca.lproj/Localizable.strings
Labels: Releases

#3238 Update SwiftGen to latest version via CocoaPods
  Podfile.lock
  podcasts/Strings+Generated.swift
  podcasts/Strings+L10n.swift
Labels: [Type] Tooling

#3236 [SPM] Adopt SPM for Googlecast
  Podfile
  Podfile.lock
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: [Type] Tech Debt

#3215 Feature Flag: fix a logic error that might prevent flag values to be applied
  podcasts/AppDelegate.swift
Labels: [Type] Bug

#3243 Removes Discover Collection View redesign Feature Flag
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/CategoryPodcastsViewController.swift
  podcasts/DiscoverViewController+CategoryRedesign.swift
  podcasts/DiscoverViewController+DiscoverDelegate.swift
  podcasts/DiscoverViewController+Search.swift
  podcasts/DiscoverViewController.swift
  podcasts/DiscoverViewController.xib
  podcasts/MainTabBarController.swift
Labels: [Project] Discover Collection View, Feature Flag

#3247 Merge release/7.91 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#3253 [Fix] Fix missing constraint
  podcasts/PlayerContainerViewController.xib
Labels: [Type] Bug

#3254 Merge release/7.91 into trunk
  config/Version.xcconfig
  podcasts/PlayerContainerViewController.xib
Labels: Releases

#3239 Use SwiftPM to provision SwiftGen
  .buildkite/commands/shared_setup.sh
  BuildTools/Package.resolved
  BuildTools/Package.swift
  Makefile
  Podfile
  Podfile.lock
  podcasts.xcodeproj/project.pbxproj
Labels: [Type] Tooling

#3241 Deintegrate CocoaPods
  .buildkite/commands/shared_setup.sh
  .gitignore
  Gemfile
  Gemfile.lock
  Makefile
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ReferralGetCodeTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/ReferralValidateTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/RetrieveRatingsTask.swift
  Modules/Server/Sources/PocketCastsServer/Private/API Tasks/WinbackOfferTask.swift
  Podfile
  Podfile.lock
  README.md
  fastlane/Fastfile
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  podcasts.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  podcasts.xcworkspace/contents.xcworkspacedata
  podcasts.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  podcasts.xcworkspace/xcshareddata/podcasts.xccheckout
  podcasts.xcworkspace/xcshareddata/podcasts.xcscmblueprint
  podcasts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: [Type] Tooling

#3246 [Banner ads] Tracking
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/AnalyticsHelper.swift
  podcasts/Common SwiftUI/BannerAdView.swift
  podcasts/HomeGridListItem.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/PodcastListViewController+CollectionView.swift
  podcasts/PodcastListViewController.swift
Labels: [Project] Banner Ads

#3251 [Banner Ads] Add "No Banner Ads" to upgrade screen
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Banner Ads

#3259 [Banner Ads] Only show banner ads upgrade item when flag is enabled
  podcasts/Onboarding/Plus/Account Prompt/PlusAccountUpgradePrompt.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
Labels: [Project] Banner Ads

#3258 Remove `ReleaseNotesViewController.swift` from root
  ReleaseNotesViewController.swift
Labels: [Type] Tech Debt

#3266 [Transcript] Address feedback
  podcasts/EpisodeDetailViewController+ShowNotes.swift
  podcasts/EpisodeDetailViewController.swift
  podcasts/GeneratedTranscriptsPremiumOverlay.swift
  podcasts/ShowNotesFormatter.swift
  podcasts/Strings+Generated.swift
  podcasts/TranscriptExcerptView.swift
  podcasts/TranscriptViewController.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Transcripts, [Project] Transcript Enhancement

#3263 New discovery network guest cell
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/ArrayExtension.swift
  podcasts/DiscoverCellType.swift
  podcasts/DiscoveryPageIndicatorView.swift
  podcasts/HorizontalCollectionList.swift
  podcasts/HorizontalCollectionListViewController.swift
Labels: Discovery Network Highlight Redesign

#3267 [Smart categories] Add category recommendations
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  PocketCastsTests/Tests/Discover/DiscoverItemObservableTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Categories/CategoriesSelectorView.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
Labels: [Epic] Smart Categories

#3273 [Bug] Fix description title tag
  podcasts/EpisodeDetailViewController+ShowNotes.swift
  podcasts/ShowNotesFormatter.swift
Labels: [Type] Bug

#3275 GRDB: remove `withoutActuallyEscaping`
  Modules/DataModel/Sources/PocketCastsDataModel/Private/DB/FMDB/FMDBQueue.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Private/DB/GRDB/GRDBQueue.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Type] Tech Debt

#3276 Add individual cell types for discover items
  podcasts/Array+DiscoverItem.swift
  podcasts/DiscoverCellType.swift
  podcasts/DiscoverCollectionViewController+Search.swift
  podcasts/DiscoverCollectionViewController.swift
Labels: Discover, [Type] Fix

#3284 Merge release/7.92 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#3282 Fix #2851: Folders History title
  podcasts/Folder History/FolderHistoryView.swift
Labels: [Type] Fix

#3291 Activate new guest network redesign
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: Discovery Network Highlight Redesign

#2502 Serial show support
  CHANGELOG.md
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Enums.swift
  Modules/DataModel/Sources/PocketCastsDataModel/Public/Model/Podcast+fromDictionary.swift
  Modules/Server/Sources/PocketCastsServer/Public/ServerPodcastManager+Update.swift
  Pocket Casts Watch App/PodcastEpisodeListViewModel.swift
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Enumerations.swift
  podcasts/EpisodeTableHelper.swift
  podcasts/EpisodesDataManager.swift
  podcasts/HeadingCell.swift
  podcasts/HeadingCell.xib
  podcasts/ListHeader.swift
  podcasts/PodcastViewController+TableData.swift
  podcasts/PodcastViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Enhancement
