Repository Automattic/pocket-casts-ios, pull requests merged in 2025-07, with the labels that each got.

#3301 Enable 'Warn before using data' by default
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate+Defaults.swift
  podcasts/AppDelegate+UrlHandling.swift
  podcasts/DescriptiveActionAttributedTextView.swift
  podcasts/DescriptiveActionView.swift
  podcasts/EpisodeListSearchController.swift
  podcasts/MultiSelectHelper.swift
  podcasts/NetworkUtils+Helpers.swift
  podcasts/OptionsPicker.swift
  podcasts/OptionsPickerRootController.swift
  podcasts/PlaylistViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Enhancement

#3294 [Smart Categories] Category Visitation Tracking
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  PocketCastsTests/Tests/Discover/DiscoverItemObservableTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Categories/CategoriesSelectorView.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
  podcasts/UserDefaults+Tracking.swift
Labels: [Epic] Smart Categories

#3296 [Smart categories] Handle Sponsored categories
  Modules/Server/Sources/PocketCastsServer/Public/Sharing/Structs/ServerStructs.swift
  PocketCastsTests/Tests/Discover/DiscoverItemObservableTests.swift
  podcasts/Categories/CategoriesSelectorViewController.swift
Labels: [Epic] Smart Categories

#3306 [Transcript In Episode View] Transcript Excerpt redesign
  podcasts/EpisodeDetailViewController+ShowNotes.swift
  podcasts/Strings+Generated.swift
  podcasts/TranscriptExcerptView.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Redesign

#3303 Add Swiftlint hook for claude code
  .claude/settings.json
  .swiftlint.yml
  BuildTools/Package.resolved
Labels: [Type] Tooling

#3316 GRDB: enable only for TestFlight users
  Modules/DataModel/Sources/PocketCastsDataModel/Public/DataManager.swift
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Type] Tech Debt

#3321 Merge release/7.93 into trunk
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  podcasts/de.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#3315 [New Onboarding] New upgrade screen generic
  podcasts.xcodeproj/project.pbxproj
  podcasts.xcodeproj/xcshareddata/xcschemes/pocketcasts.xcscheme
  podcasts/Cancel Subscription/Cancel Subscription/Plans View/CancelSubscriptionPlanRow.swift
  podcasts/IAPHelper.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Plus/NewUpgrade/SubscriptionPurchaseButton.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeBannerView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeFeaturesView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeProductsView.swift
  podcasts/Onboarding/Plus/PlusLandingViewModel.swift
  podcasts/Onboarding/Plus/PlusPurchaseModal.swift
  podcasts/Onboarding/Plus/SubscriptionPriceAndOfferView.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3317 [New onboarding] Upgrade tiers labels
  podcasts.xcodeproj/project.pbxproj
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeFeaturesView.swift
  podcasts/Onboarding/Plus/UpgradeCard.swift
  podcasts/Onboarding/Plus/UpgradeTier.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3320 [New onboarding] Update patron features and use new design
  Pocket Casts Configuration.storekit
  podcasts/AccountViewController+TableView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
  podcasts/Onboarding/Plus/UpgradeTier.swift
  podcasts/Profile - SwiftUI/Common Views/SubscriptionBadge.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3322 [New onboarding] Upgrade Variant B - Timeline component
  podcasts.xcodeproj/project.pbxproj
  podcasts/IAPHelper.swift
  podcasts/Onboarding/Models/PlusPricingInfoModel.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeProductsView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeTimelineView.swift
  podcasts/Strings+Generated.swift
  podcasts/Subscription.xcassets/unlocked-large.imageset/Contents.json
  podcasts/Subscription.xcassets/unlocked-large.imageset/locked-large.svg
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3325 [Playlists] Replacing Filters with Playlists
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  podcasts/MainTabBarController.swift
  podcasts/PlaylistsViewController.swift
  podcasts/Strings+Generated.swift
  podcasts/TabBar.xcassets/playlists_tab.imageset/Contents.json
  podcasts/TabBar.xcassets/playlists_tab.imageset/list.svg
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Playlists

#3334 GRDB: Enable
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
Labels: [Type] Tech Debt

#3336 Merge release/7.93 into trunk
  .configure
  .configure-files/pocket_casts_credentials.json.enc
  CHANGELOG.md
  Modules/Utils/Sources/PocketCastsUtils/Feature Flags/FeatureFlag.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/AppDelegate.swift
  podcasts/MainTabBarController.swift
  podcasts/NetworkUtils+Helpers.swift
  podcasts/Strings+Generated.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#3341 Merge release/7.93 into trunk
  config/Version.xcconfig
  podcasts/ca.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
Labels: Releases

#3343 Merge release/7.94 into trunk
  CHANGELOG.md
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts/Resources/release_notes.txt
Labels: Releases

#3348 Disable purchases in TestFlight
  podcasts/IAPHelper.swift
Labels: [Type] Bug

#3350 Merge release/7.94 into trunk
  config/Version.xcconfig
  podcasts/DiscoverCollectionViewController+Search.swift
  podcasts/IAPHelper.swift
  podcasts/New Search/Helpers/SearchAnalyticsHelper.swift
  podcasts/New Search/SearchResultsViewController.swift
  podcasts/PodcastListViewController+Search.swift
  podcasts/ca.lproj/Localizable.strings
  podcasts/de.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/sv.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#3345 [New onboarding] pre select chapters contextual upgrade
  podcasts.xcodeproj/project.pbxproj
  podcasts/Onboarding/OnboardingFlow.swift
  podcasts/Onboarding/Plus/NewUpgrade/PreSelectChaptersAnimationView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3352 [New Onboarding] Ensure that contextual animation is centered on the first page
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
Labels: New Onboarding

#3353 Analytics adapter fix
  PocketCastsTests/Tests/Analytics/AnalyticsAdapterPersistenceTests.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/Analytics.swift
  podcasts/PrivacySettings/PrivacySettingsDataSource.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Bug

#3351 Fix the trending notification message
  CHANGELOG.md
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Type] Enhancement, [Project] Notifications Revamp

#3357 [Playlists] Address color updates and gesture
  podcasts/Onboarding/Encourage Account Creation/Banner/InformationalBannerViewModel.swift
  podcasts/PlaylistCell.swift
  podcasts/PlaylistsViewController+Table.swift
  podcasts/PlaylistsViewController.swift
Labels: [Project] Playlists

#3354 Scroll LogsView to bottom
  podcasts/Common SwiftUI/NonEditableTextView.swift
  podcasts/LogsView.swift
Labels: [Type] Enhancement, Logging

#3358 [New Onboarding] Bookmarks contextual upgrade screen
  podcasts.xcodeproj/project.pbxproj
  podcasts/Onboarding.xcassets/Login/Covers/login-cover-10.imageset/Contents.json
  podcasts/Onboarding.xcassets/Login/Covers/login-cover-10.imageset/login-cover-10.jpg
  podcasts/Onboarding/Plus/NewUpgrade/Animations/BookmarksAnimationView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: New Onboarding

#3359 GRDB: remove episode and podcast invalid entries
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
Labels: [Type] Bug

#3342 Banner Ads: Load from server
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler+Blaze.swift
  Modules/Server/Sources/PocketCastsServer/Public/Discover/DiscoverServerHandler.swift
  podcasts.xcodeproj/project.pbxproj
  podcasts/Common SwiftUI/BannerAdView.swift
  podcasts/NowPlayingPlayerItemViewController.swift
  podcasts/NowPlayingPlayerItemViewController.xib
  podcasts/PodcastListViewController+CollectionView.swift
  podcasts/PodcastListViewController.swift
  podcasts/UIApplication+OpenSafariVC.swift
Labels: [Project] Banner Ads

#3362 [Playlists] Onboarding & Tip
  podcasts.xcodeproj/project.pbxproj
  podcasts/AppDelegate.swift
  podcasts/Constants.swift
  podcasts/DeveloperMenu.swift
  podcasts/Filter.xcassets/playlist_onboarding_manual.imageset/Contents.json
  podcasts/Filter.xcassets/playlist_onboarding_manual.imageset/image 526.pdf
  podcasts/Filter.xcassets/playlist_onboarding_smart.imageset/Contents.json
  podcasts/Filter.xcassets/playlist_onboarding_smart.imageset/image 528.pdf
  podcasts/Playlists Onboarding/PlaylistsOnboardingCardView.swift
  podcasts/Playlists Onboarding/PlaylistsOnboardingView.swift
  podcasts/PlaylistsViewController+Table.swift
  podcasts/PlaylistsViewController.swift
  podcasts/Settings.swift
  podcasts/Strings+Generated.swift
  podcasts/en.lproj/Localizable.strings
Labels: [Project] Playlists

#3364 Merge release/7.94 into trunk
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
  PocketCastsTests/Tests/Analytics/AnalyticsAdapterPersistenceTests.swift
  config/Version.xcconfig
  fastlane/Frozen.strings
  podcasts.xcodeproj/project.pbxproj
  podcasts/Analytics/Analytics.swift
  podcasts/PrivacySettings/PrivacySettingsDataSource.swift
  podcasts/Strings+Generated.swift
  podcasts/de.lproj/Localizable.strings
  podcasts/en.lproj/Localizable.strings
  podcasts/es-MX.lproj/Localizable.strings
  podcasts/es.lproj/Localizable.strings
  podcasts/fr-CA.lproj/Localizable.strings
  podcasts/fr.lproj/Localizable.strings
  podcasts/it.lproj/Localizable.strings
  podcasts/ja.lproj/Localizable.strings
  podcasts/nl.lproj/Localizable.strings
  podcasts/pt-BR.lproj/Localizable.strings
  podcasts/ru.lproj/Localizable.strings
  podcasts/zh-Hans.lproj/Localizable.strings
  podcasts/zh-Hant.lproj/Localizable.strings
Labels: Releases

#3365 [New onboarding] Analytics
  podcasts/Analytics/AnalyticsEvent.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountView.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
Labels: New Onboarding

#3366 [New onboarding] Ex-plat analytics
  PocketCastsTests/Tests/ABTest/ABTestProviderTests.swift
  podcasts/ABTest/ABTest.swift
  podcasts/ABTest/ABTestProvider.swift
  podcasts/Onboarding/Plus/NewUpgrade/UpgradeAccountViewModel.swift
Labels: New Onboarding

#3369 Add logging when we update schema version
  Modules/DataModel/Sources/PocketCastsDataModel/Private/Managers/Util/DatabaseHelper.swift
Labels: Logging
